import type { Report, Section, ConsumerDutyOutcome } from "./types";

interface ExportOptions {
  includeInteractive: boolean;
  embedImages: boolean;
  minify: boolean;
  watermark?: string;
  includeMetadata: boolean;
}

const defaultOptions: ExportOptions = {
  includeInteractive: true,
  embedImages: true,
  minify: false,
  includeMetadata: true,
};

export function generateHTMLExport(
  report: Report,
  sections: Section[],
  outcomes: ConsumerDutyOutcome[],
  options: Partial<ExportOptions> = {}
): string {
  const opts = { ...defaultOptions, ...options };
  const publishDate = new Date().toISOString();

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(report.title)} - ${escapeHtml(report.period)}</title>
  ${opts.includeMetadata ? `
  <!-- CCRO Report Export Metadata -->
  <!-- Report: ${escapeHtml(report.title)} -->
  <!-- Period: ${escapeHtml(report.period)} -->
  <!-- Published: ${publishDate} -->
  <!-- Generated by Updraft CCRO Dashboard -->
  ` : ""}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
  <style>
    ${getExportCSS()}
  </style>
</head>
<body>
  ${opts.watermark ? `<div class="watermark">${escapeHtml(opts.watermark)}</div>` : ""}

  <header class="report-header">
    <div class="header-bg">
      <svg class="ambient-shape" viewBox="0 0 400 400"><circle cx="380" cy="20" r="120" fill="#E1BEE7" opacity="0.3"/></svg>
    </div>
    <h1>${escapeHtml(report.title)}</h1>
    <p class="period">${escapeHtml(report.period)}</p>
    <p class="meta">Updraft CCRO Report</p>
  </header>

  <main class="report-content">
    ${sections.sort((a, b) => a.position - b.position).map((section) => renderSection(section)).join("\n")}

    ${outcomes.length > 0 ? renderConsumerDutyDashboard(outcomes, opts.includeInteractive) : ""}
  </main>

  <footer class="report-footer">
    <p>Generated by Updraft CCRO Dashboard &bull; ${publishDate.split("T")[0]}</p>
    <p class="confidential">CONFIDENTIAL - For authorised recipients only</p>
  </footer>

  ${opts.includeInteractive ? getInteractiveScript() : ""}
</body>
</html>`;

  return opts.minify ? minifyHTML(html) : html;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function renderSection(section: Section): string {
  const style = buildSectionStyle(section);
  const content = section.content as Record<string, unknown>;

  switch (section.type) {
    case "TEXT_BLOCK":
      return `<section class="report-section" style="${style}">
        ${section.title ? `<h2>${escapeHtml(section.title)}</h2>` : ""}
        <div class="text-content">${content.html || ""}</div>
      </section>`;

    case "DATA_TABLE":
      return `<section class="report-section" style="${style}">
        ${section.title ? `<h2>${escapeHtml(section.title)}</h2>` : ""}
        ${renderDataTable(content)}
      </section>`;

    case "CARD_GRID":
      return `<section class="report-section" style="${style}">
        ${section.title ? `<h2>${escapeHtml(section.title)}</h2>` : ""}
        ${renderCardGrid(content)}
      </section>`;

    case "ACCORDION":
      return `<section class="report-section" style="${style}">
        ${section.title ? `<h2>${escapeHtml(section.title)}</h2>` : ""}
        ${renderAccordion(content)}
      </section>`;

    case "IMPORTED_COMPONENT":
      return `<section class="report-section imported-component" style="${style}">
        ${content.html || ""}
      </section>`;

    default:
      return `<section class="report-section" style="${style}">
        ${section.title ? `<h2>${escapeHtml(section.title)}</h2>` : ""}
        <div>${JSON.stringify(content)}</div>
      </section>`;
  }
}

function buildSectionStyle(section: Section): string {
  const sc = section.styleConfig || {};
  const parts: string[] = [];
  if (sc.backgroundColor) parts.push(`background-color:${sc.backgroundColor}`);
  if (sc.borderRadius) parts.push(`border-radius:${sc.borderRadius}px`);
  if (sc.borderWidth && sc.borderStyle !== "none") {
    parts.push(`border:${sc.borderWidth}px ${sc.borderStyle || "solid"} ${sc.borderColor || "#e5e7eb"}`);
  }
  if (sc.padding) {
    parts.push(`padding:${sc.padding.top}px ${sc.padding.right}px ${sc.padding.bottom}px ${sc.padding.left}px`);
  }
  if (sc.margin) {
    parts.push(`margin:${sc.margin.top}px ${sc.margin.right}px ${sc.margin.bottom}px ${sc.margin.left}px`);
  }
  return parts.join(";");
}

function renderDataTable(content: Record<string, unknown>): string {
  const headers = (content.headers as string[]) || [];
  const rows = (content.rows as string[][]) || [];
  return `<table class="data-table">
    <thead><tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("")}</tr></thead>
    <tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("")}</tbody>
  </table>`;
}

function renderCardGrid(content: Record<string, unknown>): string {
  const cards = (content.cards as Array<{ icon?: string; title: string; value: string; subtitle?: string }>) || [];
  return `<div class="card-grid">${cards.map((card) => `
    <div class="stat-card">
      ${card.icon ? `<div class="card-icon">${card.icon}</div>` : ""}
      <div class="card-value">${escapeHtml(card.value)}</div>
      <div class="card-title">${escapeHtml(card.title)}</div>
      ${card.subtitle ? `<div class="card-subtitle">${escapeHtml(card.subtitle)}</div>` : ""}
    </div>`).join("")}
  </div>`;
}

function renderAccordion(content: Record<string, unknown>): string {
  const items = (content.items as Array<{ title: string; content: string }>) || [];
  return `<div class="accordion">${items.map((item, i) => `
    <details class="accordion-item" ${i === 0 ? "open" : ""}>
      <summary>${escapeHtml(item.title)}</summary>
      <div class="accordion-content">${item.content}</div>
    </details>`).join("")}
  </div>`;
}

function renderConsumerDutyDashboard(outcomes: ConsumerDutyOutcome[], interactive: boolean): string {
  return `<section class="consumer-duty-section">
    <h2>Consumer Duty Dashboard</h2>
    <div class="outcome-grid">
      ${outcomes.sort((a, b) => a.position - b.position).map((outcome) => `
        <div class="outcome-card ${interactive ? "clickable" : ""}" data-outcome="${outcome.outcomeId}">
          <div class="outcome-rag rag-${outcome.ragStatus.toLowerCase()}">&bull;</div>
          <h3>${escapeHtml(outcome.name)}</h3>
          <p>${escapeHtml(outcome.shortDesc)}</p>
          <div class="measure-count">${outcome.measures?.length || 0} measures</div>
        </div>
      `).join("")}
    </div>
    ${outcomes.map((outcome) => `
      <div class="measures-panel" id="measures-${outcome.outcomeId}" style="display:none">
        <h3>${escapeHtml(outcome.name)} - Measures</h3>
        <div class="measures-grid">
          ${(outcome.measures || []).map((measure) => `
            <div class="measure-card clickable" data-measure="${measure.id}">
              <div class="measure-rag rag-${measure.ragStatus.toLowerCase()}">&bull;</div>
              <div class="measure-id">${escapeHtml(measure.measureId)}</div>
              <div class="measure-name">${escapeHtml(measure.name)}</div>
              <div class="measure-summary">${escapeHtml(measure.summary)}</div>
            </div>
          `).join("")}
        </div>
      </div>
    `).join("")}
  </section>`;
}

function getExportCSS(): string {
  return `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', system-ui, sans-serif; color: #374151; background: #F3F4F6; line-height: 1.5; }
    .report-header { background: linear-gradient(135deg, #311B92, #673AB7); color: white; padding: 3rem 2rem; position: relative; overflow: hidden; }
    .report-header h1 { font-size: 2rem; font-weight: 700; letter-spacing: -0.02em; }
    .report-header .period { font-size: 1.25rem; opacity: 0.9; margin-top: 0.5rem; }
    .report-header .meta { font-size: 0.875rem; opacity: 0.7; margin-top: 0.25rem; }
    .ambient-shape { position: absolute; top: 0; right: 0; width: 300px; height: 300px; pointer-events: none; }
    .report-content { max-width: 1200px; margin: 2rem auto; padding: 0 1rem; }
    .report-section { background: white; border-radius: 1rem; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); border: 1px solid #e5e7eb; }
    .report-section h2 { font-size: 1.5rem; font-weight: 700; color: #311B92; margin-bottom: 1rem; letter-spacing: -0.01em; }
    .text-content { font-size: 0.875rem; line-height: 1.6; }
    .text-content p { margin: 0.5em 0; }
    .text-content ul, .text-content ol { padding-left: 1.5em; margin: 0.5em 0; }
    .text-content blockquote { border-left: 3px solid #7B1FA2; padding-left: 1rem; color: #6b7280; font-style: italic; margin: 1em 0; }
    .data-table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
    .data-table th { background: #F3F4F6; font-weight: 600; text-align: left; padding: 0.75rem; border: 1px solid #e5e7eb; }
    .data-table td { padding: 0.75rem; border: 1px solid #e5e7eb; }
    .card-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }
    .stat-card { background: #F9FAFB; border-radius: 0.75rem; padding: 1.25rem; text-align: center; border: 1px solid #e5e7eb; }
    .card-value { font-size: 1.5rem; font-weight: 700; color: #311B92; }
    .card-title { font-size: 0.875rem; color: #6b7280; margin-top: 0.25rem; }
    .card-subtitle { font-size: 0.75rem; color: #9ca3af; }
    .accordion-item { border: 1px solid #e5e7eb; border-radius: 0.5rem; margin-bottom: 0.5rem; }
    .accordion-item summary { padding: 0.75rem 1rem; cursor: pointer; font-weight: 600; }
    .accordion-content { padding: 0 1rem 0.75rem; font-size: 0.875rem; }
    .consumer-duty-section { margin-top: 2rem; }
    .consumer-duty-section h2 { font-size: 1.5rem; font-weight: 700; color: #311B92; margin-bottom: 1rem; }
    .outcome-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; margin-bottom: 1.5rem; }
    @media (max-width: 900px) { .outcome-grid { grid-template-columns: repeat(2, 1fr); } }
    @media (max-width: 600px) { .outcome-grid { grid-template-columns: 1fr; } }
    .outcome-card { background: rgba(255,255,255,0.9); backdrop-filter: blur(20px); border-radius: 1.5rem; padding: 1.5rem; border: 1px solid rgba(255,255,255,0.3); box-shadow: 0 8px 32px rgba(31,38,135,0.1); transition: all 0.3s; }
    .outcome-card.clickable { cursor: pointer; }
    .outcome-card:hover { transform: translateY(-4px); background: rgba(255,255,255,0.95); }
    .outcome-card h3 { font-size: 1.1rem; font-weight: 600; margin: 0.5rem 0 0.25rem; }
    .outcome-card p { font-size: 0.8rem; color: #6b7280; }
    .outcome-rag, .measure-rag { font-size: 2rem; line-height: 1; }
    .rag-good { color: #10B981; }
    .rag-warning { color: #F59E0B; }
    .rag-harm { color: #DC2626; }
    .measures-panel { background: white; border-radius: 1rem; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); animation: slideUp 0.6s cubic-bezier(0.16,1,0.3,1); }
    .measures-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1rem; margin-top: 1rem; }
    .measure-card { background: #F9FAFB; border-radius: 0.75rem; padding: 1rem; border: 1px solid #e5e7eb; cursor: pointer; transition: all 0.2s; }
    .measure-card:hover { border-color: #BA68C8; transform: translateY(-2px); }
    .measure-id { font-size: 0.75rem; color: #9ca3af; font-weight: 500; }
    .measure-name { font-weight: 600; margin: 0.25rem 0; }
    .measure-summary { font-size: 0.8rem; color: #6b7280; }
    .measure-count { font-size: 0.75rem; color: #9ca3af; margin-top: 0.5rem; }
    .report-footer { text-align: center; padding: 2rem; color: #9ca3af; font-size: 0.75rem; }
    .confidential { color: #DC2626; font-weight: 600; margin-top: 0.5rem; }
    .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%,-50%) rotate(-45deg); font-size: 4rem; color: rgba(0,0,0,0.03); pointer-events: none; z-index: 1000; white-space: nowrap; }
    @keyframes slideUp { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
    @media print { .report-header { background: #311B92 !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; } .outcome-card, .measure-card { break-inside: avoid; } }
  `;
}

function getInteractiveScript(): string {
  return `<script>
    document.querySelectorAll('.outcome-card.clickable').forEach(card => {
      card.addEventListener('click', () => {
        const outcomeId = card.dataset.outcome;
        const panel = document.getElementById('measures-' + outcomeId);
        if (panel) {
          const isVisible = panel.style.display !== 'none';
          document.querySelectorAll('.measures-panel').forEach(p => p.style.display = 'none');
          if (!isVisible) panel.style.display = 'block';
        }
      });
    });
  </script>`;
}

function minifyHTML(html: string): string {
  return html.replace(/\n\s*/g, "").replace(/\s{2,}/g, " ");
}
