import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";

const connStr = process.env.DATABASE_URL as string;
const adapter = new PrismaPg({ connectionString: connStr });
const prisma = new PrismaClient({ adapter });

/**
 * Creates controls that the policy CSV references but don't exist yet:
 * - CTRL-CDR-001..020: Conduct Risk (CSV uses CDR, markdown used COND)
 * - CTRL-FVA-001..008: Fair Value Assessment (CSV uses FVA, markdown used FV)
 * - CTRL-WB-001..012: Whistleblowing Policy (new policy, no controls yet)
 */

interface ControlDef {
  controlRef: string;
  controlName: string;
  controlDescription: string;
  businessAreaId: string;
  controlOwnerId: string;
  consumerDutyOutcome: "PRODUCTS_AND_SERVICES" | "CONSUMER_UNDERSTANDING" | "CONSUMER_SUPPORT" | "GOVERNANCE_CULTURE_OVERSIGHT";
  controlFrequency: "DAILY" | "WEEKLY" | "MONTHLY" | "QUARTERLY" | "BI_ANNUAL" | "ANNUAL" | "EVENT_DRIVEN";
  controlType: "PREVENTATIVE" | "DETECTIVE" | "CORRECTIVE" | "DIRECTIVE";
}

// ── Conduct Risk Controls (CDR) ─────────────────────────────────────
const CDR_CONTROLS: ControlDef[] = [
  { controlRef: "CTRL-CDR-001", controlName: "Consumer Duty Strategic Integration", controlDescription: "The Board and senior management integrate Consumer Duty (PRIN 12) requirements into the firm's overall business strategy, ensuring that customer outcomes are embedded in strategic planning, product development, and operational decision-making. The Compliance function reviews the strategy annually to confirm alignment with the four Consumer Duty outcomes. Evidence includes Board strategy papers, minutes documenting Consumer Duty discussion, and strategic plan alignment assessments.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-CDR-002", controlName: "Product Design Consumer Needs Assessment", controlDescription: "Before launching any new product or making material changes to existing products, the Product and Compliance teams conduct a formal consumer needs assessment to verify the product meets identified customer needs and does not cause foreseeable harm. The assessment considers target market definition, product features, pricing, distribution strategy, and potential for customer detriment. Evidence includes consumer needs assessment templates, sign-off records, and target market documentation.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "PRODUCTS_AND_SERVICES", controlFrequency: "EVENT_DRIVEN", controlType: "PREVENTATIVE" },
  { controlRef: "CTRL-CDR-003", controlName: "Price Fairness and Transparency Review", controlDescription: "The Compliance and Finance functions conduct periodic reviews of product pricing to ensure fairness and transparency in line with Consumer Duty Outcome 2 (Price and Value). Reviews assess whether the total cost of credit is reasonable relative to benefits, whether fees are clearly disclosed, and whether pricing practices do not exploit customer vulnerabilities. Evidence includes pricing review reports, fair value assessment documentation, and competitive benchmarking analysis.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "PRODUCTS_AND_SERVICES", controlFrequency: "ANNUAL", controlType: "DETECTIVE" },
  { controlRef: "CTRL-CDR-004", controlName: "Consumer Communication Clarity Assessment", controlDescription: "All customer-facing communications are assessed for clarity, accuracy, and accessibility before publication. The Compliance function reviews communications against readability standards (targeting Grade 6-8 reading level), plain English principles, and Consumer Duty Outcome 3 (Consumer Understanding) requirements. Communications must be fair, clear, and not misleading, with material terms prominently displayed. Evidence includes communication review checklists, readability scores, and approval records.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "CONSUMER_UNDERSTANDING", controlFrequency: "EVENT_DRIVEN", controlType: "PREVENTATIVE" },
  { controlRef: "CTRL-CDR-005", controlName: "Post-Sale Consumer Support Provision", controlDescription: "The Customer Service function provides ongoing support to customers throughout the product lifecycle, ensuring that customers can access help when needed and are treated fairly at all touchpoints. This includes complaint handling, account management, arrears support, and vulnerability identification. The Compliance function monitors service quality metrics and complaint volumes to identify conduct concerns. Evidence includes service level monitoring reports, customer satisfaction data, and complaint trend analysis.", businessAreaId: "ba-customer-svc", controlOwnerId: "user-cath", consumerDutyOutcome: "CONSUMER_SUPPORT", controlFrequency: "DAILY", controlType: "PREVENTATIVE" },
  { controlRef: "CTRL-CDR-006", controlName: "Cross-Cutting Rules Application", controlDescription: "All staff are required to apply the FCA's cross-cutting rules (act in good faith, avoid foreseeable harm, enable customers to pursue their financial objectives) in their day-to-day activities. The Compliance function embeds these principles through training, policies, and operational guidance. Monitoring of adherence is conducted through quality assurance reviews, complaint analysis, and management information reporting. Evidence includes training completion records, QA review results, and conduct MI dashboards.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "DAILY", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-CDR-007", controlName: "FCA Five Conduct Questions Assessment", controlDescription: "The Board and senior management assess the firm's conduct against the FCA's five conduct questions at least annually as part of governance review. The assessment covers: (1) what could cause customer harm, (2) what the firm has done to identify and mitigate harm, (3) what outcomes customers are experiencing, (4) whether staff are acting in customers' interests, and (5) how the firm ensures good outcomes. Evidence includes Board assessment papers, governance minutes, and action plans.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DETECTIVE" },
  { controlRef: "CTRL-CDR-008", controlName: "Risk Culture Framework Implementation", controlDescription: "The CRCO and senior management maintain a risk culture framework that promotes ethical behaviour, customer-first thinking, and appropriate risk-taking. The framework includes tone from the top communications, conduct expectations, reward structures that do not incentivise poor conduct, and mechanisms for staff to raise concerns. Board oversight ensures the framework remains effective. Evidence includes culture survey results, Board risk culture reports, and whistleblowing activity analysis.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "QUARTERLY", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-CDR-009", controlName: "Conduct Risk Register Maintenance", controlDescription: "The Compliance function maintains a conduct risk register that identifies, assesses, and tracks all material conduct risks across the firm. Each risk is assessed for likelihood and impact, assigned an owner, and monitored with defined mitigating controls. The register is reviewed quarterly and reported to the Board. New risks identified through complaints, regulatory changes, or operational events are added promptly. Evidence includes the current conduct risk register, quarterly review minutes, and risk movement reports.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "QUARTERLY", controlType: "DETECTIVE" },
  { controlRef: "CTRL-CDR-010", controlName: "Conduct Rules Training Delivery", controlDescription: "The Compliance and HR functions deliver mandatory conduct rules training to all staff annually, with additional role-specific training for customer-facing and management roles. Training covers the Individual Conduct Rules, Senior Manager Conduct Rules, Consumer Duty obligations, and firm-specific conduct expectations. New joiners complete induction training within their first month. Evidence includes training materials, attendance records, competency assessment results, and remedial training logs.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-CDR-011", controlName: "Remuneration Policy Compliance", controlDescription: "The HR and Compliance functions review remuneration policies and incentive structures annually to ensure they do not create conflicts of interest or incentivise behaviours that could lead to poor customer outcomes. Variable pay and bonus schemes are assessed for conduct risk, with particular attention to sales targets that could drive inappropriate lending. Evidence includes remuneration policy review reports, incentive structure assessment, and Board approval of remuneration frameworks.", businessAreaId: "ba-hr", controlOwnerId: "user-david", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DETECTIVE" },
  { controlRef: "CTRL-CDR-012", controlName: "Three Lines of Defence Implementation", controlDescription: "The firm operates a three lines of defence model: first line (business units own and manage risk), second line (Compliance and Risk provide oversight and challenge), and third line (Internal Audit provides independent assurance). Each line has defined responsibilities, reporting lines, and escalation procedures. The model is validated annually to ensure effectiveness and independence. Evidence includes three lines of defence framework documentation, validation reports, and escalation records.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-CDR-013", controlName: "Risk and Control Self-Assessment Execution", controlDescription: "Business unit managers complete Risk and Control Self-Assessments (RCSAs) quarterly to evaluate the effectiveness of controls within their areas. The RCSA process requires managers to assess inherent risk, control effectiveness, and residual risk for each conduct risk, with findings reported to the CRCO. Where controls are assessed as ineffective, remediation actions are assigned with deadlines. Evidence includes completed RCSA templates, findings summaries, and action tracking reports.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "QUARTERLY", controlType: "DETECTIVE" },
  { controlRef: "CTRL-CDR-014", controlName: "Customer Outcome Radar MI Report Generation", controlDescription: "The Compliance function produces a monthly Customer Outcome Radar management information report that tracks key conduct and customer outcome metrics across the four Consumer Duty outcomes. The report includes complaint volumes and trends, product performance data, customer satisfaction scores, vulnerability identification rates, and any adverse regulatory developments. The MI is distributed to senior management and the Board. Evidence includes monthly MI reports, distribution records, and management action notes.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "MONTHLY", controlType: "DETECTIVE" },
  { controlRef: "CTRL-CDR-015", controlName: "Risk Appetite Framework Application", controlDescription: "The Board sets and annually reviews the firm's conduct risk appetite, defining the level of conduct risk the firm is willing to accept in pursuit of its strategic objectives. The risk appetite is expressed through quantitative thresholds (e.g., maximum complaint ratios, FOS overturn rates) and qualitative statements. Breaches of risk appetite trigger escalation and remediation. Evidence includes risk appetite statement, Board approval minutes, and breach notification records.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-CDR-016", controlName: "Regulatory Horizon Scanning", controlDescription: "The Compliance function conducts ongoing regulatory horizon scanning to identify emerging regulatory requirements, FCA enforcement trends, and industry developments that may impact the firm's conduct risk profile. Quarterly reports summarise key developments and assess their implications for the firm's policies, controls, and operations. Significant changes trigger impact assessments and policy updates. Evidence includes horizon scanning reports, impact assessment documentation, and policy change records.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "QUARTERLY", controlType: "DETECTIVE" },
  { controlRef: "CTRL-CDR-017", controlName: "EDI Commitment Implementation", controlDescription: "The firm implements its Equality, Diversity, and Inclusion (EDI) commitment by embedding inclusive practices into customer-facing processes, product design, and internal operations. The Compliance function audits EDI practices annually to ensure compliance with the Equality Act 2010 and alignment with FCA expectations around diversity in the financial services sector. Evidence includes EDI policy documentation, annual audit reports, and demographic monitoring data.", businessAreaId: "ba-hr", controlOwnerId: "user-david", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-CDR-018", controlName: "CRCO Independence and Access", controlDescription: "The Chief Risk and Compliance Officer (CRCO) maintains independence from commercial and operational pressures, with direct access to the Board and Audit Committee. The CRCO has authority to escalate conduct concerns without management approval and can require business activities to be suspended where serious customer harm is identified. The Board reviews the CRCO's independence and access arrangements annually. Evidence includes CRCO role description, Board access records, and escalation logs.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-CDR-019", controlName: "Third-Party Audit of Conduct Controls", controlDescription: "An independent third party (internal audit or external consultant) conducts an annual audit of the firm's conduct risk management framework and controls. The audit assesses the design and operating effectiveness of conduct controls, the adequacy of governance arrangements, and the firm's compliance with Consumer Duty requirements. Findings are reported to the Audit Committee with recommended remediation actions. Evidence includes audit reports, management responses, and action tracking.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DETECTIVE" },
  { controlRef: "CTRL-CDR-020", controlName: "Conduct Policy Review and Update", controlDescription: "The Compliance function reviews the Conduct Risk Policy on an 18-month cycle (or sooner if triggered by regulatory changes, significant incidents, or material business changes). The review assesses whether the policy remains fit for purpose, reflects current regulatory requirements, and addresses emerging conduct risks. Updated policies require Board approval before implementation. Evidence includes policy review documentation, change logs, and Board approval minutes.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "QUARTERLY", controlType: "DIRECTIVE" },
];

// ── Fair Value Assessment Controls (FVA) ────────────────────────────
const FVA_CONTROLS: ControlDef[] = [
  { controlRef: "CTRL-FVA-001", controlName: "Consumer Duty Fair Value Alignment", controlDescription: "The Compliance function ensures the Fair Value Assessment process is fully aligned with Consumer Duty Outcome 2 (Price and Value) requirements. All product assessments are conducted within the Consumer Duty framework, evaluating whether the price paid by customers is reasonable relative to the overall benefits received. The framework is reviewed annually for continued alignment with FCA expectations. Evidence includes framework alignment assessments, regulatory mapping documentation, and Board approval records.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "PRODUCTS_AND_SERVICES", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-FVA-002", controlName: "New Product Approval Fair Value Gate", controlDescription: "Before any new product is approved for launch, the Product team must complete a comprehensive fair value assessment covering eight key requirements: target market identification, value proposition clarity, fair value concerns assessment, distribution channel alignment, customer needs research, pricing structure definition, customer communications framework, and monitoring metrics establishment. The assessment requires Compliance and Credit Committee sign-off. Evidence includes completed assessment templates, approval records, and product governance documentation.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "PRODUCTS_AND_SERVICES", controlFrequency: "EVENT_DRIVEN", controlType: "PREVENTATIVE" },
  { controlRef: "CTRL-FVA-003", controlName: "Four-Pillar Value Assessment Framework", controlDescription: "Each fair value assessment follows a structured four-pillar framework: (1) Benefits analysis — evaluating all product benefits against customer expectations, (2) Price analysis — assessing total cost of credit including fees, interest, and ancillary charges against market comparators, (3) Costs analysis — reviewing internal costs and margins to ensure pricing is not excessive, and (4) Limitations disclosure — identifying and transparently communicating all product limitations and exclusions. Evidence includes completed four-pillar assessment templates, supporting analysis, and sign-off records.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "PRODUCTS_AND_SERVICES", controlFrequency: "EVENT_DRIVEN", controlType: "DETECTIVE" },
  { controlRef: "CTRL-FVA-004", controlName: "Fair Value Assessment Documentation", controlDescription: "The Product team maintains comprehensive documentation for every fair value assessment, capturing the assessment date, outcome, product information, target market definition, distribution channels, remuneration structure, and signed authorisation. The standardised template ensures consistency across assessments and provides a clear audit trail for regulatory review. Documentation is retained for a minimum of 6 years. Evidence includes completed assessment templates, version-controlled records, and document retention schedules.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "PRODUCTS_AND_SERVICES", controlFrequency: "EVENT_DRIVEN", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-FVA-005", controlName: "Target Market Definition and Validation", controlDescription: "For each product, the Product team defines and validates the target market with granularity, including customer type (employed, self-employed, specific income ranges), distribution method (direct, broker, aggregator), expected product lifespan, and intended use case. The target market definition is validated through customer research and market data analysis to confirm the product meets genuine customer needs. Evidence includes target market documentation, customer research reports, and market analysis.", businessAreaId: "ba-compliance", controlOwnerId: "user-chris", consumerDutyOutcome: "PRODUCTS_AND_SERVICES", controlFrequency: "ANNUAL", controlType: "PREVENTATIVE" },
  { controlRef: "CTRL-FVA-006", controlName: "Customer Communications Fair Value Framework", controlDescription: "The Compliance and Marketing functions ensure customer-facing communications clearly and fairly communicate product benefits, costs, limitations, and the overall fair value proposition. Communications are tested for customer comprehension before deployment. The framework ensures that marketing claims are substantiated, that benefits are not overstated, and that limitations are not buried in small print. Evidence includes communication review records, comprehension testing results, and approval documentation.", businessAreaId: "ba-finprom", controlOwnerId: "user-cath", consumerDutyOutcome: "CONSUMER_UNDERSTANDING", controlFrequency: "EVENT_DRIVEN", controlType: "PREVENTATIVE" },
  { controlRef: "CTRL-FVA-007", controlName: "Ongoing Fair Value Monitoring", controlDescription: "The Compliance function operates an ongoing monitoring framework for all live products, tracking: cost of credit relative to market, complaint volumes and themes, service delivery quality, customer communication effectiveness, vulnerability screening outcomes, and target market re-evaluation triggers. Monthly monitoring reports identify any drift from fair value and trigger remediation where thresholds are breached. Evidence includes monthly monitoring reports, threshold breach notifications, and remediation action logs.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "PRODUCTS_AND_SERVICES", controlFrequency: "MONTHLY", controlType: "DETECTIVE" },
  { controlRef: "CTRL-FVA-008", controlName: "Vulnerable Customer Fair Value Protections", controlDescription: "The fair value assessment process integrates enhanced protections for vulnerable customers at every stage. Assessments consider whether vulnerable customer segments may experience worse outcomes, whether pricing disproportionately impacts vulnerable groups, and whether communications are accessible to customers with additional needs. Ongoing monitoring tracks vulnerable customer outcomes separately to identify any fair value disparities. Evidence includes vulnerability impact assessments, outcome tracking reports, and remediation records.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "CONSUMER_SUPPORT", controlFrequency: "EVENT_DRIVEN", controlType: "PREVENTATIVE" },
];

// ── Whistleblowing Controls (WB) ────────────────────────────────────
const WB_CONTROLS: ControlDef[] = [
  { controlRef: "CTRL-WB-001", controlName: "Whistleblowing Policy Framework", controlDescription: "The Compliance function maintains a comprehensive whistleblowing policy that establishes the framework for reporting suspected wrongdoing, ensuring compliance with the Public Interest Disclosure Act 1998 (PIDA) and FCA SYSC 18 requirements. The policy clearly defines reportable concerns including criminal activity, regulatory breaches, health and safety risks, financial fraud, bribery, and deliberate concealment. It is reviewed annually and approved by the Board. Evidence includes current policy documentation, Board approval minutes, and version control records.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-WB-002", controlName: "Confidential Reporting Channels", controlDescription: "The firm provides multiple confidential reporting channels for whistleblowers, including direct reporting to line managers, the CRCO, senior management, and a dedicated confidential hotline. All channels guarantee confidentiality and are monitored by the Compliance function to ensure reports are received and actioned promptly. Channel accessibility is communicated to all staff during induction and annual training. Evidence includes channel documentation, accessibility testing records, and usage monitoring reports.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "PREVENTATIVE" },
  { controlRef: "CTRL-WB-003", controlName: "Whistleblower Protection Guarantee", controlDescription: "The firm provides comprehensive protection for whistleblowers against retaliation, victimisation, dismissal, or any detrimental treatment as a result of making a protected disclosure. The CRCO is responsible for monitoring that protections are maintained throughout and after investigation. Any allegations of retaliation are investigated immediately and treated as serious disciplinary matters. Evidence includes protection commitment documentation, monitoring records, and investigation files where relevant.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "EVENT_DRIVEN", controlType: "PREVENTATIVE" },
  { controlRef: "CTRL-WB-004", controlName: "Whistleblowing Investigation Procedure", controlDescription: "All whistleblowing reports are investigated promptly, thoroughly, and impartially by appropriately qualified personnel independent of the area under investigation. The investigation procedure includes evidence gathering, witness interviews, timeline documentation, and findings assessment. The CRCO oversees all investigations and reports outcomes to the Board. Investigations are completed within a reasonable timeframe with regular progress updates to the reporter. Evidence includes investigation procedure documentation, case files, and outcome reports.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "EVENT_DRIVEN", controlType: "DETECTIVE" },
  { controlRef: "CTRL-WB-005", controlName: "Investigation Outcome Communication", controlDescription: "Whistleblowers are informed of the outcome of investigations into their reports, subject to legal and confidentiality constraints. The CRCO ensures that communication is timely, clear, and explains any actions taken or reasons for conclusions reached. Where the reporter is not satisfied with the outcome, the external reporting options (FCA, PRA, Serious Fraud Office) are explained. Evidence includes outcome communication records, reporter acknowledgement, and external referral documentation where applicable.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "EVENT_DRIVEN", controlType: "CORRECTIVE" },
  { controlRef: "CTRL-WB-006", controlName: "Remediation Action Tracking", controlDescription: "Where whistleblowing investigations identify wrongdoing or control failures, the Compliance function assigns and tracks remediation actions with defined owners and deadlines. Actions may include disciplinary proceedings, policy updates, control enhancements, regulatory notifications, or process changes. The Board receives regular updates on remediation progress. Evidence includes action tracking registers, completion evidence, and Board progress reports.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "EVENT_DRIVEN", controlType: "CORRECTIVE" },
  { controlRef: "CTRL-WB-007", controlName: "FCA Regulatory Notification", controlDescription: "The CRCO assesses whether whistleblowing reports require notification to the FCA or other regulatory bodies. Matters involving potential regulatory breaches, market abuse, financial crime, or systemic risks are reported to the relevant regulator within required timeframes. The firm maintains a record of all regulatory notifications and their outcomes. Evidence includes regulatory notification records, FCA acknowledgement correspondence, and outcome tracking.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "EVENT_DRIVEN", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-WB-008", controlName: "Annual Whistleblowing Training", controlDescription: "All staff receive mandatory annual training on the whistleblowing policy, covering what constitutes a reportable concern, how to make a report, available reporting channels, protections available, and the firm's commitment to an open culture. New joiners receive training during induction. Training materials are reviewed annually for accuracy and relevance. Evidence includes training materials, attendance records, competency assessments, and induction completion logs.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-WB-009", controlName: "Whistleblowing Champion Appointment", controlDescription: "The firm appoints a Whistleblowing Champion at Board level (or equivalent) responsible for ensuring the whistleblowing arrangements are effective and that staff feel able to raise concerns freely. The Champion has direct oversight of the whistleblowing process and reports to the Board on its effectiveness, including the number and nature of reports received, investigation outcomes, and any systemic issues identified. Evidence includes Champion appointment documentation, Board reports, and effectiveness assessment records.", businessAreaId: "ba-compliance", controlOwnerId: "user-ceo", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-WB-010", controlName: "Anonymous Reporting Capability", controlDescription: "The firm's whistleblowing arrangements allow for anonymous reporting where the reporter prefers not to identify themselves. Anonymous reports are investigated with the same rigour as identified reports, although the firm communicates that providing contact details enables better investigation and feedback. Anonymous reporting mechanisms are tested periodically to ensure they function correctly. Evidence includes anonymous reporting system documentation, testing records, and usage statistics.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "PREVENTATIVE" },
  { controlRef: "CTRL-WB-011", controlName: "Whistleblowing Record Keeping", controlDescription: "The Compliance function maintains comprehensive records of all whistleblowing reports, investigations, outcomes, and remediation actions. Records are stored securely with restricted access to protect confidentiality. Records are retained in accordance with the firm's data retention policy (minimum 6 years). The CRCO ensures record quality is sufficient for regulatory review. Evidence includes records management procedures, access control documentation, and retention schedule compliance.", businessAreaId: "ba-compliance", controlOwnerId: "user-cath", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "EVENT_DRIVEN", controlType: "DIRECTIVE" },
  { controlRef: "CTRL-WB-012", controlName: "Annual Whistleblowing Effectiveness Review", controlDescription: "The Board conducts an annual review of the effectiveness of the firm's whistleblowing arrangements, assessing whether staff feel able to raise concerns, whether investigations are conducted properly, whether outcomes are appropriate, and whether the firm's culture supports open reporting. The review considers report volumes, investigation quality, reporter satisfaction, and benchmarking against industry practice. Evidence includes annual effectiveness review report, Board discussion minutes, and improvement action plans.", businessAreaId: "ba-compliance", controlOwnerId: "user-ceo", consumerDutyOutcome: "GOVERNANCE_CULTURE_OVERSIGHT", controlFrequency: "ANNUAL", controlType: "DETECTIVE" },
];

async function main() {
  console.log("Creating missing controls (CDR, FVA, WB)");
  console.log("─".repeat(60));

  const allDefs = [...CDR_CONTROLS, ...FVA_CONTROLS, ...WB_CONTROLS];
  let created = 0;
  let skipped = 0;

  for (const def of allDefs) {
    const existing = await prisma.control.findUnique({ where: { controlRef: def.controlRef } });
    if (existing) {
      skipped++;
      continue;
    }

    await prisma.control.create({
      data: {
        controlRef: def.controlRef,
        controlName: def.controlName,
        controlDescription: def.controlDescription,
        businessAreaId: def.businessAreaId,
        controlOwnerId: def.controlOwnerId,
        consumerDutyOutcome: def.consumerDutyOutcome,
        controlFrequency: def.controlFrequency,
        controlType: def.controlType,
        isActive: true,
        approvalStatus: "APPROVED",
        createdById: "user-cath",
      },
    });
    created++;
  }

  console.log(`Created: ${created}, Skipped: ${skipped}`);

  // Now link to policies
  const conductPolicy = await prisma.policy.findFirst({ where: { name: { contains: "Conduct Risk", mode: "insensitive" } } });
  const fvPolicy = await prisma.policy.findFirst({ where: { name: { contains: "Fair Value", mode: "insensitive" } } });
  const wbPolicy = await prisma.policy.findFirst({ where: { reference: "POL-021" } });

  let linked = 0;
  const linkDefs = [
    ...CDR_CONTROLS.map(c => ({ ref: c.controlRef, policyId: conductPolicy?.id })),
    ...FVA_CONTROLS.map(c => ({ ref: c.controlRef, policyId: fvPolicy?.id })),
    ...WB_CONTROLS.map(c => ({ ref: c.controlRef, policyId: wbPolicy?.id })),
  ];

  for (const { ref, policyId } of linkDefs) {
    if (!policyId) continue;
    const ctrl = await prisma.control.findUnique({ where: { controlRef: ref } });
    if (!ctrl) continue;
    try {
      await prisma.policyControlLink.upsert({
        where: { policyId_controlId: { policyId, controlId: ctrl.id } },
        update: {},
        create: { policyId, controlId: ctrl.id, linkedBy: "user-cath" },
      });
      linked++;
    } catch { /* already exists */ }
  }

  console.log(`Policy links created: ${linked}`);
  const total = await prisma.control.count();
  console.log(`Total controls in DB: ${total}`);

  await prisma.$disconnect();
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
