/**
 * Enriched descriptions for FIN-CRIME (CU-0219 to CU-0229), EMPLOYMENT (CU-0230 to CU-0251),
 * CORPORATE (CU-0252 to CU-0258), TAX (CU-0259 to CU-0263), FCA-GUIDANCE (CU-0264 to CU-0278),
 * ICO (CU-0279 to CU-0291), INDUSTRY (CU-0292 to CU-0304), OTHER-REGS (CU-0305 to CU-0312),
 * OP-RES (CU-0313 to CU-0317), MISC-LEG (CU-0318 to CU-0325), PAYMENTS (CU-0326 to CU-0327)
 */
export const REMAINING_DESCRIPTIONS: Record<string, string> = {
  // FIN-CRIME
  "CU-0219": "UK financial crime legislation creates a comprehensive framework of criminal offences, regulatory obligations and supervisory expectations covering anti-money laundering (AML), counter-terrorist financing (CTF), fraud prevention, bribery and corruption, sanctions compliance, and proceeds of crime. For a consumer credit firm, these obligations are both legally mandatory and operationally significant — non-compliance can result in criminal prosecution of the firm and its officers (with penalties including imprisonment), unlimited fines, FCA enforcement action, loss of authorisation, and severe reputational damage. The financial crime framework requires a risk-based approach: firms must assess, document and mitigate the specific money laundering, terrorist financing and fraud risks presented by their business model, customer base, products and delivery channels.",

  "CU-0220": "The Money Laundering, Terrorist Financing and Transfer of Funds (Information on the Payer) Regulations 2017 are the UK's primary AML/CTF legislation, implementing the Fourth and Fifth Money Laundering Directives. The Regulations mandate: firm-wide risk assessments (regulation 18), written policies, controls and procedures (regulation 19), customer due diligence (CDD) at onboarding (regulation 27), enhanced due diligence (EDD) for high-risk situations including PEPs (regulations 33-35), ongoing monitoring of business relationships (regulation 28), record retention for at least five years (regulation 40), appointment of an MLRO and senior management compliance officer (regulation 21), and staff training (regulation 24). The FCA is the supervisory authority for consumer credit firms and has enforcement powers including unlimited fines, cancellation of authorisation, and criminal prosecution. Non-compliance is a criminal offence carrying up to two years' imprisonment.",

  "CU-0221": "MLR Part 2 requires every firm in the regulated sector to carry out a written risk assessment identifying and assessing money laundering and terrorist financing risks, considering customer risk factors, geographic risk factors, product/service risk factors, transaction risk factors, and delivery channel risk factors. The assessment must be kept up to date, reviewed regularly, and provided to the FCA on request. The risk assessment forms the basis for the firm's AML programme — policies, procedures and controls must be proportionate to the identified risks. For a consumer credit firm, the risk assessment must specifically address the ML/TF risks associated with online lending, automated decisioning, third-party introductions, and the use of proceeds — the FCA has identified online lending and rapid decisioning as presenting heightened risks requiring appropriate technology controls and human oversight.",

  "CU-0222": "MLR Part 3 establishes the CDD framework: firms must identify the customer and verify their identity from a reliable independent source, identify and verify beneficial owners, and assess the purpose and intended nature of the business relationship. CDD must be completed before entering into a credit agreement. Enhanced due diligence is required for higher-risk situations (PEPs, high-risk third countries, complex transactions, and firm-assessed high-risk cases). Simplified due diligence is permitted where risk is assessed as low, but still requires CDD — only the extent, timing or type of measures may be adjusted. Ongoing monitoring under regulation 28(11) requires scrutiny of transactions throughout the relationship for consistency with the firm's knowledge of the customer. For a consumer credit firm, CDD is integral to the onboarding process and must be balanced with customer experience requirements.",

  "CU-0223": "MLR Part 4 establishes record-keeping and reporting obligations. Records of CDD measures, transaction records, and supporting evidence must be retained for at least five years from the end of the business relationship or occasional transaction. The MLRO must be appointed and must make suspicious activity reports to the NCA where required. Firms must also submit annual financial crime returns to the FCA and cooperate with information requests from law enforcement. For a consumer credit firm, this means comprehensive and auditable records of all identity verification documents, CDD assessments, ongoing monitoring activities, internal and external SARs, and training records — all readily accessible for supervisory review or law enforcement requests.",

  "CU-0224": "The Proceeds of Crime Act 2002 (POCA) establishes the UK's principal money laundering offences and the SAR reporting regime. Part 7 creates three ML offences: concealing criminal property (s.327), entering into arrangements facilitating criminal property (s.328), and acquiring/using/possessing criminal property (s.329). Sections 330-331 create disclosure offences for the regulated sector — it is a criminal offence to fail to make a SAR where you know, suspect, or have reasonable grounds to suspect money laundering. The suspicion threshold is deliberately low: 'a possibility which is more than fanciful.' Failure to file a SAR carries up to five years' imprisonment. Section 333A criminalises tipping off (revealing that a SAR has been filed). For a consumer credit firm, every employee encountering suspicious activity must report internally to the MLRO, who must then report to the NCA if appropriate.",

  "CU-0225": "The Terrorism Act 2000 creates a parallel regime for terrorist financing. Sections 15-18 establish offences relating to terrorist property: fund-raising (s.15), use and possession (s.16), funding arrangements (s.17), and money laundering of terrorist property (s.18). Section 19 imposes a disclosure obligation — failure to disclose as soon as reasonably practicable is a criminal offence carrying up to five years' imprisonment. The definition of 'terrorist property' is extremely broad. For a consumer credit firm, terrorist financing obligations operate alongside POCA: the MLRO must assess whether suspicious activity relates to money laundering or terrorist financing and submit the appropriate report. Firms must screen customers against the UK sanctions list and ensure no lending is provided to designated persons — penalties for substantive offences reach 14 years' imprisonment.",

  "CU-0226": "The Sanctions and Anti-Money Laundering Act 2018 provides the UK's post-Brexit domestic legal framework for imposing, implementing and enforcing sanctions independently of the EU. SAMLA empowers Ministers to make regulations imposing financial sanctions (asset freezes, prohibitions on making funds available to designated persons), trade sanctions, travel bans, and other restrictive measures. For a consumer credit firm, the primary obligation is to comply with UK sanctions by screening customers and counterparties against the UK Sanctions List maintained by OFSI (Office of Financial Sanctions Implementation), ensuring no funds are made available to designated persons, and reporting matches or breaches. Breach of financial sanctions is a strict liability criminal offence carrying up to seven years' imprisonment, and OFSI can impose civil penalties of up to £1 million or 50% of the breach value.",

  "CU-0227": "The Bribery Act 2010 establishes four principal offences: bribing another person (s.1), being bribed (s.2), bribing a foreign public official (s.6), and the strict liability corporate offence of failure to prevent bribery by associated persons (s.7). The s.7 offence is triggered when an employee, agent, subsidiary, contractor or intermediary bribes another person intending to benefit the organisation — the only defence is demonstrating 'adequate procedures' based on six Ministry of Justice principles: proportionate procedures, top-level commitment, risk assessment, due diligence, communication and training, and monitoring and review. Penalties include up to ten years' imprisonment for individuals and unlimited fines for organisations. For a consumer credit firm, the Act is relevant to relationships with introducers, brokers, lead generators, and any third parties — payments, hospitality and incentive arrangements must be assessed for bribery risk.",

  "CU-0228": "The Fraud Act 2006 defines the general criminal offence of fraud, committed in three ways: fraud by false representation (s.2), fraud by failing to disclose information (s.3), and fraud by abuse of position (s.4). All require dishonesty and intent to make a gain or cause loss — actual gain or loss need not be proved. Maximum sentence is ten years' imprisonment. For a consumer credit firm, the Act is relevant both defensively (application fraud, identity fraud, first-party fraud by borrowers) and offensively (the firm and employees could be prosecuted for false representations about rates, charges, or suitability). Under the Economic Crime and Corporate Transparency Act 2023, large organisations now face a corporate offence of failure to prevent fraud, requiring 'reasonable fraud prevention procedures' — a significant new compliance obligation for consumer credit firms of sufficient size.",

  "CU-0229": "The Criminal Finances Act 2017 introduced corporate criminal offences of failure to prevent the facilitation of UK tax evasion (s.45) and foreign tax evasion (s.46). The offence is triggered when: a taxpayer evades tax; an associated person (employee, agent, service provider) criminally facilitates that evasion; and the organisation failed to prevent the facilitation. This is strict liability — no need to prove management knowledge. The only defence is 'reasonable prevention procedures' following HMRC's six principles: risk assessment, proportionality, top-level commitment, due diligence, communication and training, and monitoring and review. For a consumer credit firm, this requires a risk assessment of tax evasion facilitation risks across the business — including staff, contractors, introducers and associated persons — and proportionate prevention procedures, policies and training. The penalty is an unlimited fine.",

  // EMPLOYMENT
  "CU-0230": "UK employment law creates a comprehensive framework of statutory rights and employer obligations covering the employment relationship from recruitment through termination. The framework encompasses unfair dismissal protection, redundancy rights, discrimination protections, working time limits, minimum wage requirements, pension auto-enrolment, health and safety duties, whistleblowing protection, family leave entitlements, and obligations to workers in non-standard employment arrangements. For a consumer credit firm, employment law compliance is both a legal obligation and a reputational imperative — employment tribunal claims and regulatory findings of poor workplace practices can damage the firm's standing with the FCA, which increasingly views workplace culture as indicative of customer treatment culture.",

  "CU-0231": "The Employment Rights Act 1996 is the cornerstone of UK employment law, establishing fundamental statutory rights for employees including: the right to a written statement of employment particulars (Part I), protection of wages (Part II), time off rights (Part VI), maternity and paternity leave rights (Part VIII), protection against unfair dismissal (Part X), redundancy payments (Part XI), and protection for whistleblowers making qualifying disclosures (Part IVA). For a consumer credit firm, the ERA creates the legal framework for the employment relationship with every member of staff — from day-one documentation requirements through to the procedures that must be followed in any termination decision. Compliance requires comprehensive employment contracts, documented policies and procedures, and HR capability to manage the full range of employment situations.",

  "CU-0232": "Part I of the ERA requires employers to provide employees with a written statement of employment particulars on or before the first day of employment (the Employment Rights (Employment Particulars and Paid Annual Leave) (Amendment) Regulations 2018 extended this to day-one). The statement must include: the names of employer and employee, start date, continuous employment date, remuneration, hours, holiday entitlement, place of work, job title, collective agreements, pension scheme, and notice periods. Additional particulars (disciplinary and grievance procedures, probationary periods) must be provided. For a consumer credit firm, this means every new hire must receive a compliant written statement on day one — failure to comply entitles the employee to claim compensation of two or four weeks' pay at tribunal.",

  "CU-0233": "Part IVA of the ERA provides protection for workers who make 'qualifying disclosures' about wrongdoing — commonly known as whistleblowing protection. A qualifying disclosure is any disclosure of information that the worker reasonably believes shows: a criminal offence, breach of legal obligation, miscarriage of justice, danger to health and safety, environmental damage, or deliberate concealment of any of these. Workers who suffer detriment or dismissal as a result of making a qualifying disclosure are entitled to bring claims to the employment tribunal, with no cap on compensation for automatically unfair whistleblowing dismissals. For a consumer credit firm, this intersects with SYSC 18 whistleblowing requirements — the firm must ensure that internal reporting channels are effective and that employees are not deterred from raising concerns about conduct, compliance or customer outcomes.",

  "CU-0234": "Part X of the ERA provides protection against unfair dismissal for employees with at least two years' continuous service (with certain automatically unfair reasons having no qualifying period, including whistleblowing, pregnancy, and asserting statutory rights). An employee who is dismissed can claim unfair dismissal at the employment tribunal if the employer cannot show the dismissal was for a potentially fair reason (capability, conduct, redundancy, statutory restriction, or 'some other substantial reason') and that the employer acted reasonably in treating that reason as sufficient, following a fair procedure. Compensation includes a basic award (calculated like redundancy pay) and a compensatory award (currently capped at £115,115 or 52 weeks' pay, whichever is lower). For a consumer credit firm, this means dismissal decisions must be substantively justified and procedurally fair, following the ACAS Code of Practice.",

  "CU-0235": "Part IX of the ERA establishes employees' rights to statutory redundancy payments where they have at least two years' continuous service and are dismissed by reason of redundancy (the employer ceasing to carry on the business, or a diminished need for employees to carry out work of a particular kind). Statutory redundancy pay is calculated based on age, length of service and weekly pay (subject to a cap, currently £700 per week). Employers must follow a fair redundancy process: pool selection, objective selection criteria, consultation (collective consultation under TULRCA for 20+ redundancies), and consideration of suitable alternative employment. For a consumer credit firm, redundancy obligations arise whenever organisational changes result in role reductions — non-compliance can result in unfair dismissal claims and protective awards.",

  "CU-0236": "The Equality Act 2010 is the UK's principal anti-discrimination statute, prohibiting discrimination on the basis of nine protected characteristics: age, disability, gender reassignment, marriage and civil partnership, pregnancy and maternity, race, religion or belief, sex, and sexual orientation. The Act covers both employment (Part 5) and the provision of services (Part 3), meaning a consumer credit firm must comply as both an employer and a service provider. Types of prohibited conduct include direct discrimination, indirect discrimination, harassment, victimisation, and failure to make reasonable adjustments for disability. For a consumer credit firm, the Equality Act is directly relevant to lending decisions (non-discriminatory underwriting), customer treatment (reasonable adjustments for disabled customers), marketing (non-discriminatory targeting), and employment practices (fair recruitment, equal pay, non-discriminatory promotion and dismissal).",

  "CU-0237": "Part 2 of the Equality Act defines the nine protected characteristics and the types of prohibited conduct. Direct discrimination occurs when a person is treated less favourably because of a protected characteristic. Indirect discrimination occurs when a provision, criterion or practice puts persons sharing a protected characteristic at a particular disadvantage compared with others, unless objectively justified. Harassment is unwanted conduct related to a protected characteristic that has the purpose or effect of violating dignity or creating an intimidating, hostile, degrading, humiliating or offensive environment. Victimisation is subjecting a person to detriment because they have done, or it is believed they will do, a protected act (such as bringing a discrimination claim). For a consumer credit firm, understanding these concepts is essential for both employment practices and customer-facing activities.",

  "CU-0238": "Part 3 of the Equality Act prohibits discrimination in the provision of services, directly applying to lending decisions and customer treatment. A financial services provider must not discriminate in the terms on which it provides services, by refusing to provide services, or by subjecting a person to any other detriment. The Act imposes a duty to make reasonable adjustments for disabled persons — in a financial services context, this includes accessible application processes, alternative communication formats, and adjustments to collections procedures for customers with mental health conditions or cognitive disabilities. There is a specific exception allowing financial services firms to use age as a factor in risk assessment and pricing where based on relevant actuarial data and proportionate. The FCA's Consumer Duty and vulnerability guidance increasingly require firms to embed equitable treatment into product design, service delivery and collections.",

  "CU-0239": "Part 5 of the Equality Act prohibits discrimination in employment — covering recruitment, terms and conditions, access to opportunities, promotion, transfer, training, and dismissal. Employers must not discriminate against employees or job applicants on any protected characteristic, must make reasonable adjustments for disabled employees, and must not victimise employees who raise discrimination complaints. The Act also establishes the equal pay framework (Part 5 Chapter 3), requiring that women and men receive equal pay for equal work, work rated as equivalent, or work of equal value. For a consumer credit firm, this means non-discriminatory recruitment processes, equal pay audits, reasonable adjustments for disabled employees, and training for managers on preventing workplace discrimination.",

  "CU-0240": "The Working Time Regulations 1998 implement the EU Working Time Directive, establishing maximum working hours (48 hours per week averaged over 17 weeks, with an individual opt-out right), minimum rest periods (11 consecutive hours daily rest, 24 hours weekly rest), rest breaks (20 minutes for shifts over 6 hours), night work limits (8 hours per 24-hour period averaged over 17 weeks), and annual leave entitlement (5.6 weeks, equivalent to 28 days for a five-day week). Workers cannot be subjected to detriment for refusing to opt out of the 48-hour limit. For a consumer credit firm, WTR compliance requires tracking working hours, ensuring rest breaks are taken, managing opt-out agreements where applicable, and administering holiday entitlement accurately — non-compliance can result in employment tribunal claims and HSE enforcement action.",

  "CU-0241": "The National Minimum Wage Act 1998 and National Minimum Wage Regulations require all employers to pay workers at least the applicable minimum wage rate, which varies by age: National Living Wage (21 and over), National Minimum Wage (18-20), reduced rate (under 18), and apprentice rate. Rates are reviewed annually and typically increase each April. Employers must maintain records of hours worked and pay for at least six years. HMRC enforces minimum wage compliance and can impose financial penalties (currently 200% of arrears, up to £20,000 per worker), name non-compliant employers publicly, and pursue criminal prosecution for deliberate non-payment. For a consumer credit firm, minimum wage compliance requires particular attention to salaried staff whose effective hourly rate may fall below the minimum if working excessive hours.",

  "CU-0242": "The Pensions Act 2008 established the auto-enrolment framework requiring all employers to automatically enrol eligible workers (aged 22 to state pension age, earning above the earnings trigger of £10,000 per year) into a qualifying workplace pension scheme. The employer must contribute at least 3% of qualifying earnings and the employee at least 5% (total minimum 8%). Employers must comply with ongoing duties including re-enrolment of opted-out workers every three years, maintaining registration with The Pensions Regulator (TPR), and submitting a re-declaration of compliance every three years. Non-compliance can result in escalating penalty notices from TPR, fixed penalties (£400), and daily compliance penalties (up to £10,000 per day depending on the number of employees). For a consumer credit firm, auto-enrolment is a mandatory employer obligation that must be administered accurately through payroll.",

  "CU-0243": "The Health and Safety at Work etc. Act 1974 imposes a general duty on employers to ensure, so far as is reasonably practicable, the health, safety and welfare at work of all employees. This includes: providing a safe working environment, safe systems of work, adequate information, instruction, training and supervision, and maintaining the workplace in a safe condition. For an office-based consumer credit firm, health and safety obligations include workstation assessments (Display Screen Equipment Regulations), fire safety (Regulatory Reform (Fire Safety) Order 2005), first aid provision, and risk assessments for the workplace. Where employees work from home, the employer retains health and safety duties. The Health and Safety Executive (HSE) enforces workplace safety through inspections, improvement notices, prohibition notices, and criminal prosecution — offences carry unlimited fines and up to two years' imprisonment.",

  "CU-0244": "The Transfer of Undertakings (Protection of Employment) Regulations 2006 (TUPE) protect employees' terms and conditions when a business or undertaking is transferred to a new employer. Under TUPE, employees of the transferor automatically become employees of the transferee on their existing terms, and dismissals connected to the transfer are automatically unfair unless there is an economic, technical or organisational (ETO) reason entailing changes in the workforce. Both transferor and transferee must inform and consult affected employees (or their representatives). For a consumer credit firm, TUPE is relevant to acquisitions, disposals, outsourcing arrangements, and changes of service provider — the firm must understand its obligations whether it is acquiring, disposing of, or outsourcing part of its business.",

  "CU-0245": "The Flexible Working Regulations 2014, as amended by the Employment Relations (Flexible Working) Act 2023, give all employees the statutory right to request flexible working from day one of employment (previously requiring 26 weeks' service). Employees can make two requests in any 12-month period. The employer must deal with each request in a reasonable manner and must decide within two months. The employer can only refuse a request for one of eight prescribed business reasons, and must explain the reason for refusal. For a consumer credit firm, this means having a clear flexible working policy, training managers to handle requests appropriately, and documenting decisions with the prescribed business reason where a request is refused.",

  "CU-0246": "The Maternity and Parental Leave Regulations 1999, Paternity and Adoption Leave Regulations 2002, and Shared Parental Leave Regulations 2014 collectively establish the framework for family leave entitlements. Maternity leave comprises 26 weeks' ordinary maternity leave and 26 weeks' additional maternity leave (52 weeks total). Statutory maternity pay is payable for 39 weeks (90% of average earnings for 6 weeks, then the statutory rate). Paternity leave is two weeks. Shared parental leave allows parents to share up to 50 weeks of leave and 37 weeks of pay. Adoption leave mirrors maternity provisions. For a consumer credit firm, these entitlements require accurate payroll processing, adequate cover arrangements, and clear return-to-work processes.",

  "CU-0247": "The Part-Time Workers (Prevention of Less Favourable Treatment) Regulations 2000 provide that part-time workers must not be treated less favourably than comparable full-time workers in relation to their terms and conditions of employment, unless the different treatment is objectively justified. This covers pay (pro-rated), contractual sick pay, maternity/paternity pay, access to pension schemes, training, career development, holiday entitlement, and selection for redundancy. For a consumer credit firm that employs part-time staff, compliance requires that all employment policies and benefits are reviewed to ensure equitable treatment on a pro-rata or proportionate basis.",

  "CU-0248": "The Agency Workers Regulations 2010 entitle agency workers to the same basic working and employment conditions as directly recruited employees after 12 weeks in the same role with the same hirer. The qualifying conditions include pay, duration of working time, night work, rest periods, rest breaks, and annual leave. From day one, agency workers are entitled to access to the hirer's collective facilities (canteen, transport, childcare) and to be informed of any relevant vacancies. For a consumer credit firm using agency workers, the Regulations require tracking of assignment durations, ensuring qualifying entitlements are provided after 12 weeks, and providing day-one access to collective facilities and vacancy information.",

  "CU-0249": "The Immigration, Asylum and Nationality Act 2006 imposes a duty on employers to verify that all employees have the right to work in the United Kingdom before employment commences. The employer must check and copy prescribed identity documents, conduct the check before the employee starts work, and repeat time-limited checks before expiry. Failure to conduct compliant right-to-work checks exposes the employer to civil penalties (currently up to £60,000 per illegal worker for a first offence, £45,000 for repeated breaches) and potential criminal prosecution (up to five years' imprisonment for knowingly employing an illegal worker). For a consumer credit firm, right-to-work checks must be integrated into the recruitment and onboarding process, with documented evidence of compliance maintained for each employee.",

  "CU-0250": "The Modern Slavery Act 2015 consolidates and strengthens the UK's response to slavery, servitude, forced labour and human trafficking. Section 54 requires commercial organisations with turnover above £36 million to produce an annual slavery and transparency statement setting out the steps taken to ensure slavery and human trafficking are not taking place in the organisation's business or supply chains (or a statement that no such steps have been taken). For a consumer credit firm meeting the turnover threshold, the transparency statement must be approved by the board, published on the company's website, and cover areas including organisational structure, policies, due diligence processes, risk assessment, training, and KPIs. Beyond the reporting obligation, the Act's offences apply regardless of the firm's size — firms must be vigilant about modern slavery risks in their supply chains.",

  "CU-0251": "The ACAS Code of Practice on Disciplinary and Grievance Procedures is a statutory code of practice that sets out the minimum procedural standards for handling disciplinary issues and employee grievances. While not legally binding in itself, employment tribunals are required to take the Code into account in relevant proceedings, and can adjust compensation by up to 25% for unreasonable failure to comply. The Code requires: investigation of the facts, written notification of the allegation, a disciplinary meeting with the right to be accompanied, the decision, and the right of appeal. For a consumer credit firm, following the ACAS Code is essential for managing disciplinary matters and grievances — failure to follow the Code significantly increases the risk and cost of unfair dismissal and other employment tribunal claims.",

  // CORPORATE
  "CU-0252": "UK company law and corporate governance requirements establish the legal framework within which the company operates as a legal entity, including directors' duties, accounts and reporting obligations, share capital rules, and governance standards. For a consumer credit firm structured as a limited company, these obligations run alongside regulatory requirements and create a parallel set of duties — directors owe duties both under company law (to the company and its shareholders) and under FCA regulation (as SMF holders with individual accountability). Understanding the intersection of company law and financial regulation is essential for effective governance.",

  "CU-0253": "The Companies Act 2006 is the primary legislation governing UK companies, covering formation, management, accounts, reporting, shares, capital, and dissolution. Key areas for a consumer credit firm include: directors' general duties (Part 10), preparation and filing of annual accounts and reports (Part 15), the annual confirmation statement (formerly annual return), maintenance of statutory registers (register of members, register of directors, PSC register), and requirements for registered office, company name, and statutory records. Non-compliance with Companies Act filing requirements carries criminal sanctions (fines for late filing, prosecution for failure to file accounts), and can result in directors being personally disqualified. Companies House filing obligations operate on strict deadlines that must be built into the firm's compliance calendar.",

  "CU-0254": "Part 10 of the Companies Act 2006 codifies seven statutory directors' duties: (s.171) duty to act within powers; (s.172) duty to promote the success of the company for the benefit of its members, having regard to long-term consequences, employee interests, business relationships, community and environment, reputation, and fairness between members; (s.173) duty to exercise independent judgment; (s.174) duty to exercise reasonable care, skill and diligence; (s.175) duty to avoid conflicts of interest; (s.176) duty not to accept benefits from third parties; and (s.177) duty to declare interest in proposed transactions. These duties are owed to the company and are enforceable by the company or through derivative claims by shareholders. For directors of a consumer credit firm who also hold SMF positions, these duties operate alongside and complement their regulatory responsibilities.",

  "CU-0255": "Part 15 of the Companies Act 2006 requires companies to prepare and file annual accounts (comprising a balance sheet, profit and loss account, and notes) and a strategic report and directors' report. Small companies may qualify for simplified reporting, but all companies must file accounts with Companies House within specified deadlines (9 months for private companies, 6 months for public companies). The accounts must give a true and fair view of the company's financial position. For a consumer credit firm, the accounts are also relevant to the FCA's assessment of the firm's financial resources and compliance with prudential requirements. Common issues include late filing (which results in automatic penalties), failure to maintain adequate accounting records, and discrepancies between management accounts and statutory accounts.",

  "CU-0256": "Part 21A of the Companies Act 2006 requires companies to maintain a register of Persons with Significant Control (PSC) — individuals or entities that hold more than 25% of shares or voting rights, have the right to appoint or remove a majority of the board, or otherwise exercise significant influence or control. The PSC register must be kept up to date and filed with Companies House. The Economic Crime and Corporate Transparency Act 2023 enhanced PSC requirements, including identity verification for PSCs. For a consumer credit firm, the PSC register must accurately reflect the ownership and control structure, and must be updated within 14 days of any change becoming known.",

  "CU-0257": "The Insolvency Act 1986 establishes the legal framework for corporate insolvency in England and Wales, including the duties of directors when a company is in financial difficulty. Section 214 creates liability for wrongful trading — directors who continued trading when they knew or ought to have concluded that there was no reasonable prospect of avoiding insolvent liquidation may be required to personally contribute to the company's assets. Section 213 addresses fraudulent trading (carrying on business with intent to defraud creditors), carrying more severe penalties including personal liability and criminal prosecution. For directors of a consumer credit firm, awareness of insolvency obligations is essential — the duty to act in the interests of creditors crystallises when the company is or is likely to become unable to pay its debts, and directors must take every step to minimise potential losses to creditors.",

  "CU-0258": "The Economic Crime and Corporate Transparency Act 2023 introduces a landmark corporate offence of failure to prevent fraud (section 199), applying to large organisations whose employees, agents, subsidiaries or associated persons commit fraud offences intending to benefit the organisation. The only defence is having 'reasonable fraud prevention procedures' in place. The Act also reforms Companies House, introducing identity verification for directors, PSCs and those filing documents, and giving Companies House new powers to query and refuse filings. Enhanced AML information-sharing provisions enable regulated sector firms to share information for financial crime prevention. For a consumer credit firm of sufficient size, the failure to prevent fraud offence requires implementing documented fraud prevention procedures analogous to the Bribery Act's 'adequate procedures' framework — including risk assessment, proportionate controls, top-level commitment, due diligence, training, and monitoring.",

  // TAX
  "CU-0259": "UK tax obligations create a framework of corporate and employer duties that interact with and complement financial services regulation. For a consumer credit firm, tax compliance encompasses corporation tax on profits, VAT (with particular attention to financial services exemptions and partial exemption), PAYE and NIC on employee remuneration, and compliance with Making Tax Digital requirements for digital record-keeping and reporting. Tax non-compliance can result in financial penalties, interest charges, criminal prosecution, and reputational damage — HMRC has extensive investigation and enforcement powers including criminal prosecution authority.",

  "CU-0260": "The Corporation Tax Acts 2009 and 2010 establish the framework for corporation tax on UK company profits. Companies must compute taxable profits, submit a company tax return (CT600) within 12 months of the end of the accounting period, and pay corporation tax within nine months and one day of the period end (with quarterly instalment payments for large companies). The current main rate is 25% for profits over £250,000. For a consumer credit firm, specific corporation tax considerations include the treatment of loan loss provisions, the deductibility of regulatory fines and levies, transfer pricing for intra-group transactions, and the interaction between accounting standards and tax computation. HMRC can enquire into returns within 12 months of filing, and deliberate non-compliance carries penalties of up to 100% of the tax underpaid.",

  "CU-0261": "The Value Added Tax Act 1994 establishes the VAT framework in the UK. Financial services are generally exempt from VAT under Group 5 of Schedule 9 — this includes the provision of credit and related services. However, VAT exemption means the firm cannot recover input VAT on costs related to exempt supplies, creating a partial exemption calculation where the firm also makes taxable supplies. For a consumer credit firm, the key VAT considerations are: ensuring correct categorisation of supplies as exempt (credit) or taxable (advisory, technology), managing partial exemption recovery calculations, and complying with VAT registration and reporting obligations including Making Tax Digital. Incorrect VAT treatment of mixed supplies and failure to manage partial exemption properly are common compliance issues.",

  "CU-0262": "The Income Tax (PAYE) Regulations 2003 and associated legislation establish the employer's obligation to operate PAYE (Pay As You Earn), deducting income tax and National Insurance Contributions from employee earnings and remitting them to HMRC. Employers must report payroll information to HMRC in real time through RTI (Real Time Information) submissions, maintain accurate payroll records, issue P60 certificates to employees, and report benefits in kind on P11D forms. For a consumer credit firm, PAYE compliance is a core employer obligation — errors can result in penalties, interest charges, and HMRC compliance investigations. Specific areas of attention include correct treatment of bonuses and commissions, salary sacrifice arrangements, and benefits in kind including company vehicles and private medical insurance.",

  "CU-0263": "Making Tax Digital (MTD) is HMRC's programme to digitise the UK tax system, requiring businesses to maintain digital records and submit returns through compatible software. MTD for VAT has been mandatory since April 2022 for all VAT-registered businesses. MTD for Income Tax Self Assessment is being phased in from April 2026. While MTD for Corporation Tax has not yet been mandated, HMRC has signalled its intention to extend digital requirements to all business taxes. For a consumer credit firm, MTD compliance requires compatible accounting software, digital record-keeping practices, and processes for digital submission of VAT returns. The firm should monitor HMRC's MTD roadmap and prepare for future requirements.",

  // FCA-GUIDANCE
  "CU-0264": "FCA guidance, policy statements and supervisory expectations shape the practical application of Handbook rules, providing the FCA's interpretation of how rules should be applied and setting out supervisory priorities. While not binding in the same way as Handbook rules, guidance creates legitimate expectations — a firm that does not follow relevant guidance must be able to justify its alternative approach. Policy statements explain the rationale behind final rules. Supervisory expectations (communicated through Dear CEO letters, portfolio letters, and thematic reviews) signal the FCA's areas of focus and inform the supervisory approach. For a consumer credit firm, staying current with FCA guidance is essential for understanding evolving regulatory expectations and preparing for supervisory engagement.",

  "CU-0265": "FG22/5 is the FCA's comprehensive finalised guidance on implementing the Consumer Duty, providing detailed practical guidance on how firms should interpret and apply Principle 12, the cross-cutting rules, and the four outcomes. The guidance covers: scope and application, the standard of care expected, the cross-cutting rules in practice, each of the four outcomes with examples of good and poor practice, governance and oversight requirements, vulnerable customers, and the relationship between the Duty and existing requirements. For a consumer credit firm, FG22/5 is the primary reference document for Consumer Duty implementation — it provides the FCA's own interpretation of what 'good outcomes' means in practice and should inform every aspect of the firm's Duty framework.",

  "CU-0266": "PS22/9 is the FCA's policy statement setting out the final Consumer Duty rules, explaining the FCA's approach and the changes made following consultation. The document provides the FCA's reasoning for the final rules, addresses stakeholder feedback, and clarifies how the Duty interacts with existing regulatory requirements. PS22/9 is essential reading for understanding the FCA's policy intent — it explains not just what the rules require but why specific approaches were adopted, which informs how the FCA will assess compliance. For a consumer credit firm, PS22/9 provides the authoritative explanation of the Consumer Duty's design and the FCA's expectations for implementation.",

  "CU-0267": "FG21/1 is the FCA's detailed guidance on identifying, understanding and responding to customer vulnerability. The guidance establishes the FCA's definition of a vulnerable customer (someone who, due to their personal circumstances, is especially susceptible to harm, particularly when a firm is not acting with appropriate levels of care) and identifies four key drivers of vulnerability: health, life events, resilience, and capability. The guidance requires firms to: understand the nature and scale of vulnerability in their customer base; ensure staff have appropriate skills and capability; design products and services that meet the needs of vulnerable customers; provide flexible and responsive customer service; and monitor and evaluate outcomes for vulnerable customers. For a consumer credit firm, FG21/1 is central to the Consumer Duty's cross-cutting rule on avoiding foreseeable harm and the Consumer Support outcome.",

  "CU-0268": "GC23/2 provides the FCA's guidance on financial promotions on social media, reflecting the increasing importance of social media as a marketing channel for financial services. The guidance addresses: the application of financial promotion rules to social media content (including character-limited formats); the requirement for promotions to be clear, fair and not misleading even in short-form content; the inclusion of risk warnings and required disclosures; influencer marketing and the responsibilities of the authorised firm approving the promotion; the need for firms to monitor and control social media content; and the FCA's expectations around prominence of key information. For a consumer credit firm using social media for marketing, GC23/2 provides essential guidance on ensuring compliance across platforms including Instagram, TikTok, Twitter/X, Facebook and LinkedIn.",

  "CU-0269": "FG15/04 provides the FCA's original guidance on social media and customer communications, establishing the principle that the same regulatory requirements apply regardless of the communication channel. The guidance covers: how to apply the 'clear, fair and not misleading' standard to social media; the treatment of character-limited posts; the use of links to additional information; image-based communications; and the firm's responsibility for content posted by third parties on its behalf. While superseded in some areas by GC23/2, FG15/04 remains relevant for its broader guidance on digital customer communications. For a consumer credit firm, FG15/04 provides foundational principles for all digital communication, not just social media marketing.",

  "CU-0270": "PS21/3 is the FCA's policy statement on building operational resilience, establishing requirements for firms to identify their important business services, set impact tolerances, map resources and dependencies, and conduct scenario testing. The policy statement explains the FCA's approach, the relationship between operational resilience and business continuity, and the supervisory expectations for compliance. For a consumer credit firm, PS21/3 provides the authoritative statement of the FCA's operational resilience expectations and the timeline for compliance milestones. The firm should use PS21/3 as the basis for its operational resilience programme, ensuring that all important business services have been identified, tolerances set, resources mapped, and testing conducted.",

  "CU-0271": "FG17/9 provides the FCA's guidance on assessing creditworthiness in consumer credit, supplementing the CONC 5 rules with practical interpretation of how firms should conduct affordability and credit risk assessments. The guidance addresses: what 'reasonable and proportionate' assessment means in practice; the types of information firms should obtain and verify; the role of credit reference agency data; how to assess income and expenditure; the treatment of different types of credit products; and the FCA's expectations for record-keeping and evidencing the assessment. For a consumer credit firm, FG17/9 is the primary interpretive guidance for CONC 5 compliance and should inform the design of the firm's creditworthiness assessment methodology, policies and procedures.",

  "CU-0272": "FCA supervisory expectations for debt collection and forbearance are communicated through Dear CEO letters, portfolio letters, and thematic review findings. These communications set out the FCA's current areas of concern and supervisory focus, and while not binding rules, they create strong expectations that firms will address the issues raised. Key themes include: the quality and consistency of forbearance offered to customers in financial difficulty; the adequacy of collections strategies and MI; the identification and treatment of vulnerable customers in collections; and the firm's use of data to monitor and improve customer outcomes. For a consumer credit firm, staying current with these communications is essential for anticipating supervisory priorities and ensuring the collections function meets FCA expectations.",

  "CU-0273": "PS24/16 sets out the FCA's expectations on diversity and inclusion in financial services, reflecting the FCA's view that diverse and inclusive firms make better decisions and deliver better outcomes for customers. While the FCA's formal D&I proposals are still evolving, the policy statement signals expectations around: board and senior management diversity; data collection on workforce characteristics; inclusive workplace cultures; and the link between internal culture and customer outcomes. For a consumer credit firm, D&I considerations inform both employment practices and the Consumer Duty — the FCA increasingly views inclusive product design, accessible communications, and diverse governance as indicators of a firm that delivers good customer outcomes.",

  "CU-0274": "The FCA's ESG and climate-related expectations are evolving, with increasing supervisory focus on how financial services firms identify, assess and manage climate-related financial risks and opportunities. The FCA's expectations draw on the Task Force on Climate-related Financial Disclosures (TCFD) framework. While mandatory climate reporting requirements currently apply primarily to larger firms and listed entities, the FCA has signalled that climate risk management is expected of all firms proportionate to their size and activities. For a consumer credit firm, the relevance depends on the firm's size and activities — the firm should monitor FCA consultations on climate risk management and prepare for potential future requirements while considering climate risk in its broader risk management framework.",

  "CU-0275": "PS23/6 sets out the FCA's rules for financial promotions relating to cryptoassets, extending the financial promotion regime to qualifying cryptoassets. The rules require that cryptoasset promotions are fair, clear and not misleading, include specific risk warnings, and are approved by an FCA-authorised firm. While not directly applicable to a consumer credit firm that does not deal in cryptoassets, awareness of the regulatory perimeter is important — if the firm's business model evolves to include any cryptoasset-related features (such as accepting cryptocurrency payments or offering crypto-backed credit), the PS23/6 requirements would become relevant.",

  "CU-0276": "The FCA's AI and machine learning expectations, set out primarily in DP5/22 (later developed through further publications), establish the regulatory framework for the use of AI/ML in financial services. The FCA focuses on four key themes: explainability (firms should be able to explain AI-driven decisions to customers and the regulator), fairness (AI systems must not produce discriminatory outcomes), accountability (clear human oversight and responsibility for AI decisions), and transparency (appropriate disclosure of AI usage). For a consumer credit firm using automated credit decisioning, these expectations are directly relevant — the firm must ensure its AI/ML models are explainable, regularly tested for bias, subject to human oversight, and that customers are informed about automated decision-making in accordance with UK GDPR Article 22.",

  "CU-0277": "The FCA's cost of living expectations, communicated through Dear CEO letters and supervisory communications, require firms to proactively support customers through periods of financial pressure. The FCA expects firms to: identify customers who may be struggling, including through proactive use of data and MI; ensure forbearance is offered proactively and not just reactively; review product and service design to ensure fair value is maintained during cost pressures; provide tailored communications and support for customers in difficulty; and ensure vulnerable customers receive additional care. For a consumer credit firm specialising in debt consolidation, these expectations are particularly relevant — the firm's customers may be disproportionately affected by cost of living pressures, and the FCA expects proactive, not just reactive, support.",

  "CU-0278": "The FCA's Consumer Credit Portfolio Strategy Letter sets out the FCA's supervisory strategy and priorities for the consumer credit sector, identifying the key risks and harms that the FCA will focus on in its supervision of consumer credit firms. The letter typically addresses: the FCA's assessment of the main risks in the consumer credit sector; specific areas of supervisory focus (such as affordability assessment quality, collections practices, and Consumer Duty implementation); data and MI expectations; and the FCA's approach to supervision for the period. For a consumer credit firm, the portfolio strategy letter is essential reading — it defines what the FCA is looking for in supervisory engagements and informs the firm's compliance monitoring priorities and board reporting.",

  // ICO
  "CU-0279": "ICO guidance and codes of practice provide authoritative interpretation of data protection law, shaping enforcement expectations and establishing practical compliance standards. ICO guidance has particular authority because the ICO is both the regulator and the primary source of interpretive guidance — departure from ICO guidance in enforcement proceedings requires strong justification. For a consumer credit firm processing significant volumes of personal and financial data, ICO guidance is essential for operationalising data protection obligations, from lawful basis selection through to breach response and rights request handling.",

  "CU-0280": "The ICO's Direct Marketing Guidance provides comprehensive guidance on data protection requirements for direct marketing, covering consent-based marketing, legitimate interests marketing, the 'soft opt-in' exception under PECR, opt-out mechanisms, suppression lists, and the interaction between UK GDPR and PECR. The guidance addresses all marketing channels: email, SMS, phone (live and automated), post, and online advertising. For a consumer credit firm, the guidance is essential for ensuring all marketing activities comply with data protection requirements — including the requirement for valid consent where applicable, proper maintenance of suppression lists, and the conditions for relying on the soft opt-in for existing customer marketing.",

  "CU-0281": "The ICO's DPIA Guidance explains when and how to conduct Data Protection Impact Assessments, which are mandatory before any processing likely to result in a high risk to individuals. The guidance covers: screening criteria for when a DPIA is required; the systematic description of processing operations; assessment of necessity and proportionality; risk identification and assessment; identification of mitigation measures; and documentation requirements. For a consumer credit firm, DPIAs are mandatory for automated credit decisioning, Open Banking data processing, CRA data processing at scale, and any significant new system or product involving personal data. The guidance provides practical templates and examples that should be adapted for the firm's specific processing activities.",

  "CU-0282": "The ICO's Data Sharing Code of Practice is a statutory code (produced under section 121 of the DPA 2018) providing practical guidance on sharing personal data with other organisations. The code covers: deciding whether to share data; the legal framework for sharing; establishing data sharing agreements; governance and accountability for shared data; security measures; individual rights; and record-keeping. For a consumer credit firm that shares data with CRAs, funders, third-party service providers, debt collectors, and regulatory bodies, the Data Sharing Code provides essential guidance on ensuring each sharing arrangement has a lawful basis, appropriate safeguards, and adequate documentation.",

  "CU-0283": "The ICO's Employment Practices Data Protection Code provides guidance on processing employee personal data, covering recruitment, employment records, monitoring at work, and information about workers' health. The guidance addresses: fairness in recruitment data collection; retention of recruitment records; processing of employee health data; monitoring of emails, internet usage, and phone calls; CCTV in the workplace; drug and alcohol testing; and workers' rights to access their employment records. For a consumer credit firm, the guidance informs HR data processing practices — particularly around monitoring of staff communications (relevant to compliance monitoring), health data processing (relevant to occupational health and disability adjustments), and the boundaries of acceptable workplace surveillance.",

  "CU-0284": "The ICO's Guidance on AI and Data Protection addresses the intersection of artificial intelligence, machine learning and data protection law, providing practical guidance for organisations that develop or deploy AI systems that process personal data. The guidance covers: lawfulness (identifying appropriate lawful bases for AI training and deployment), fairness (addressing bias and discrimination in AI systems), transparency (explaining AI decisions to data subjects), accountability (documenting AI governance), and individual rights (handling rights requests in the context of AI). For a consumer credit firm using AI/ML for credit scoring and automated decisioning, the guidance is directly applicable and should be read alongside the FCA's own AI/ML expectations.",

  "CU-0285": "The ICO's Personal Data Breach Reporting Guidance explains when and how to report personal data breaches to the ICO and affected individuals. The guidance covers: what constitutes a personal data breach; the 72-hour notification requirement; how to assess whether a breach is 'likely to result in a risk to individuals'; the content of breach notifications; when to notify affected individuals; and how to document all breaches (including those not notified to the ICO). For a consumer credit firm handling sensitive financial data, breach response procedures must be robust — a breach involving customer financial data or credit information could enable identity fraud and would typically require both ICO and individual notification. The firm should maintain pre-prepared breach notification templates and conduct regular breach response exercises.",

  "CU-0286": "The ICO's Age Appropriate Design Code (Children's Code) establishes standards for online services likely to be accessed by children (under 18). The Code applies to information society services (online services) that process personal data and are likely to be accessed by children. The 15 standards include: best interests of the child, age-appropriate application, transparency, data minimisation, sharing controls, geolocation, parental controls, profiling, nudge techniques, connected toys and devices, and online tools. For a consumer credit firm, the Code's applicability depends on whether the firm's online services might be accessed by under-18s — while credit products are restricted to adults, the firm's website and app may be accessible to minors, potentially triggering Code obligations for data processing during browsing and eligibility checking.",

  "CU-0287": "The ICO's Legitimate Interests Assessment (LIA) Guidance provides detailed practical guidance on conducting and documenting the three-part LIA test required for any processing relying on legitimate interests as a lawful basis under Article 6(1)(f). The three parts are: (1) Purpose test — is the interest legitimate and is there a genuine need for the processing? (2) Necessity test — is the processing necessary for that purpose, or could the purpose be achieved in a less intrusive way? (3) Balancing test — do the individual's interests, rights and freedoms override the legitimate interest? The guidance provides worked examples and a template for documentation. For a consumer credit firm, LIAs are commonly required for: fraud prevention, direct marketing (where not relying on consent), network and information security, business analytics, and certain data sharing arrangements.",

  "CU-0288": "The ICO's Consent Guidance provides detailed guidance on obtaining, recording and managing valid consent under the UK GDPR. Valid consent must be: freely given (genuine choice, no detriment for refusing), specific (separate consent for different purposes), informed (told the controller's identity, the processing purpose, and the right to withdraw), and unambiguous (clear affirmative action). The guidance covers: consent and children (parental consent for under-13s for online services), granular consent, bundled consent (generally not valid), consent records, refreshing consent, and withdrawal mechanisms. For a consumer credit firm, consent is the primary lawful basis for marketing communications, cookies, and optional profiling — the firm must be able to demonstrate valid consent through timestamps, specific wording shown, and records of the information provided at the point of consent.",

  "CU-0289": "The ICO's Automated Decision-Making and Profiling Guidance explains the requirements of Article 22 of the UK GDPR, which gives individuals the right not to be subject to decisions based solely on automated processing that produce legal or similarly significant effects. The guidance covers: what constitutes 'solely automated' processing; what are 'legal or similarly significant effects'; the three exceptions (contract necessity, authorised by law, explicit consent); the safeguards required when relying on an exception (meaningful information about the logic, right to human intervention, ability to contest the decision); and the requirement for DPIAs. For a consumer credit firm with automated credit decisioning, this guidance is directly and critically relevant — the firm must either ensure meaningful human involvement in credit decisions or rely on an exception with full safeguards implemented.",

  "CU-0290": "The ICO's Right to Erasure Guidance explains when and how to handle erasure requests, including the circumstances in which the right applies and the exemptions that may permit refusal. The right applies where: data is no longer necessary, consent has been withdrawn, legitimate interests objection is upheld, processing was unlawful, or there is a legal obligation to erase. Exemptions include processing necessary for: legal obligation compliance, legal claims establishment or defence, and public interest. For a consumer credit firm, right to erasure requests are common and operationally challenging — the firm must balance the right against CCA record-keeping requirements, FCA data retention obligations, and the need to maintain records for legal claims. The firm should maintain a clear erasure process, identify all systems holding data, and document refusals with specific legal justification.",

  "CU-0291": "The ICO's Accountability Framework is a self-assessment tool covering ten areas of data protection governance: leadership and oversight; policies and procedures; training and awareness; individuals' rights; transparency; records of processing; contracts and data sharing; risks and DPIAs; breach management and response; and international transfers. Each area includes expectations at different maturity levels, enabling organisations to benchmark their compliance and identify areas for improvement. For a consumer credit firm, the Accountability Framework provides a structured approach to demonstrating compliance with the accountability principle (Article 5(2)) — the firm should conduct regular self-assessments against the framework, document findings, and address gaps through a prioritised improvement programme.",

  // INDUSTRY
  "CU-0292": "Industry codes of practice, technical standards and voluntary frameworks supplement formal regulation by establishing best-practice standards developed by industry bodies, standards organisations and trade associations. While adherence is often voluntary, many industry codes are treated as de facto requirements by regulators — the FCA regularly references industry standards in its expectations and enforcement actions, and the FOS considers adherence to relevant codes when assessing whether a firm has acted fairly. For a consumer credit firm, engagement with industry codes demonstrates professionalism and commitment to high standards, and can provide a competitive advantage in customer and partner relationships.",

  "CU-0293": "The Advertising Standards Authority (ASA) enforces the CAP Code (non-broadcast) and BCAP Code (broadcast) through a self-regulatory system backed by statutory and contractual powers. Section 14 of both codes sets specific requirements for financial products advertising, requiring consumer credit advertisements to comply with FSMA financial promotion requirements and CONC Chapter 3 rules. For a consumer credit firm, ASA compliance is an additional regulatory layer beyond FCA requirements — the ASA can require advertisements to be withdrawn, refer persistent offenders to trading standards for statutory enforcement, and impose adverse publicity through published rulings. Firms must ensure all marketing (including social media, influencer marketing, and comparison site listings) complies with both FCA and ASA requirements.",

  "CU-0294": "The CAP Code (UK Code of Non-Broadcast Advertising and Direct & Promotional Marketing) governs all non-broadcast advertising in the UK, including online, print, direct mail, social media, and outdoor advertising. The Code requires advertisements to be legal, decent, honest and truthful, and establishes specific rules for financial products including consumer credit. Key requirements include: promotions must not mislead by omission or exaggeration, must not take advantage of consumers' inexperience or credulity, must include required risk warnings, and must not target inappropriate audiences. For a consumer credit firm, the CAP Code applies to all marketing channels except broadcast — compliance requires integrating CAP requirements into the firm's marketing approval process alongside FCA financial promotion rules.",

  "CU-0295": "The BCAP Code (UK Code of Broadcast Advertising) governs television and radio advertising, requiring that broadcast advertisements are legal, decent, honest and truthful. Financial advertising rules mirror those in the CAP Code, with additional broadcast-specific requirements around presentation and scheduling. For a consumer credit firm that advertises through broadcast media, BCAP compliance requires pre-clearance of advertisements through Clearcast (for TV) or Radiocentre (for radio), ensuring that promotional content meets both FCA and BCAP requirements before broadcast.",

  "CU-0296": "The Ofcom Broadcasting Code sets standards for UK television and radio broadcasters, covering protection of under-eighteens, harm and offence, crime and disorder, religion, impartiality, elections, fairness, privacy, and commercial references. While the Broadcasting Code applies primarily to broadcasters rather than advertisers, it is relevant where a consumer credit firm's advertising content could raise issues under the Code's standards — for example, advertising during programming aimed at younger audiences, or promotional content that could be considered harmful or offensive. Compliance is primarily the broadcaster's responsibility, but the firm should ensure its advertising content does not create Code issues for broadcasting partners.",

  "CU-0297": "The Lending Standards Board (LSB) oversees the Standards of Lending Practice, which set voluntary standards for lending to personal and business customers. The LSB monitors registered firms' compliance through mystery shopping, data analysis, and independent reviews. The Standards of Lending Practice cover the entire lending lifecycle: product information and communication, application and assessment of lending, account management and servicing, and dealing with financial difficulty. For a consumer credit firm, LSB membership and adherence to the Standards of Lending Practice demonstrates commitment to best practice and provides an additional layer of accountability beyond FCA regulation — the firm should assess whether LSB registration would benefit its compliance and reputational position.",

  "CU-0298": "The Standards of Lending Practice for Personal Customers, overseen by the LSB, set out best-practice standards for lending to individual consumers. The Standards cover: providing information to help customers make informed decisions; assessing whether lending is appropriate and affordable; managing accounts and supporting customers throughout the product lifecycle; and treating customers in financial difficulty with forbearance and understanding. While voluntary, the Standards represent the lending industry's agreed minimum standards of good practice and are considered by the FOS and FCA when assessing firm conduct. For a consumer credit firm, the Standards provide a practical benchmark for responsible lending practices that complements regulatory requirements.",

  "CU-0299": "The Finance & Leasing Association (FLA) Lending Code applies to FLA member firms engaged in consumer lending, providing industry-specific best-practice standards. The Code covers responsible lending, advertising, pre-contractual information, assessment, contract documentation, post-contractual conduct, financial difficulty, and complaints handling. FLA membership and Code adherence provide access to industry intelligence, benchmarking data, and representation on regulatory matters. For a consumer credit firm, FLA membership may be relevant depending on the firm's product range and business model — the Code's standards complement FCA regulation and demonstrate industry engagement.",

  "CU-0300": "Information security standards and frameworks provide structured approaches to protecting information assets, including customer data, financial records, and business-critical systems. For a consumer credit firm handling sensitive personal and financial data, robust information security is both a regulatory requirement (SYSC, UK GDPR Article 32) and a business imperative — data breaches can result in ICO enforcement action, FCA supervisory concerns, customer harm, and severe reputational damage. Industry security standards provide the frameworks for implementing proportionate and effective security controls.",

  "CU-0301": "ISO/IEC 27001:2022 is the internationally recognised standard for Information Security Management Systems (ISMS), specifying requirements for establishing, implementing, maintaining and continually improving information security through a risk-based approach. The standard requires: context and stakeholder analysis; risk assessment and treatment; leadership commitment; documented policies and procedures; Annex A controls covering organisational, people, physical and technological security; internal audits; management reviews; and continual improvement. Certification is achieved through independent audit, with surveillance audits annually and recertification every three years. For a consumer credit firm, ISO 27001 certification provides a structured framework for protecting customer data, demonstrates compliance with UK GDPR security requirements, supports FCA expectations around systems and controls, and provides competitive advantage in partnership and procurement relationships.",

  "CU-0302": "Cyber Essentials and Cyber Essentials Plus are UK government-backed certification schemes, developed by the National Cyber Security Centre (NCSC), that set baseline cyber hygiene standards for organisations of all sizes. Cyber Essentials covers five technical controls: firewalls, secure configuration, user access control, malware protection, and security update management. Cyber Essentials Plus includes an independent technical verification (vulnerability scanning and on-site assessment). For a consumer credit firm, Cyber Essentials certification provides a minimum baseline of cyber security that demonstrates commitment to protecting customer data. Many government and corporate clients require Cyber Essentials certification from their suppliers, and the FCA views appropriate cyber security as part of a firm's systems and controls obligations.",

  "CU-0303": "The Payment Card Industry Data Security Standard (PCI DSS) v4.0.1 comprises 12 core requirements for protecting cardholder data, organised into six control objectives: secure network, data protection, vulnerability management, access control, monitoring and testing, and information security policy. Compliance requirements vary by merchant level based on annual transaction volume, ranging from self-assessment questionnaires to full on-site assessments. Non-compliance can result in fines from payment card brands, increased transaction fees, and loss of ability to accept card payments. For a consumer credit firm that processes card payments for loan repayments, fees or direct debit setup, PCI DSS compliance is essential across all systems storing, processing or transmitting cardholder data.",

  "CU-0304": "The NIST Cybersecurity Framework provides a voluntary framework for managing cyber security risk, organised around five core functions: Identify (asset management, risk assessment, governance), Protect (access control, awareness training, data security), Detect (continuous monitoring, detection processes), Respond (response planning, analysis, mitigation, communications), and Recover (recovery planning, improvements, communications). While not a certification standard, the NIST Framework provides a comprehensive taxonomy for discussing and managing cyber security risk and is widely used as a reference framework by regulators and organisations globally. For a consumer credit firm, the NIST Framework can be used alongside ISO 27001 and Cyber Essentials to provide a comprehensive approach to cyber risk management.",

  // OTHER-REGS
  "CU-0305": "Beyond the FCA, multiple regulatory bodies exercise jurisdiction over aspects of a consumer credit firm's operations, including the Financial Ombudsman Service (consumer disputes), Competition and Markets Authority (competition law), The Pensions Regulator (auto-enrolment), Health and Safety Executive (workplace safety), Companies House (company filings), HMRC (tax compliance), and the National Crime Agency (financial crime intelligence). For a comprehensive compliance framework, the firm must identify all relevant regulatory relationships, understand the obligations and expectations of each body, and maintain appropriate engagement and reporting across the regulatory landscape.",

  "CU-0306": "The Financial Ombudsman Service handles complaints referred by consumers after the firm's internal process has been exhausted (or after eight weeks). FOS decisions are determined by reference to what is fair and reasonable in all circumstances — a broader standard than strict legal liability. Awards can be made up to £430,000. All FCA-authorised firms are within the FOS compulsory jurisdiction. For a consumer credit firm, FOS engagement is a routine operational reality — common complaint areas include unaffordable lending, inadequate forbearance, unfair charges, and poor arrears handling. FOS decisions and feedback provide valuable insight into regulatory expectations and should be tracked as a key risk indicator, with systemic issues addressed through root cause analysis.",

  "CU-0307": "The Competition and Markets Authority (CMA) enforces UK and EU competition law (the Competition Act 1998 and the Enterprise Act 2002) and consumer protection law (including the Consumer Rights Act 2015 and Consumer Protection from Unfair Trading Regulations 2008). The FCA has concurrent competition law enforcement powers for financial services. For a consumer credit firm, competition law compliance means avoiding: anti-competitive agreements (price-fixing, market-sharing, bid-rigging), abuse of dominant position, and information exchange that could facilitate coordination with competitors. The CMA can impose fines of up to 10% of global group turnover for competition law breaches, and individuals can face criminal prosecution for cartel offences.",

  "CU-0308": "The Pensions Regulator (TPR) regulates workplace pensions, including enforcement of auto-enrolment duties. TPR monitors compliance through data matching with HMRC and can impose escalating penalties for non-compliance: fixed penalty notices (£400), escalating penalty notices (daily penalties of £50 to £10,000 depending on the number of employees), and prohibited recruitment conduct penalties. For a consumer credit firm, TPR compliance requires accurate auto-enrolment administration, timely re-enrolment of opted-out workers, and submission of re-declarations of compliance every three years. The firm should ensure payroll processes are configured to correctly identify eligible jobholders and apply the correct contribution rates.",

  "CU-0309": "The Health and Safety Executive (HSE) enforces workplace health and safety legislation, conducting inspections, issuing improvement and prohibition notices, and prosecuting serious breaches. For an office-based consumer credit firm, key HSE obligations include: workplace risk assessments, fire safety, display screen equipment assessments, first aid provision, and reporting of injuries and dangerous occurrences (RIDDOR). Where employees work from home, the employer retains certain health and safety duties. Non-compliance can result in unlimited fines and up to two years' imprisonment for the most serious offences. The firm should maintain documented risk assessments, ensure adequate H&S training for all staff, and have procedures for reporting and investigating workplace incidents.",

  "CU-0310": "Companies House is the UK registrar of companies, responsible for maintaining the public register and receiving statutory filings. Key filing obligations include: annual confirmation statement (within 14 days of the review period end), annual accounts (within 9 months of financial year end for private companies), notification of changes to directors, registered office, share capital, and PSC register (within 14 days of the change). The Economic Crime and Corporate Transparency Act 2023 introduced identity verification requirements for directors and PSCs. Late filing of accounts results in automatic penalties (£150 to £1,500 depending on delay), and failure to file can result in criminal prosecution of directors and striking off of the company.",

  "CU-0311": "HMRC is the UK's tax authority, responsible for the collection and administration of direct and indirect taxes including corporation tax, VAT, income tax (PAYE), National Insurance Contributions, and stamp duties. HMRC has extensive investigation and enforcement powers including: compliance checks and enquiries; discovery assessments; civil penalties for errors and late filing/payment; criminal prosecution for tax evasion; and information-gathering powers under Schedule 36 of the Finance Act 2008. For a consumer credit firm, HMRC compliance encompasses corporation tax returns, VAT returns, PAYE/NIC administration, and any applicable stamp duty obligations — all subject to strict filing deadlines and payment dates.",

  "CU-0312": "The National Crime Agency (NCA) is the UK's lead agency for tackling serious and organised crime, including money laundering, terrorist financing, and fraud. The NCA receives and analyses Suspicious Activity Reports (SARs) submitted under POCA and the Terrorism Act, and can issue Defence Against Money Laundering (DAML) consent decisions in response to requests from firms. The NCA's UK Financial Intelligence Unit processes SARs and shares intelligence with law enforcement and regulatory partners. For a consumer credit firm, the NCA relationship is operational — the MLRO must submit SARs electronically through the NCA's SAR Online system, must seek DAML consent before proceeding with transactions where suspicion has been identified, and must maintain records of all SARs and consent decisions.",

  // OP-RES
  "CU-0313": "Operational resilience and outsourcing requirements form a critical component of the FCA's supervisory framework, reflecting the increasing dependence of financial services firms on technology and third-party providers. The FCA expects firms to: identify their important business services; set impact tolerances; understand and manage the dependencies and vulnerabilities in their operations; and ensure they can continue to deliver important services during disruptions. For a consumer credit firm reliant on cloud technology, open banking APIs, CRA services, and payment infrastructure, operational resilience is not merely a compliance obligation but a strategic imperative — disruption to any of these services could directly harm customers and the firm's viability.",

  "CU-0314": "SYSC 3.2 sets out the FCA's requirements for firms that outsource material functions, requiring: thorough pre-outsourcing due diligence; written outsourcing agreements containing prescribed provisions (including service level descriptions, data protection, audit rights, business continuity, and exit strategies); ongoing performance monitoring; adequate business continuity arrangements covering the outsourced function; and maintenance of the firm's ability to manage and supervise the outsourced activity. The firm retains full regulatory responsibility for outsourced activities — outsourcing does not transfer regulatory obligations. For a consumer credit firm, this applies to all material outsourcing arrangements including technology providers, payment processors, customer service functions, debt collection, and IT support.",

  "CU-0315": "SYSC 8 provides additional outsourcing requirements that apply to certain firms based on their regulatory classification. The chapter establishes conditions for outsourcing 'critical or important' operational functions, including: requirements that outsourcing does not materially impair the quality of internal control or the FCA's ability to supervise; the firm must maintain the expertise necessary to supervise the outsourced functions; the firm must take appropriate action if the service provider does not carry out the functions effectively; and the firm must have access to data about the outsourced activities and the service provider's business premises. For a consumer credit firm, SYSC 8 applicability should be assessed based on the firm's specific permission profile and the materiality of its outsourcing arrangements.",

  "CU-0316": "The FCA's Operational Resilience Requirements (implementing PS21/3 through SYSC 15A) require firms to: identify important business services — services that, if disrupted, could cause intolerable harm to consumers, market integrity, or the firm's safety and soundness; set impact tolerances — the maximum tolerable level of disruption, measured by time and other relevant metrics; map resources — identify and document the people, processes, technology, facilities, information and third-party dependencies supporting each important business service; and conduct scenario testing — test the firm's ability to remain within impact tolerances during severe but plausible scenarios. For a consumer credit firm, important business services likely include lending, customer account servicing, payment processing, collections, and complaints handling.",

  "CU-0317": "The UK's approach to digital operational resilience is shaped by the FCA/PRA's Critical Third Parties (CTP) regime (PS24/16), which gives regulators direct oversight of technology providers designated as critical to the UK financial sector. While the EU's Digital Operational Resilience Act (DORA) does not directly apply to UK firms post-Brexit, it serves as a comparative benchmark and is relevant to firms with EU operations or that provide services to EU financial entities. The CTP regime enables regulators to set minimum resilience standards for critical third parties, conduct direct testing, and take enforcement action where standards are not met. For a consumer credit firm, understanding the evolving digital resilience landscape is important for third-party contract negotiations, risk management, and anticipating future regulatory requirements.",

  // MISC-LEG
  "CU-0318": "Additional applicable legislation encompasses UK statutes that, while not specific to financial services, create obligations that affect a consumer credit firm's operations. These range from intellectual property protection and limitation periods for legal claims to human rights protections, whistleblower legislation, debt respite schemes, online safety requirements, and corporate fraud prevention duties. A comprehensive compliance framework must identify and address all applicable legislation, not just sector-specific regulation — failure to comply with 'general' legislation can result in civil liability, criminal prosecution, and reputational damage that undermines the firm's regulatory standing.",

  "CU-0319": "The Copyright, Designs and Patents Act 1988 (CDPA) is the UK's primary intellectual property statute for copyright protection. Copyright automatically subsists in original literary, dramatic, musical and artistic works, sound recordings, films, broadcasts, and typographical arrangements of published editions — no registration is required. For a consumer credit firm, the CDPA is relevant to: marketing content (website copy, blog posts, social media content, advertisements), software and technology (code, databases, user interfaces), and the use of third-party content (stock images, licensed materials, user-generated content). The firm must ensure it has appropriate rights or licences for all content it uses, and should protect its own original content through copyright notices and contractual provisions.",

  "CU-0320": "The Limitation Act 1980 prescribes time limits for legal proceedings in England and Wales. Key limitation periods for a consumer credit firm include: six years for simple contract claims including unsecured credit agreements (s.5); six years for tort claims (s.2); twelve years for claims on specialty including deeds and secured mortgage debts (s.8); and six years for statutory claims (s.9). Time runs from the date the cause of action accrued (typically breach or default). The limitation period can be reset by written acknowledgement signed by the debtor (s.29) or part payment. Once expired, the debt becomes 'statute-barred' — unenforceable through the courts although the debt itself is not extinguished. For a consumer credit firm's collections function, understanding limitation periods is essential for managing the recoveries lifecycle and responding to customer queries about statute-barred debts.",

  "CU-0321": "The Human Rights Act 1998 incorporates the European Convention on Human Rights (ECHR) into UK domestic law, requiring public authorities to act compatibly with Convention rights. While private companies are not directly bound by the Act, it influences the interpretation of other legislation and can apply indirectly where a private firm exercises functions of a public nature. The most relevant Convention rights for a consumer credit firm are: Article 8 (right to respect for private and family life — relevant to data protection, customer communications, and debt collection practices) and Article 14 (prohibition of discrimination — relevant to lending decisions and customer treatment). Courts and tribunals must interpret legislation compatibly with Convention rights, which can influence the outcome of claims involving consumer credit firms.",

  "CU-0322": "The Public Interest Disclosure Act 1998 (PIDA) amended the Employment Rights Act 1996 to provide statutory protection for workers who make qualifying disclosures about wrongdoing in the workplace. PIDA protects workers from dismissal or detriment for raising concerns about criminal offences, regulatory breaches, miscarriages of justice, health and safety dangers, environmental damage, and deliberate concealment of any of these. PIDA works alongside SYSC 18 (FCA whistleblowing requirements) to create a comprehensive framework for internal and external reporting of misconduct. For a consumer credit firm, PIDA compliance requires ensuring that internal whistleblowing channels are effective, that workers understand how to make protected disclosures, and that the firm does not subject whistleblowers to any detriment.",

  "CU-0323": "The Debt Respite Scheme (Breathing Space Moratorium and Mental Health Crisis Moratorium) (England and Wales) Regulations 2021 establish two types of breathing space: standard breathing space (60 days, accessed through a debt advice provider) and mental health crisis breathing space (lasting for the duration of crisis treatment plus 30 days). During a breathing space, creditors must: freeze enforcement action, not apply interest or charges to breathing space debts, not contact the customer to demand payment, and take positive steps to update systems and communicate with the Insolvency Service within prescribed timescales. For a consumer credit firm, breathing space compliance requires automated system capabilities to identify and freeze breathing space accounts, trained staff who understand the restrictions, and monitoring processes to ensure compliance throughout the breathing space period.",

  "CU-0324": "The Online Safety Act 2023 establishes a new regulatory framework for online services, administered by Ofcom, addressing illegal content, children's safety, and fraudulent advertising. The Act imposes duties on providers of user-to-user services and search services to take steps to minimise the risk of illegal content, protect children, and prevent paid-for fraudulent advertising appearing on their platforms. For a consumer credit firm, the Act's relevance depends on the nature of its online presence — if the firm operates any platform features that could constitute a user-to-user service (such as customer forums or review sections), it may have obligations under the Act. The duty to prevent fraudulent advertising is also relevant to the firm's advertising supply chain.",

  "CU-0325": "The Economic Crime and Corporate Transparency Act 2023 introduces the corporate offence of failure to prevent fraud (section 199), applying to large organisations when an employee, agent, subsidiary or associated person commits a fraud offence intending to benefit the organisation. The only defence is demonstrating 'reasonable fraud prevention procedures' in place at the time. The Home Office has published guidance identifying principles for reasonable procedures: top-level commitment, risk assessment, proportionate procedures, due diligence, communication and training, and monitoring and review. For a consumer credit firm of sufficient size, this requires implementing a comprehensive fraud prevention programme covering internal and external fraud risks, with documented procedures, staff training, third-party due diligence, and ongoing monitoring.",

  // PAYMENTS
  "CU-0326": "Payment services regulation governs the provision of payment services in the UK, establishing authorisation requirements, conduct of business standards, consumer protection rights, and security requirements for payment transactions. While the Payment Services Regulations 2017 apply primarily to payment service providers (payment institutions, electronic money institutions, and banks providing payment services), they are relevant to any firm that facilitates payment transactions as part of its regulated activities. For a consumer credit firm, understanding payment services regulation is important for assessing whether loan disbursement, repayment collection, or other payment-related activities trigger PSR obligations, and for ensuring compliance with strong customer authentication requirements.",

  "CU-0327": "The Payment Services Regulations 2017 implement the EU's second Payment Services Directive (PSD2) into UK law, establishing the comprehensive legal framework for payment services. The Regulations cover: authorisation and registration requirements; conduct of business including information disclosure and execution of payment transactions; consumer protection rights including refund rights for unauthorised transactions (full refund within one business day); strong customer authentication (SCA) requirements; and the open banking framework requiring account servicing payment service providers to provide access to authorised third-party providers. For a consumer credit firm, the PSR 2017 is relevant to: payment collection mechanisms (direct debit, standing order, card payment), SCA requirements for customer authentication, open banking data access for affordability assessment, and the consumer protection framework that applies when processing customer payments.",
};
