/**
 * Enriched descriptions for SYSC (CU-0079 to CU-0097), FCA-OTHER (CU-0098 to CU-0117),
 * FS-LEG (CU-0118 to CU-0137), and CONSUMER-LEG (CU-0138 to CU-0144)
 */
export const SYSC_LEG_DESCRIPTIONS: Record<string, string> = {
  "CU-0079": "SYSC is the FCA's Senior Management Arrangements, Systems and Controls sourcebook, establishing the governance framework that every authorised firm must maintain. It encompasses requirements for organisational structure, internal controls, risk management, compliance monitoring, internal audit, record-keeping, conflicts of interest management, operational resilience, whistleblowing, regulatory references, and — critically — the Senior Managers and Certification Regime (SM&CR). SYSC is the regulatory expression of the principle that good governance is a prerequisite for fair customer outcomes, and its requirements inform the FCA's assessment of whether a firm meets its threshold conditions for authorisation. For a consumer credit firm, SYSC compliance means maintaining robust governance arrangements proportionate to the nature, scale and complexity of the business, with clear accountability, effective oversight, and comprehensive management information.",

  "CU-0080": "SYSC 3 establishes the fundamental requirement for firms to maintain robust governance arrangements, effective processes to manage risks, and adequate internal controls. The firm must have clear decision-making procedures, appropriate internal reporting lines, established internal control mechanisms, and arrangements that ensure compliance with regulatory requirements. SYSC 3 requires the governing body to define, approve and oversee the firm's governance arrangements, risk strategy, and internal controls framework. For a consumer credit firm, this means documented policies and procedures for all material business activities, regular board-level review of risk management effectiveness, compliance monitoring programmes, and management information that provides the governing body with an accurate picture of the firm's risk profile and control environment.",

  "CU-0081": "SYSC 4 sets out the organisational requirements that firms must meet, including clear and well-documented business organisation, defined reporting structures, and appropriate allocation of responsibilities. The firm must have adequate arrangements for the orderly and efficient conduct of its business, must not delegate responsibilities to an extent that could create a risk of undermining the quality of internal control, and must maintain separation of duties where appropriate to prevent conflicts of interest. For a consumer credit firm, SYSC 4 means having an organisational chart that reflects the actual allocation of responsibilities, ensuring that no single individual has unchecked authority over critical processes (such as lending decisions, complaints handling, or regulatory reporting), and maintaining documented procedures for all key business processes.",

  "CU-0082": "SYSC 5 requires firms to ensure that employees and agents have the necessary skills, knowledge and expertise to discharge their responsibilities. The firm must employ personnel with the skills, knowledge and expertise necessary for the discharge of the responsibilities allocated to them, and must ensure that the personnel are aware of the procedures which must be followed for the proper discharge of their responsibilities. For a consumer credit firm, this encompasses recruitment standards, induction training, ongoing competence development, and performance management — particularly for customer-facing roles, lending decision-makers, compliance staff, and senior managers. SYSC 5 overlaps with TC (Training and Competence) requirements and the SM&CR fitness and propriety standards.",

  "CU-0083": "SYSC 6 establishes the requirements for a compliance function, internal audit (where proportionate), and financial crime systems and controls. The firm must establish, maintain and implement adequate policies and procedures sufficient to ensure compliance with regulatory requirements, and must employ a compliance function that operates independently and has sufficient authority, resources, expertise and access to all relevant information. SYSC 6 also requires appropriate systems and controls to counter the risk that the firm might be used for financial crime, including anti-money laundering, counter-terrorist financing, fraud prevention, and sanctions screening. For a consumer credit firm, this means a compliance function with appropriate independence and authority, a documented compliance monitoring programme, and robust AML/CTF controls including customer due diligence, transaction monitoring, and suspicious activity reporting.",

  "CU-0084": "SYSC 7 requires firms to maintain risk management policies and processes to identify, measure, manage and report risks to which the firm is or might be exposed. The firm must adopt effective arrangements and strategies to identify, manage and report the risks it is or might be exposed to, and must maintain a risk management function that is established and maintained independently from the business units. For a consumer credit firm, this means maintaining a comprehensive risk register covering credit risk, operational risk, compliance risk, conduct risk, financial crime risk, IT/cyber risk, and emerging risks; establishing risk appetite and tolerance thresholds approved by the board; implementing monitoring and reporting against those thresholds; and ensuring timely escalation of risks that exceed tolerances.",

  "CU-0085": "SYSC 9 requires firms to make and retain adequate records of their business and internal organisation, including all services and transactions undertaken, sufficient to enable the FCA to monitor compliance. Records must be arranged so that they are readily accessible and must be retained for the appropriate period — generally at least five years for FCA-regulated activities, though CCA requirements may extend this. For a consumer credit firm, records retention encompasses: credit agreements and pre-contractual documents, creditworthiness assessments and affordability evidence, customer communications, complaint files, compliance monitoring records, risk management documentation, governance and board minutes, staff training records, regulatory correspondence, and financial crime records including SARs and CDD documentation.",

  "CU-0086": "SYSC 10 requires firms to establish and maintain adequate policies, procedures and organisational arrangements to identify and manage conflicts of interest between the firm and its customers, between different customers, and between the firm's commercial interests and its regulatory obligations. The firm must maintain a conflicts of interest policy that identifies the circumstances that constitute or may give rise to conflicts, specifies the procedures and measures adopted to manage those conflicts, and is kept up to date. For a consumer credit firm, key conflict areas include: tension between lending volume targets and responsible lending obligations; commission and incentive structures for staff and intermediaries; relationships with comparison sites and lead generators; product bundling decisions; and the inherent conflict between the firm's commercial interest in maximising revenue and the customer's interest in obtaining the most suitable and affordable credit.",

  "CU-0087": "SYSC 15A implements the FCA's operational resilience requirements (PS21/3), requiring firms to identify their important business services, set impact tolerances for the maximum tolerable disruption, map the resources supporting those services (people, processes, technology, facilities, information and third-party dependencies), and conduct scenario testing to assess their ability to remain within impact tolerances during severe but plausible disruptions. By March 2025, firms were required to demonstrate they can remain within tolerances for each important business service. For a consumer credit firm, important business services likely include lending decision-making, customer account servicing, payment processing, collections operations, regulatory reporting, and complaints handling. The firm must invest in resilience proportionate to the potential impact of disruption on consumers and markets.",

  "CU-0088": "SYSC 18 establishes the FCA's requirements for internal whistleblowing arrangements, requiring firms to have appropriate mechanisms for employees and workers to report concerns about potential misconduct, regulatory breaches, or other wrongdoing. Firms must establish a whistleblowing champion (typically a non-executive director or senior manager), maintain confidential reporting channels, protect whistleblowers from retaliation, and ensure that reports are investigated and acted upon. The whistleblowing arrangements must be communicated to all staff and must be accessible without fear of retribution. SYSC 18 operates alongside the statutory protections in the Employment Rights Act 1996 (Part IVA — protected disclosures) and the FCA's own external whistleblowing mechanism. For a consumer credit firm, effective whistleblowing arrangements are a critical component of the governance framework, providing a mechanism for identifying and addressing misconduct that might not surface through routine compliance monitoring.",

  "CU-0089": "SYSC 22 governs the giving and requesting of regulatory references for employees who perform or will perform certain functions, including all senior management functions and certification functions under SM&CR. Firms must request references before an individual begins performing a certification function and must provide references when requested by other regulated firms. References must cover a six-year lookback period and must use the prescribed template (SYSC 22 Annex 1), disclosing information about fitness and propriety including disciplinary action, conduct rule breaches, and any determination that the individual was not fit and proper. References must be provided as soon as reasonably practicable (FCA maximum: six weeks) and must be updated if relevant new information emerges after provision. For a consumer credit firm, this applies to hiring senior compliance staff, lending managers, and other certified persons.",

  "CU-0090": "The Senior Managers and Certification Regime (SM&CR), set out in SYSC 24-28, is the FCA's accountability framework for individuals working in financial services. SM&CR has three components: the Senior Managers Regime (requiring FCA approval for individuals performing senior management functions, with prescribed responsibilities and Statements of Responsibilities); the Certification Regime (requiring firms to annually certify that employees performing significant-harm functions are fit and proper); and the Conduct Rules (Individual Conduct Rules applying to all staff, plus Senior Manager Conduct Rules for SMF holders). For a consumer credit firm, SM&CR means clear individual accountability for key business areas, documented Statements of Responsibilities, a Responsibilities Map, annual certification of relevant staff, conduct rules training for all employees, and regulatory reference obligations when staff move between regulated firms.",

  "CU-0091": "SYSC 24 defines the senior management functions (SMFs) that require FCA approval before an individual can perform them. For a consumer credit firm, the minimum SMF requirements typically include SMF1 (Chief Executive), SMF16 (Compliance Oversight), and SMF17 (Money Laundering Reporting Officer), though additional functions may be required depending on the firm's structure and activities. Each SMF holder must have a Statement of Responsibilities (SoR) documenting the areas for which they are personally responsible and the prescribed responsibilities allocated to them. The SoR must be submitted to the FCA as part of the approval process and updated whenever responsibilities change. The FCA assesses SMF applications against the fit and proper criteria in FIT, considering honesty, integrity and reputation; competence and capability; and financial soundness.",

  "CU-0092": "SYSC 25 governs the allocation of prescribed responsibilities to senior managers and the firm's Responsibilities Map. Prescribed responsibilities are specific obligations that the FCA requires to be allocated to named senior managers, ensuring there is always clear individual accountability for key regulatory requirements. Prescribed responsibilities include: responsibility for the firm's compliance with the Conduct Rules; responsibility for the firm's policies and procedures for countering financial crime; responsibility for the firm's compliance with CASS requirements (if applicable); and responsibility for the firm's compliance with the Consumer Duty. The Responsibilities Map is a single document that sets out the firm's management and governance arrangements, showing how responsibilities are allocated across the senior management team and how the firm's governance structure operates in practice.",

  "CU-0093": "SYSC 26 establishes the 'overall responsibility' requirement — every area of the firm's activities must have at least one senior manager with overall responsibility. This prevents gaps in accountability where no individual can be held responsible for a particular area. The requirement ensures that there is always a named senior manager who can be held to account for any part of the firm's business, even where specific prescribed responsibilities are not allocated to that area. For a consumer credit firm, this means the Responsibilities Map must demonstrate complete coverage with no gaps — every business function, support function, and control function must be within the overall responsibility of an identified senior manager.",

  "CU-0094": "SYSC 27 contains the FCA's Conduct Rules, which apply to all staff of authorised firms (not just senior managers). The five Individual Conduct Rules are: (1) act with integrity; (2) act with due skill, care and diligence; (3) be open and cooperative with the FCA, PRA and other regulators; (4) pay due regard to the interests of customers and treat them fairly; (5) observe proper standards of market conduct. The four Senior Manager Conduct Rules add: (SC1) take reasonable steps to ensure that the business is controlled effectively; (SC2) take reasonable steps to ensure that the business complies with relevant regulatory requirements; (SC3) take reasonable steps to ensure that any delegation is to an appropriate person with adequate oversight; (SC4) disclose appropriately any information of which the FCA would reasonably expect notice. All staff must be trained on the Conduct Rules, and breaches must be reported to the FCA.",

  "CU-0095": "SYSC 28 establishes the Certification Regime, requiring firms to annually assess and certify that employees performing 'certification functions' are fit and proper. Certification functions include: significant-harm functions (roles where the person's actions could cause significant harm to the firm or its customers), customer-dealing functions (roles involving direct customer interaction), and other functions specified by the FCA. The fitness and propriety assessment must consider the same criteria as for SMF holders (FIT): honesty, integrity and reputation; competence and capability; and financial soundness. Firms must maintain records of all certification decisions and the evidence supporting them. For a consumer credit firm, certified persons typically include lending decision-makers, collections team leaders, complaints handlers, and other staff whose roles could materially impact customer outcomes.",

  "CU-0096": "COCON (the Code of Conduct Sourcebook) contains the full text of the Individual Conduct Rules and Senior Manager Conduct Rules that apply under SM&CR. All employees of an authorised firm must comply with the Individual Conduct Rules from day one of employment, and firms must notify all relevant staff of the Conduct Rules that apply to them. Breaches of the Conduct Rules must be reported to the FCA within specified timeframes — seven business days for breaches by certified persons, and as soon as reasonably practicable for breaches by senior managers. For a consumer credit firm, COCON compliance requires: comprehensive Conduct Rules training programme covering all staff; clear disciplinary procedures for Conduct Rule breaches; mechanisms for identifying and investigating potential breaches; accurate and timely FCA notifications; and records demonstrating that all staff have been notified of and trained on the rules applicable to their role.",

  "CU-0097": "FIT sets out the criteria for assessing fitness and propriety of employees and senior personnel. The assessment covers three domains: (1) honesty, integrity and reputation — including criminal records, civil proceedings, disciplinary actions, and any matter that could cast doubt on the individual's honesty; (2) competence and capability — including relevant qualifications, training, and experience for the role; and (3) financial soundness — including personal insolvency, CCJs, and other financial difficulties that could create vulnerability to improper influence. For SMF holders, the FCA conducts its own assessment as part of the approval process; for certified persons, the firm must conduct the assessment annually. For a consumer credit firm, the FIT assessment must be conducted at hire, annually for certified persons, and whenever information comes to the firm's attention that could affect an individual's fitness and propriety.",

  // FCA-OTHER section
  "CU-0098": "This category encompasses the wider FCA Handbook sourcebooks beyond CONC, SYSC and PRIN that are applicable to a consumer credit firm. These include General Provisions (GEN) for statutory status disclosure, the Product Governance sourcebook (PROD) for target market identification and product review, the Supervision manual (SUP) for regulatory reporting and notifications, Training and Competence (TC) for staff capability requirements, the Dispute Resolution sourcebook (DISP) for complaints handling, FEES for regulatory levies, and the Compensation sourcebook (COMP) for FSCS obligations. While CONC is the primary operational sourcebook, these ancillary sourcebooks create important obligations around governance, reporting, complaints, and product design that must be integrated into the firm's compliance framework.",

  "CU-0099": "GEN (General Provisions) sets out requirements that apply across all authorised firms, including statutory status disclosure obligations, restrictions on the use of FCA and PRA names and logos, and general requirements for the communication of information. GEN is often overlooked because its requirements seem procedural, but the FCA takes a dim view of firms that fail to comply — particularly with status disclosure requirements — as non-compliance undermines consumer confidence in the regulatory framework. For a consumer credit firm, GEN compliance requires attention to detail in all customer-facing communications, website content, email footers, and marketing materials.",

  "CU-0100": "GEN 4 requires all FCA-authorised firms to disclose their regulatory status in certain communications with clients and potential clients. The disclosure must include: the firm's name as it appears on the FCA Register; its FCA firm reference number; the fact that it is authorised and regulated by the Financial Conduct Authority; and the FCA's contact details. This information must be included in letters, electronic equivalents (including emails), and in the firm's terms of business. For a consumer credit firm, this extends to all first written communications with clients, loan agreements, and marketing materials. The disclosure must be prominently displayed and not obscured. Common failings include omitting the disclosure from email footers, using outdated firm names or reference numbers, and failing to update disclosures following changes in regulatory status.",

  "CU-0101": "GEN 5 restricts the use of FCA and PRA names and logos by authorised firms. Firms must not use the FCA or PRA names or logos in a way that suggests or implies endorsement, approval or recommendation of the firm or its products by the regulator. The FCA register badge may be used on websites and communications to confirm authorised status, but must not be modified or used in a misleading context. For a consumer credit firm, this means ensuring that marketing materials and website content do not create the impression that the FCA endorses the firm's products, and that any reference to FCA authorisation is factually accurate and not misleading.",

  "CU-0102": "PROD (the Product Intervention and Product Governance Sourcebook) implements the FCA's product governance requirements, which are central to the Consumer Duty's Products and Services outcome. PROD requires firms to design products that meet the needs of an identified target market, select appropriate distribution channels, and conduct ongoing monitoring and review throughout the product lifecycle. Product governance is not a one-off compliance exercise but an ongoing obligation to ensure products continue to deliver fair value and meet the needs of the target market. For a consumer credit firm as a product manufacturer, PROD requires documented target market definitions, product approval processes, fair value assessments, distribution channel reviews, and regular product reviews with documented outcomes.",

  "CU-0103": "PROD 1 sets out the overview and application of the Product Governance sourcebook, establishing which firms are in scope as manufacturers or distributors. A manufacturer is a firm that creates, develops, designs or issues a financial product. A distributor is a firm that offers, recommends, sells or provides a product to a customer. For a consumer credit firm that designs and originates its own loan products, the firm is a manufacturer and must comply with the manufacturer requirements including: target market identification at a sufficiently granular level, product testing including value assessment, selection of appropriate distribution channels, and ongoing monitoring of whether products continue to meet target market needs. The FCA expects product governance to be embedded into the firm's product development and review cycles as a genuine end-to-end process.",

  "CU-0104": "PROD 4 provides the detailed product governance rules for manufacturers and distributors, requiring documented product approval processes, target market assessments, distribution arrangements, and ongoing product reviews. Manufacturers must maintain a product approval process for each new product and for significant adaptations of existing products. Distribution requirements mandate that manufacturers carefully select channels appropriate for the target market, provide distributors with sufficient product information, and monitor whether products are reaching the intended audience. For a consumer credit firm, this means having a documented product approval process, maintaining target market assessments, conducting regular product reviews, and ensuring distribution partners have adequate product knowledge. Common failings include vague target market definitions, inadequate product testing, failure to monitor products post-launch, and insufficient manufacturer-distributor communication.",

  "CU-0105": "SUP (the Supervision Manual) establishes the FCA's framework for supervising authorised firms, covering the mechanics of regulatory interaction including approved persons processes, regulatory notifications, reporting requirements, and information-gathering powers. For a consumer credit firm, SUP creates practical obligations around: submitting applications for SMF approval (SUP 10C), notifying the FCA of significant events (SUP 15), submitting regulatory returns on time (SUP 16), and cooperating with supervisory visits and information requests. Understanding SUP is essential for maintaining a productive and compliant regulatory relationship.",

  "CU-0106": "SUP 10C sets out the FCA's regime for approving individuals to perform Senior Management Functions (SMFs), specifying the application process, assessment criteria and ongoing obligations. The FCA must approve any individual before they begin performing an SMF, and the application requires Form A (or Form E for internal transfers), a Statement of Responsibilities, and supporting fitness and propriety evidence. Approved persons must be notified of changes to their details within seven business days using Form D. For a consumer credit firm, the minimum SMFs typically include SMF1 (Chief Executive), SMF16 (Compliance Oversight), and SMF17 (MLRO). Common issues include insufficient competence evidence in applications, delays in submitting change notifications, and failure to withdraw approval promptly when an individual ceases to perform the function.",

  "CU-0107": "SUP 15 establishes the framework for notifications that firms must make to the FCA, covering events and circumstances the regulator needs to know about. The core requirement (Principle 11 and SUP 15.3) obliges firms to notify the FCA of anything it would reasonably expect notice of, including: matters affecting the firm's ability to meet obligations, significant business changes, matters that could result in serious consumer detriment, and any significant rule breach. Specific triggers include management body changes, material business plan changes, significant operational incidents, cyber incidents, actual or potential threshold condition breaches, and civil/criminal/disciplinary proceedings. For a consumer credit firm, common notification triggers include significant complaint volumes or trends, material outsourcing changes, cyber incidents, and changes to key personnel. The FCA expects firms to err on the side of disclosure.",

  "CU-0108": "SUP 16 sets out the regulatory reporting framework, specifying content, format, frequency and submission deadlines for data items and returns the FCA requires. For consumer credit firms, key returns include CCR002 (volumes data), complaints returns under DISP, annual financial returns, and Product Sales Data. Reports must be submitted through RegData, with frequencies varying from quarterly to annually. Late or inaccurate submissions can result in administrative fees, supervisory action, and reputational damage. Common compliance issues include failure to maintain adequate systems for collecting reportable data, missing deadlines, submitting inaccurate data, and not having governance sign-off processes for regulatory returns. Firms should establish a regulatory reporting calendar, designate clear ownership for each return, and implement data quality checks.",

  "CU-0109": "TC (Training and Competence) sets out the FCA's requirements for ensuring that employees who carry out regulated activities are competent. The assessment must not be based solely on experience but should also consider professional qualifications, training, and competency tests. For consumer credit firms, TC is particularly relevant to staff involved in MCD credit activities who must demonstrate appropriate knowledge of consumer credit law, consumer protection requirements, and creditworthiness assessment. Firms must ensure supervisors have coaching, assessment and technical skills to act as competent assessors. Common failings include inadequate initial competence assessment, failure to maintain structured training records, insufficient ongoing monitoring, and supervisors lacking assessment skills.",

  "CU-0110": "DISP (the Dispute Resolution sourcebook) establishes the FCA's comprehensive framework for complaints handling, from internal procedures through to referral to the Financial Ombudsman Service. DISP requires firms to have appropriate and effective internal complaints handling procedures (DISP 1), sets out the FOS's jurisdiction and process (DISP 2), and mandates complaints reporting to the FCA (DISP 1.10). For a consumer credit firm, complaints handling is a critical operational function — complaints data provides insight into systemic issues, informs Consumer Duty outcomes monitoring, and drives continuous improvement. The FCA places significant emphasis on using complaints data to identify root causes and deliver fair outcomes.",

  "CU-0111": "DISP 1 establishes the framework for internal complaints handling, requiring firms to identify and record all complaints, investigate them competently and impartially, and offer redress where appropriate. The FCA defines a complaint broadly as any oral or written expression of dissatisfaction, whether justified or not, about the provision of or failure to provide a financial services activity. Firms must send prompt written acknowledgement, provide a holding response if not resolved within four weeks, and issue a final response within eight weeks. If the complaint cannot be resolved within eight weeks, the firm must inform the customer of their right to refer to the FOS. For a consumer credit firm, common complaint areas include affordability disputes, charging queries, collections conduct, and CRA reporting accuracy.",

  "CU-0112": "DISP 1.3 sets out the specific procedural requirements for complaints handling, mandating written procedures that are freely available to complainants and that enable complaints through any reasonable means. Firms must identify and record complaints promptly, assign them to staff with appropriate authority and competence, handle them fairly and consistently, keep complainants informed of progress, and ensure final responses are clear, fair and not misleading. Complainants dissatisfied with final responses must be informed of their right to refer to the FOS and the time limits for doing so. For a consumer credit firm, procedures must be accessible to vulnerable customers and accommodate different communication needs. Common failings include overly legalistic procedures, failure to update complainants during investigation, and inadequate complaint identification by front-line staff.",

  "CU-0113": "DISP 1.10 requires firms to submit complaints data to the FCA on a biannual basis, providing a breakdown by product type, cause and outcome. Reports must be submitted within 30 business days of each six-month reporting period through RegData. Firms receiving more than 500 complaints in any period must publish a summary promoting transparency. The data is used by the FCA for supervisory purposes, including identifying firms or sectors with higher complaint volumes that may warrant investigation. For a consumer credit firm, accurate categorisation of complaints is essential, and firms should reconcile internal records with the regulatory return before submission. Common issues include inaccurate categorisation, under-reporting where informal complaints are not logged, and discrepancies between internal MI and the regulatory return.",

  "CU-0114": "DISP 2 sets out the jurisdiction and process of the Financial Ombudsman Service (FOS), the independent dispute resolution body that provides consumers with a free alternative to the courts. All FCA-authorised firms are automatically within the FOS compulsory jurisdiction. The FOS determines complaints by reference to what is fair and reasonable in all circumstances — a broader standard than strict legal liability — taking into account law, regulation, codes of practice and good industry practice. Awards can be made up to the statutory maximum (currently £430,000 for complaints about acts from 1 April 2024). For a consumer credit firm, common FOS complaint areas include unaffordable lending, inadequate forbearance, unfair charges, and poor arrears handling. Firms should treat FOS decisions as valuable insight into regulatory expectations and track outcomes as a key risk indicator.",

  "CU-0115": "The FEES sourcebook sets out the fees and levies that FCA-authorised firms must pay to fund the FCA's operations, the Financial Ombudsman Service, the Financial Services Compensation Scheme, and other regulatory bodies. Consumer credit firms fall into specific fee-blocks with rates calculated by reference to annual income from regulated activities. The FCA invoices from July each year with payment typically due within 30 days. Fee rates change annually based on the FCA's budget and the size of the regulated population. Common compliance issues include failure to submit accurate fee tariff data on time (leading to estimated fees), not budgeting for regulatory costs, and missing payment deadlines which can result in administrative penalties.",

  "CU-0116": "COMP (the Compensation Sourcebook) establishes the rules of the Financial Services Compensation Scheme (FSCS), the UK's statutory scheme of last resort that compensates customers when authorised firms fail. All authorised firms contribute to the FSCS through annual levies allocated across funding classes. For consumer credit claims, the current compensation limit is £85,000 per eligible claimant. The FSCS provides a critical safety net for consumers and firms must understand the scope of coverage, levy obligations, and the circumstances under which FSCS protection applies to their products. For a consumer credit firm, FSCS levy obligations should be built into annual budgets, and the firm should be able to explain FSCS coverage to customers as part of its communication obligations.",

  "CU-0117": "MIFIDPRU sets out the prudential requirements for FCA-regulated investment firms, implementing the UK Investment Firms Prudential Regime. While primarily designed for investment firms, MIFIDPRU may apply to consumer credit firms that hold dual permissions covering both credit and investment activities. Where applicable, MIFIDPRU imposes capital, liquidity, concentration risk, and public disclosure requirements. For a consumer credit firm, the key question is whether its permission profile triggers MIFIDPRU applicability — this should be assessed as part of the firm's regulatory perimeter review and periodically reassessed as the business model evolves.",

  // FS-LEG section
  "CU-0118": "This category encompasses the primary Acts of Parliament that establish the UK's financial services regulatory framework and consumer credit regime. These statutes provide the legal foundation for all FCA regulation, define regulated activities requiring authorisation, create the enforcement and disciplinary powers used by the FCA, and establish the statutory rights and obligations that underpin consumer credit law. For a consumer credit firm, understanding the legislative framework is essential not only for compliance but for understanding the legal basis and limits of regulatory requirements — Handbook rules derive their authority from these Acts, and the courts interpret regulatory obligations by reference to the underlying legislation.",

  "CU-0119": "The Financial Services and Markets Act 2000 (FSMA) is the foundational Act establishing the UK's financial regulatory architecture. FSMA grants the FCA its powers, defines regulated activities under the Regulated Activities Order, establishes the financial promotion restriction (section 21), creates the framework for the Financial Ombudsman Service and Financial Services Compensation Scheme, and provides the FCA's enforcement toolkit including powers to impose unlimited fines, issue public censures, vary or cancel permissions, and apply to court for injunctions and restitution orders. FSMA was substantially amended by the Financial Services Act 2012 (creating the FCA from the FSA), the Financial Services Act 2021 (post-Brexit amendments), and the Financial Services and Markets Act 2023 (revoking retained EU law). For a consumer credit firm, FSMA is the ultimate source of the firm's obligations — every FCA Handbook rule traces its authority back to FSMA.",

  "CU-0120": "Section 19 of FSMA establishes the 'general prohibition' — no person may carry on a regulated activity in the United Kingdom, or purport to do so, unless that person is an authorised person or an exempt person. Contravention of the general prohibition is a criminal offence carrying up to two years' imprisonment and/or an unlimited fine on conviction on indictment. For a consumer credit firm, maintaining authorisation is existential — the firm must ensure it holds the correct permissions for all the regulated activities it carries on, must not carry on activities outside the scope of its permissions (the regulatory perimeter), and must meet its threshold conditions for authorisation on an ongoing basis. Any change to the business model or product range should be assessed for regulatory perimeter implications.",

  "CU-0121": "Section 20 of FSMA addresses the consequences of contravening the general prohibition — agreements entered into by unauthorised persons are potentially unenforceable, and the other party may be entitled to recover money paid, compensation for loss, and the return of property transferred. The FCA and affected parties can apply to court to enforce these provisions. For a consumer credit firm, the enforceability risk is critical — if the firm inadvertently carries on a regulated activity without the correct permission, any agreements entered into in connection with that activity could be unenforceable, potentially affecting the firm's entire loan book for the affected activity.",

  "CU-0122": "Section 21 of FSMA establishes the financial promotion restriction — no person may, in the course of business, communicate an invitation or inducement to engage in investment activity or credit-related regulated activity unless: (a) the person is an authorised person, or (b) the content of the communication is approved by an authorised person. Contravention is a criminal offence carrying up to two years' imprisonment. For a consumer credit firm, section 21 means that all financial promotions must either be issued by the firm itself (as an authorised person) or approved by another authorised person. This creates a compliance obligation to ensure that all marketing materials, advertisements, social media content, and communications that constitute financial promotions are within the firm's control and subject to its compliance approval process.",

  "CU-0123": "Part XI of FSMA grants the FCA extensive powers to gather information and conduct investigations. Section 165 empowers the FCA to require authorised firms to provide information or produce documents; section 166 allows the FCA to commission 'skilled person' reports at the firm's expense; and sections 167-169 grant powers to appoint investigators with statutory information-gathering powers. For a consumer credit firm, these powers mean the FCA can at any time request detailed information about the firm's business, require production of documents and records, commission independent reviews of specific areas of the business, and conduct formal investigations where potential breaches are identified. Cooperation with these powers is mandatory (Principle 11), and obstruction or failure to comply is itself a serious regulatory and criminal offence.",

  "CU-0124": "Part XIV of FSMA sets out the FCA's disciplinary and enforcement powers, including the power to: impose unlimited financial penalties on firms and individuals (section 206); issue public censures (section 205); vary or cancel a firm's permissions (section 55J); prohibit individuals from working in financial services (section 56); and apply to court for injunctions, restitution, and winding-up orders. The FCA must follow its published decision-making procedures (DEPP) and the individual has the right to refer the matter to the Upper Tribunal. For a consumer credit firm, understanding the enforcement framework is important for risk assessment — the FCA publishes its enforcement approach, penalty calculation methodology, and previous enforcement outcomes, all of which inform the compliance monitoring programme and risk appetite.",

  "CU-0125": "The Consumer Credit Act 1974 (CCA) is the primary legislation governing the formation, content, execution, cancellation, variation, default, enforcement, and termination of regulated consumer credit agreements. Despite the transfer of consumer credit regulation from the OFT to the FCA in 2014, the CCA remains the statutory foundation — FCA rules in CONC supplement but do not replace CCA requirements. The CCA prescribes mandatory agreement content, form requirements whose non-compliance renders agreements unenforceable, consumer rights including early settlement and withdrawal, and creditor obligations including the provision of information on request. For a consumer credit firm, CCA compliance is not optional — an improperly executed agreement is potentially unenforceable, and certain CCA breaches constitute criminal offences. The CCA and its secondary legislation must be read alongside CONC as a unified framework.",

  "CU-0126": "Part V of the CCA governs the entry into regulated credit agreements, establishing mandatory requirements for the form, content, execution and copies of agreements. Sections 60-65 prescribe what a regulated credit agreement must contain (including prescribed terms, signature requirements, and copies provisions), and the consequences of non-compliance — an improperly executed agreement can only be enforced by order of the court (section 65). For a consumer credit firm, Part V compliance is fundamental to the enforceability of every loan originated — the agreement template must be regularly reviewed against current prescribed requirements, and any changes to terms or format must be legally validated before implementation. Common issues include missing prescribed terms, incorrect execution sequences, and failure to provide the required copies at the correct times.",

  "CU-0127": "Sections 55 to 55C of the CCA establish the statutory pre-contractual disclosure obligations, requiring firms to provide pre-contract credit information (SECCI), adequate explanations, and a creditworthiness assessment before entering into a regulated credit agreement. Section 55A creates the obligation to provide adequate explanations, section 55B imposes the creditworthiness assessment requirement, and section 55C establishes the duty to provide the SECCI. These CCA requirements are supplemented by CONC 2, 4 and 5, creating a comprehensive pre-contractual framework. For a consumer credit firm, compliance requires that the customer journey is designed to deliver all required pre-contractual information at the correct time and in the correct format, with evidence of compliance maintained for each individual agreement.",

  "CU-0128": "Sections 61 to 65 of the CCA prescribe the form and content requirements for regulated credit agreements — the most technically demanding area of CCA compliance. Section 61 requires the agreement to be in the 'prescribed form', section 62 requires a copy to be given to the debtor at the time of making the agreement, section 63 requires a further copy within seven days if the agreement was not made in person, and section 65 provides that an improperly executed agreement can only be enforced by court order. The Consumer Credit (Agreements) Regulations 2010 specify the prescribed terms, content and format in detail. For a consumer credit firm, any deficiency in agreement form or content — no matter how technical — creates an enforceability risk that could affect the entire portfolio. Agreement templates must be drafted by specialist legal counsel and reviewed whenever regulations change.",

  "CU-0129": "Section 66A of the CCA gives the debtor a statutory right to withdraw from a regulated credit agreement within 14 days of the agreement being made, without giving any reason. The debtor must give notice of withdrawal (orally or in writing) to the creditor, and must then repay the credit and any accrued interest within 30 days. The right cannot be waived or restricted by the agreement. For a consumer credit firm, the withdrawal right must be clearly communicated to the customer, the withdrawal process must be simple and accessible, and systems must be capable of accurately calculating the amount repayable (principal plus daily interest). Creating barriers to withdrawal — such as requiring written notice when oral notice is sufficient — could breach both the CCA and the Consumer Duty.",

  "CU-0130": "Sections 77 and 78 of the CCA impose the duty to provide information to the customer on request. Section 77 (fixed-sum credit) and section 78 (running-account credit) require the firm, upon written request and payment of the statutory fee (currently £1), to provide a copy of the executed agreement and a statement of account within 12 working days. Failure to comply renders the agreement unenforceable until the information is provided and constitutes a criminal offence. For a consumer credit firm, this means maintaining robust systems for retrieving historical agreement documentation and generating accurate statements within the statutory timeframe. Common compliance issues include exceeding the 12-working-day deadline, providing incomplete documentation, and failing to recognise valid requests (particularly from debt advice agencies or claims management companies).",

  "CU-0131": "Sections 86B to 86E of the CCA establish the requirement to send Notices of Sums in Arrears (NOSIA) and Subsequent Notices of Sums in Arrears (SNOSIA) to customers who are in arrears. A NOSIA must be sent when the customer has missed two consecutive payments, and subsequent notices must follow at prescribed intervals for as long as the arrears persist. The notices must be in the prescribed form and contain specified information including the amount of arrears, the sum due and unpaid, and the date of the next payment. Failure to send NOSIAs/SNOSIAs at the correct time and in the correct form has enforcement consequences — the agreement is not enforceable while the firm is in default of its NOSIA/SNOSIA obligations. For a consumer credit firm, this requires automated systems that accurately track arrears status and trigger notices at the prescribed intervals.",

  "CU-0132": "Sections 87 to 89 of the CCA prescribe the requirements for serving default notices before taking enforcement action. A creditor cannot terminate the agreement, demand early repayment, recover possession of goods, treat any right of the debtor as terminated, restricted or deferred, or enforce any security, without first serving a default notice in the prescribed form. The notice must specify the breach, the action required to remedy it (if capable of remedy) or the sum to be paid as compensation, and must give the debtor at least 14 days to comply. For a consumer credit firm, the default notice is a critical procedural step before any enforcement action — failure to serve a valid default notice can render subsequent enforcement action unlawful and create significant litigation risk.",

  "CU-0133": "Sections 94 to 97 of the CCA establish the customer's statutory right to complete early settlement of a regulated credit agreement. Section 94 gives the debtor the right to discharge indebtedness early by giving notice and paying the amount calculated in accordance with the regulations. Section 97 requires the creditor to provide a settlement statement within seven working days of a written request. The settlement amount must reflect a proportionate rebate of interest and charges under the Consumer Credit (Early Settlement) Regulations 2004. For a consolidation lender where early settlement is frequent, accurate and timely settlement calculations are essential — errors or delays are a common source of customer complaints and FOS referrals.",

  "CU-0134": "Sections 140A to 140C of the CCA grant the court power to review and reopen unfair credit relationships. Section 140A provides that a court may make an order under section 140B if it determines that the relationship between the creditor and debtor arising out of the agreement is unfair to the debtor because of any of the terms of the agreement, the way the creditor has exercised or enforced rights, or any other thing done or not done by the creditor. The burden of proof is on the creditor to prove fairness. The Supreme Court's decision in Plevin v Paragon confirmed that non-disclosure of commission — without any breach of duty — was sufficient to render the relationship unfair. For a consumer credit firm, this means the fairness assessment extends beyond the agreement's terms to encompass the firm's entire conduct, pricing transparency, treatment in financial difficulty, and the overall value proposition.",

  "CU-0135": "The Financial Services Act 2012 restructured UK financial regulation, replacing the Financial Services Authority with the Financial Conduct Authority (FCA) and the Prudential Regulation Authority (PRA). The Act created the FCA with its statutory objectives: securing an appropriate degree of protection for consumers, protecting the integrity of the UK financial system, and promoting effective competition. It also established the Financial Policy Committee within the Bank of England. For a consumer credit firm, the FSA 2012 is significant as the Act that created the FCA and defined its objectives — the consumer protection objective is the primary lens through which the FCA supervises consumer credit firms.",

  "CU-0136": "The Financial Services Act 2021 made post-Brexit amendments to the UK's financial regulatory framework, including expanding the FCA's rule-making powers, laying the groundwork for the Consumer Duty, and implementing prudential updates. The Act enabled the FCA to revoke and replace retained EU financial services law with UK-specific rules, gave the FCA power to make temporary transitional provisions, and established requirements for the FCA and PRA to have regard to the UK's net-zero emissions target. For a consumer credit firm, the FSA 2021 expanded the FCA's authority and signalled the regulatory direction towards higher consumer protection standards that culminated in the Consumer Duty.",

  "CU-0137": "The Financial Services and Markets Act 2023 (FSMA 2023) is the major post-Brexit reform Act that revokes retained EU financial services law (REUL), replacing it with UK-specific regulation made by the FCA and PRA. The Act introduces a new secondary international competitiveness and growth objective for the FCA (alongside its primary objectives), provisions for access to cash, regulation of cryptoassets, and enhanced powers for the FCA including the ability to publicise enforcement investigations. For a consumer credit firm, FSMA 2023 is significant because the ongoing revocation of REUL means regulatory requirements will continue to evolve as the FCA replaces EU-derived rules with UK-specific provisions — firms must maintain awareness of these changes through active regulatory horizon scanning.",

  // CONSUMER-LEG section
  "CU-0138": "UK consumer protection legislation provides an additional layer of legal obligations beyond FCA regulation, creating enforceable rights for consumers and duties for firms in relation to goods, services, unfair terms, distance selling, and commercial practices. These statutes operate alongside (not instead of) FCA rules, and breaches can result in both civil liability to individual consumers and criminal prosecution by trading standards authorities. The FCA has concurrent enforcement powers for many of these provisions, meaning a consumer credit firm can face regulatory action from the FCA as well as criminal prosecution for the same underlying conduct. Understanding the consumer legislation landscape is essential for comprehensive compliance.",

  "CU-0139": "The Consumer Rights Act 2015 is the UK's principal consumer protection statute, consolidating and modernising earlier legislation. Part 1 covers contracts for goods, digital content and services (requiring services to be performed with reasonable care and skill). Part 2 covers unfair terms in consumer contracts — directly applicable to credit agreements, making terms unenforceable if they cause significant imbalance contrary to good faith. Part 3 provides enforcement powers for the CMA and sector regulators including the FCA. For a consumer credit firm, Part 2 is the most significant: every term in the credit agreement must be assessed for fairness, terms must be transparent (plain, intelligible language) and prominent (brought to the consumer's attention), and the FCA has concurrent enforcement powers to challenge unfair terms. The firm should maintain a documented unfair terms analysis reviewed whenever terms are amended.",

  "CU-0140": "The Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 implement the EU Consumer Rights Directive, establishing requirements for pre-contractual information, cancellation rights, and restrictions on additional charges for distance and off-premises contracts. For online lending, the Regulations require comprehensive pre-contractual information and provide a 14-day cancellation period (running in parallel with CCA withdrawal rights — the more protective right must be communicated). Key provisions include the prohibition on pre-ticked boxes for additional charges (regulation 40) and restrictions on premium-rate telephone helplines for post-contract enquiries (regulation 41). For a consumer credit firm operating digitally, compliance requires that the customer journey incorporates all required distance contract disclosures and that the more favourable cancellation/withdrawal right is clearly communicated.",

  "CU-0141": "The Consumer Protection from Unfair Trading Regulations 2008 (CPRs) prohibit unfair, misleading and aggressive commercial practices towards consumers, creating both criminal offences and (since 2014) private rights of consumer redress. The CPRs establish a general prohibition on unfair commercial practices, specific prohibitions on misleading actions, misleading omissions and aggressive practices, and 31 practices deemed unfair in all circumstances (the 'blacklist'). The 2014 amendments gave consumers rights to unwind contracts, claim discounts and seek damages. For a consumer credit firm, the CPRs apply from advertising through to collections — misleading statements about rates or costs, omitting material information, and aggressive collection tactics can all result in criminal prosecution, civil claims from consumers, and FCA enforcement action. The FCA has concurrent enforcement powers.",

  "CU-0142": "The Unfair Contract Terms Act 1977 (UCTA) restricts the ability to exclude or limit liability through contract terms. Exclusion clauses for death or personal injury caused by negligence are absolutely void; other exclusion clauses are subject to a reasonableness test considering the parties' bargaining positions, inducements offered, availability of alternatives, and insurance considerations. While UCTA's application to consumer contracts has been largely superseded by the Consumer Rights Act 2015, it remains relevant to the firm's business-to-business contracts including supplier agreements, technology contracts, and outsourcing arrangements. For a consumer credit firm, UCTA informs the drafting and enforcement of limitation clauses in commercial agreements.",

  "CU-0143": "The CCA's secondary legislation (Statutory Instruments) provides the detailed, prescribed form and calculation rules that operationalise the Consumer Credit Act 1974. Key SIs include: the Consumer Credit (Agreements) Regulations 2010 (prescribed form and content of credit agreements), Consumer Credit (Disclosure of Information) Regulations 2010 (SECCI form requirements), Consumer Credit (Advertisements) Regulations 2010 (representative APR calculation and display), Consumer Credit (Total Charge for Credit) Regulations 2010 (APR calculation methodology), and Consumer Credit (Early Settlement) Regulations 2004 (settlement rebate calculations). For a consumer credit firm, these SIs contain the precise technical requirements for agreement documentation, pre-contractual information, advertising, and settlement calculations — non-compliance creates enforceability and criminal liability risks.",

  "CU-0144": "The Electronic Commerce (EC Directive) Regulations 2002 apply to 'information society services' — services provided by electronic means, at a distance, at the individual request of the recipient — and impose requirements on online service providers including financial services firms. Key obligations include: providing specified information about the service provider (name, address, registration details, VAT number), ensuring commercial communications are clearly identifiable, making the terms and conditions of the service available in a way that allows storage and reproduction, and following prescribed steps for the formation of electronic contracts. For a consumer credit firm operating primarily through digital channels, the ECRs require that the website and app clearly identify the firm, that the online loan application process follows the prescribed contract formation steps, and that terms are accessible and storable.",
};
