/**
 * Enriched descriptions for PRIN (CU-0001 to CU-0023) and CONC (CU-0024 to CU-0078)
 * These are merged into the master enrichment script.
 */
export const PRIN_CONC_DESCRIPTIONS: Record<string, string> = {
  "CU-0001": "The 12 FCA Principles for Businesses are the foundational obligations binding all FCA-authorised firms, sitting at the apex of the regulatory hierarchy and underpinning every rule in the FCA Handbook. A breach of any Principle is independently actionable by the FCA — the Principles are not merely aspirational statements but enforceable rules carrying the full weight of disciplinary sanctions including unlimited fines, public censure, and permission variation or cancellation. Principles 1 to 5 and 8 to 11 continue to apply alongside the Consumer Duty (Principle 12), while Principles 6 and 7 are superseded by Principle 12 for activities within the Consumer Duty's scope. The FCA has historically used Principles as the primary basis for enforcement action where specific Handbook rules do not capture the misconduct, and compliance with the Principles requires a culture of genuine commitment rather than box-ticking. For a consumer credit firm, every business decision — from product design through to collections — must be tested against the Principles.",

  "CU-0002": "Principle 1 requires a firm to conduct its business with integrity, meaning honesty, fair dealing, and adherence to proper standards of conduct. Integrity extends beyond mere compliance with rules to encompass the spirit of regulation and reasonable expectations of honest business conduct. The FCA interprets this broadly — a firm acts without integrity if it misleads customers, manipulates processes for commercial advantage, fails to honour commitments, or engages in sharp practices even where no specific rule is breached. For a consumer credit firm, integrity permeates every aspect of operations: honest representation of product terms in marketing, transparent pricing without hidden fees, genuine affordability assessments that are not designed to maximise approvals at the expense of suitability, and collections practices that do not exploit customers' vulnerability or lack of knowledge. The FCA has imposed some of its largest fines under Principle 1, including penalties for deliberate mis-selling, manipulation of benchmark rates, and systemic failures to treat customers honestly.",

  "CU-0003": "Principle 2 requires a firm to conduct its business with due skill, care and diligence, establishing that competence is not merely aspirational but a regulatory obligation enforceable by the FCA. This encompasses the firm's systems, processes, and the capability of its personnel — the FCA expects firms to invest in adequate resources, maintain appropriate expertise, and exercise professional judgment in their operations. For a consumer credit firm, this means ensuring that underwriting models are statistically sound and regularly validated, that customer-facing staff are properly trained in regulatory requirements and product features, that IT systems are robust and adequately tested, and that management receives timely and accurate information to make informed decisions. Failures of skill, care and diligence are commonly identified in enforcement actions involving poor-quality affordability assessments, inadequate systems testing leading to customer detriment, and insufficient oversight of outsourced functions. The standard is measured objectively against what a reasonably competent firm would do in the same circumstances.",

  "CU-0004": "Principle 3 requires a firm to take reasonable care to organise and control its affairs responsibly and effectively, with adequate risk management systems. This is the governance and controls Principle, requiring firms to maintain clear organisational structures, defined reporting lines, effective internal controls, appropriate management information, and robust risk management frameworks proportionate to the nature and scale of the business. For a consumer credit firm, compliance requires a well-defined management structure with SM&CR accountability fully embedded, an effective three-lines-of-defence model, documented risk appetite with tolerance thresholds, and management information that enables timely identification and escalation of emerging risks. The FCA assesses Principle 3 compliance by examining governance minutes, MI packs, risk and compliance reports, internal audit findings, and the timeliness and quality of senior management responses to identified issues. Common pitfalls include insufficiently independent compliance functions, failure to act on red flags identified through monitoring, poor change management, and delegation without adequate oversight.",

  "CU-0005": "Principle 4 requires a firm to maintain adequate financial resources, encompassing sufficient capital and liquidity to meet obligations as they fall due, absorb unexpected losses, and wind down in an orderly fashion if required. For a consumer credit firm, this means maintaining compliance with the applicable prudential framework, ensuring adequate provisions for expected credit losses, and holding sufficient liquid assets to continue servicing customers through stressed scenarios. The FCA expects firms to conduct their own internal capital and liquidity adequacy assessments — not simply meet minimum regulatory thresholds — and to demonstrate forward-looking awareness of risks that could erode their financial position. Common risks include inadequate provisioning for credit impairments during economic downturns, over-reliance on single funding lines, failure to stress-test capital adequacy under adverse scenarios, and growing too rapidly without maintaining proportionate capital buffers.",

  "CU-0006": "Principle 5 requires a firm to observe proper standards of market conduct, supporting the integrity, transparency and orderly functioning of financial markets. Although primarily associated with wholesale market conduct, Principle 5 applies to all authorised firms and is relevant to consumer credit firms in the context of fair competitive practices, accurate public disclosures, transparent pricing, and not engaging in practices that undermine market confidence. For a consumer credit lender, this includes ensuring that pricing is not predatory, that representative APR examples are genuinely representative, that the firm does not engage in anti-competitive practices such as price-fixing or market-sharing with competitors, and that any benchmark or reference rate usage is appropriate. The FCA will act under Principle 5 where a firm's conduct could harm the proper functioning of the market or undermine confidence in the UK financial system.",

  "CU-0007": "Principle 6 is the foundation of the FCA's Treating Customers Fairly (TCF) regime, requiring firms to pay due regard to the interests of customers and treat them fairly at every stage of the product lifecycle. For retail customer activities, Principle 6 is now superseded by the higher standard of Principle 12 (the Consumer Duty) where the Duty applies, but it remains in force for activities outside the Consumer Duty's scope and continues to inform regulatory expectations around fair treatment. For a consumer credit firm, Principle 6 historically required ensuring products are designed with customer needs in mind, marketing is not misleading, affordability assessments are robust, customers in financial difficulty are treated with forbearance, and complaints are handled fairly and promptly. The FCA has used Principle 6 to take enforcement action in cases of systematic unfair treatment, including excessive charges, failure to provide adequate explanations, and poor complaint outcomes.",

  "CU-0008": "Principle 7 establishes the 'clear, fair and not misleading' standard underpinning all customer-facing communications, financial promotions, marketing materials, pre-contractual disclosures, periodic statements, and digital content. For retail customer activities now subject to the Consumer Duty, Principle 7 is superseded by Principle 12 and the Consumer Understanding outcome (PRIN 2A.5), which sets a higher bar by requiring firms to actively ensure customer understanding rather than merely providing information that is not misleading. For a consumer credit firm, all communications — from app notifications and marketing emails through to SECCI documents, loan agreements, arrears letters and settlement statements — must be presented in language customers can actually understand, with key information given appropriate prominence and without buried disclaimers or misleading emphasis. The FCA has imposed significant fines for Principle 7 breaches, including cases involving renewal letters that falsely implied competitive pricing and promotions that obscured material terms.",

  "CU-0009": "Principle 8 requires firms to identify, prevent or manage all actual and potential conflicts of interest that could adversely affect customers. For a consumer credit firm, conflicts commonly arise between the firm's commercial interest in maximising revenue (through higher interest rates, fees, or loan volumes) and the customer's interest in obtaining an affordable, suitable product — this tension is at the heart of responsible lending. Additional conflicts may arise where the firm uses intermediaries or introducers incentivised to generate volume rather than quality, where staff remuneration structures reward lending targets over customer outcomes, or where the firm has relationships with debt management companies. The FCA expects firms to maintain a conflicts of interest policy aligned with SYSC 10, a conflicts register, and appropriate organisational arrangements including information barriers, remuneration controls, and independent oversight of product design decisions.",

  "CU-0010": "Principle 9 applies where a firm gives advice or exercises discretion on behalf of a customer, requiring reasonable care to ensure that any such advice or discretionary decision is suitable. For consumer credit firms, this is particularly relevant where the firm provides guidance, recommendations, or makes decisions that customers reasonably rely upon — for example, recommending a particular loan product, term, or repayment structure, or making forbearance decisions during financial difficulty. Although consumer credit lending is not typically classified as 'advice' in the regulatory sense, the FCA takes a broad view of where customers may reasonably rely on a firm's expertise, and any personalised recommendation or guided customer journey that leads to a particular credit decision may attract Principle 9 obligations. Firms should ensure clear delineation between information provision and advice, and train staff to recognise when they may be crossing the advice boundary.",

  "CU-0011": "Principle 10 requires firms to safeguard any client money or assets for which they are responsible, maintaining appropriate custody, segregation, and reconciliation arrangements. For most consumer credit firms, Principle 10 has limited direct application because lenders do not typically hold client assets in the traditional sense — however, it becomes relevant where the firm handles customer funds in transit (such as loan disbursement or repayment processing), operates trust accounts, or manages any form of customer deposits or prepayments. Where applicable, firms must comply with the Client Assets sourcebook (CASS) requirements, including maintaining adequate client money calculations, performing regular reconciliations, and ensuring customer funds are properly segregated. Even where a consumer credit firm considers Principle 10 to have low applicability, it should document this assessment and ensure that any transitory handling of customer funds is adequately controlled.",

  "CU-0012": "Principle 11 is the foundation of the regulatory relationship, requiring firms to proactively engage with the FCA in an open, transparent and cooperative manner — this is not a passive obligation but requires active disclosure of matters the FCA would reasonably expect to know about, even without being asked. For a consumer credit firm, this means timely notification of material changes to the business (including changes to senior management, business model pivots, significant IT incidents, material complaints trends, and breaches of regulatory requirements), full cooperation with supervisory visits and information requests, and candid responses to section 165 and section 166 notices. The FCA treats failures under Principle 11 as aggravating factors in enforcement proceedings and has consistently imposed increased penalties where firms have failed to be open, delayed disclosures, or provided misleading information. Firms should establish clear regulatory notification policies with defined triggers, maintain a regulatory engagement log, and ensure the compliance function has appropriate authority to escalate matters to the FCA promptly.",

  "CU-0013": "Principle 12, which came into force on 31 July 2023 for new products and 31 July 2024 for closed books, represents the most significant shift in UK retail financial services regulation in a generation. Unlike Principles 6 and 7 which it supersedes for in-scope retail activities, Principle 12 requires firms to proactively deliver good outcomes rather than merely avoid causing harm — it imposes a positive obligation to ensure customers achieve results consistent with their reasonable expectations. For a consumer credit firm, every aspect of the business — from product design and pricing through to marketing, onboarding, servicing, forbearance and complaints — must be deliberately oriented towards delivering demonstrably good outcomes, with particular attention to customers in vulnerable circumstances. The Consumer Duty is operationalised through three cross-cutting rules and four outcomes detailed in PRIN 2A. The FCA has signalled this will be its primary supervisory and enforcement tool for retail market conduct, and boards must produce an annual Consumer Duty assessment.",

  "CU-0014": "PRIN 2A contains the detailed requirements implementing the Consumer Duty, translating the overarching Principle 12 into specific, actionable obligations. It establishes three cross-cutting rules (act in good faith, avoid foreseeable harm, enable customers to pursue financial objectives), four outcomes (products and services, price and value, consumer understanding, consumer support), and governance obligations including annual board assessments and outcomes monitoring. PRIN 2A applies to all firms involved in the manufacture or distribution of products and services to retail customers, including firms in the distribution chain that do not have a direct customer relationship but whose activities materially influence retail customer outcomes. For a consumer credit firm, PRIN 2A requires systematic, evidence-based compliance across the entire product lifecycle, with documented target markets, fair value assessments, consumer testing of communications, and accessible support processes.",

  "CU-0015": "PRIN 2A.1 defines the scope of the Consumer Duty, establishing which firms, activities, products and services fall within its ambit. The Duty applies to all firms involved in the manufacture or distribution of products and services to retail customers, including firms in the distribution chain whose activities materially influence retail customer outcomes — this 'chain of responsibility' approach means manufacturers, distributors, intermediaries and platforms all bear proportionate responsibility. The Duty extends to both open (new) and closed (legacy) products, with the closed book deadline having passed on 31 July 2024. Where Principle 12 and PRIN 2A apply, Principles 6 and 7 do not apply to the same activity, as the Consumer Duty imposes a higher standard; however, Principles 1 to 5, 8 to 11 continue to apply alongside. Firms must document their scope assessment, identifying all in-scope products, services and customer segments, and maintain this as a living document updated when new products are launched or business models evolve.",

  "CU-0016": "The three cross-cutting rules under PRIN 2A.2 are the interpretive backbone of the Consumer Duty, setting overarching behavioural standards across all four outcomes. The first rule — acting in good faith (PRIN 2A.2.1R) — requires firms to act honestly, fairly, openly and consistently with reasonable expectations, though it does not prevent pursuing legitimate commercial interests. The second rule — avoiding foreseeable harm (PRIN 2A.2.5R) — requires that product design, terms, marketing, sale and support do not cause foreseeable harm, and that the firm does not exploit customers' behavioural biases, lack of knowledge, or vulnerability characteristics; however, firms are not responsible for all harm where customers accept inherent risks with informed consent. The third rule — enabling financial objectives (PRIN 2A.2.8R) — requires proactive steps to put customers in a position to make informed decisions, going beyond information provision to genuine empowerment. For a consumer credit firm, every customer interaction must be assessed against all three standards simultaneously.",

  "CU-0017": "The Products and Services outcome (PRIN 2A.3) requires that products and services are designed to meet the needs, characteristics and objectives of customers in an identified target market, and that distribution strategies ensure products reach the intended audience. Manufacturers must define and document the target market at a sufficiently granular level, identify groups for whom the product is not designed, stress-test features against adverse scenarios, and maintain audit trails for product sign-off decisions. For a consumer credit firm, each loan product must have a formally documented target market definition — specifying the customer need it addresses (e.g. debt consolidation to reduce total interest cost), the customer characteristics it is designed for, and the customers for whom it would be unsuitable. Distributors must ensure their arrangements are consistent with the manufacturer's target market assessment. The FCA expects robust product governance processes aligned with PROD requirements and evidenced regular review cycles.",

  "CU-0018": "The Price and Value outcome (PRIN 2A.4) requires that the total price paid by retail customers bears a reasonable relationship to the overall benefits received, evidenced through a structured fair value assessment. Firms must assess fair value by considering: the nature and quality of the product including benefits and limitations; all fees, charges and costs over the product lifetime; the firm's costs; and whether any customer groups receive differential value. For a consumer credit firm, this directly applies to interest rates, arrangement fees, late payment charges, early settlement calculations and ancillary charges — the FCA does not cap prices but expects documented analysis demonstrating each pricing element delivers fair value. The FCA's review of fair value frameworks found good practice includes clear analysis of the relationship between interest rates and cost of funds, regular benchmarking, and willingness to reduce unjustifiable charges. Differential pricing is permitted but must be justified, with each cohort assessed independently.",

  "CU-0019": "The Consumer Understanding outcome (PRIN 2A.5) requires firms to ensure their communications support and enable customers to make effective, timely and properly informed decisions. This goes beyond the former 'clear, fair and not misleading' standard by requiring firms to test and evidence actual customer understanding, not merely the absence of misleading content. For a consumer credit firm, pre-contractual information, adequate explanations, financial promotions, SECCI documents, periodic statements, arrears communications and all digital content must be designed with genuine comprehension in mind, using plain language, appropriate emphasis on key terms, and effective formatting for the channel used. The FCA expects consumer testing of key communications, monitoring of engagement metrics as proxies for understanding, and adaptation where evidence suggests customers are not adequately informed. Common compliance risks include information overload, legal language that fails to communicate effectively, and failure to tailor communications for vulnerable customers.",

  "CU-0020": "The Consumer Support outcome (PRIN 2A.6) requires firms to design and deliver customer support that meets needs throughout the entire product lifecycle, including in situations of financial difficulty. Firms must ensure customers can access support easily and without unreasonable barriers, and that friction is not applied asymmetrically (e.g. making it easy to take out a product but difficult to cancel or switch). For a consumer credit firm, this outcome has particular significance for arrears management, forbearance and complaints handling — the FCA expects customers in financial difficulty can access support through their preferred channel without excessive waiting times, that forbearance options are proactively communicated, and that the firm does not create barriers to switching, early settlement or cancellation that serve only commercial interests. The FCA assesses compliance by examining customer journey analytics, channel accessibility data, complaint volumes, time-to-resolution metrics, and whether support processes have been tested with vulnerable customers.",

  "CU-0021": "PRIN 2A.7 establishes the governance requirements for the Consumer Duty, mandating that the firm's board or governing body must review and approve an annual assessment of whether the firm is delivering good outcomes for retail customers. This assessment must consider evidence from all four outcomes, the cross-cutting rules, and the firm's management information on customer outcomes. The board must maintain oversight of the firm's Consumer Duty compliance on an ongoing basis and must ensure that appropriate senior management accountability exists — under SM&CR, a prescribed responsibility for Consumer Duty oversight must be allocated to a named senior manager. For a consumer credit firm, the annual board report should include analysis of outcomes data segmented by customer characteristics, identification of differential outcomes between customer groups, root cause analysis of any poor outcomes identified, and action plans for remediation. The FCA expects boards to challenge the evidence presented, not simply rubber-stamp management assurances.",

  "CU-0022": "PRIN 2A.8 requires firms to monitor outcomes on an ongoing basis, identify where customers or groups of customers are not receiving good outcomes, and take appropriate action to address any shortfalls. This is not a retrospective compliance exercise but an ongoing, real-time obligation to track customer outcomes across all four outcome areas and the cross-cutting rules. For a consumer credit firm, outcomes monitoring should encompass: product-level analysis (are products meeting target market needs), price and value metrics (are customers receiving fair value, with particular attention to differential outcomes), consumer understanding indicators (engagement rates, comprehension testing, complaint themes suggesting misunderstanding), and support metrics (channel accessibility, resolution times, forbearance effectiveness, complaint handling). The FCA expects firms to collect and analyse data segmented by customer characteristics including vulnerability indicators, and to take prompt corrective action where poor outcomes are identified — delays in remediation are themselves a potential Consumer Duty breach.",

  "CU-0023": "PRIN 2A.9 requires firms to produce and review adequate management information (MI) on outcomes for retail customers, ensuring that relevant decision-makers can identify poor outcomes and take timely action. The MI must be sufficiently granular to reveal differential outcomes between customer groups, must be produced at appropriate frequencies, and must be reviewed by individuals with the authority and accountability to drive change. For a consumer credit firm, Consumer Duty MI should include: approval rates and average APR by customer segment, complaint volumes and root causes by product and customer characteristic, arrears and forbearance outcomes, customer satisfaction and NPS scores, fair value assessment results, communication engagement metrics, and vulnerability identification rates. The MI should be reported to both executive management and the board, with clear escalation triggers for poor outcomes. The FCA expects the MI framework itself to be subject to regular review, ensuring it remains fit for purpose as the business, customer base, and risk profile evolve.",

  "CU-0024": "CONC is the FCA's primary sourcebook governing consumer credit activities, containing the most directly applicable and operationally significant rules for any consumer credit firm. It covers the full lifecycle of credit from financial promotions (CONC 3) through pre-contractual requirements (CONC 4), responsible lending and affordability (CONC 5), post-contractual requirements including statements and early settlement (CONC 6), to arrears, default and recovery (CONC 7). Additional chapters address debt advice (CONC 8), credit reference agencies (CONC 9), cancellation rights (CONC 11), knowledge and competence (CONC 14), and connected lender liability (CONC 15). CONC implements and supplements the Consumer Credit Act 1974 requirements within the FCA's regulatory framework. For a consumer credit firm, CONC compliance is not optional or aspirational — breaches can result in enforcement action, fines, consumer redress schemes, and in the most serious cases, cancellation of permissions.",

  "CU-0025": "CONC 1 establishes the application, scope and purpose of the Consumer Credit Sourcebook, defining which firms, activities and products fall within its ambit. The chapter confirms that CONC applies to every firm with an FCA permission to carry on a credit-related regulated activity, including entering into regulated credit agreements as lender, exercising or having the right to exercise the lender's rights and duties under such agreements, credit broking, debt counselling, debt adjusting, debt collecting, and operating an electronic system in relation to lending. CONC 1 also sets out the relationship between CONC and other FCA sourcebooks — where CONC contains specific provisions, they generally take precedence over more general Handbook rules. Understanding CONC 1 is essential for correctly mapping which CONC obligations apply to each of the firm's regulated activities and for identifying any exemptions or modifications that may be relevant.",

  "CU-0026": "CONC 2 establishes the general conduct of business standards for consumer credit firms, setting out overarching behavioural requirements that apply across all credit-related activities. The chapter addresses pre-contractual requirements, adequate explanations, distance marketing, unfair business practices, mental capacity, and general standards of professional conduct. CONC 2 operates as the behavioural foundation upon which more specific requirements in later chapters are built — a firm that breaches CONC 2 may face enforcement action even where no specific breach of a later chapter can be identified. For a consumer credit firm, CONC 2 compliance means maintaining professional conduct in every customer interaction, ensuring pre-contractual information is timely and complete, providing adequate explanations tailored to the individual customer, not engaging in unfair or aggressive commercial practices, and having appropriate procedures for identifying and responding to customers who may lack mental capacity.",

  "CU-0027": "CONC 2.2 establishes the general conduct standards for consumer credit firms, including the fundamental prohibition on lending practices that lead to customers taking on more debt than they can afford. A firm must not pursue a practice of making credit available (or increasing an existing credit limit) in circumstances where the credit is not affordable, or where there are other factors which suggest that the lending could be detrimental to the customer. This also encompasses the prohibition on imposing charges that are excessive for the service provided. CONC 2.2 sets the tone for the entire sourcebook — it is a broad, principles-based rule that captures conduct which may not be caught by more specific provisions but which is nonetheless harmful to customers.",

  "CU-0028": "CONC 2.3 sets out general pre-contractual requirements specifying the level of information that must be provided to prospective borrowers and the timing of that provision. Firms must ensure that customers receive adequate pre-contractual information in good time before they become bound by the credit agreement, allowing them to compare products and make an informed decision. The information must be provided in a clear, concise manner using the prescribed formats where applicable. For a consumer credit firm operating online, the timing requirements mean that information must be presented at a point in the customer journey where the customer can genuinely assess and compare — not buried at the final stage of a checkout-style process. Failure to provide adequate pre-contractual information can render agreements unenforceable under the CCA 1974.",

  "CU-0029": "CONC 2.4 requires the provision of the Standard European Consumer Credit Information (SECCI) form before a regulated credit agreement is entered into. The SECCI must be provided in good time before the borrower becomes bound by the agreement, using the prescribed format that enables comparison across providers. The SECCI must contain specified information including: the type of credit, the total amount of credit, the duration, the borrowing rate and APR, the total amount payable, the amount/number/frequency of repayments, any security required, and the existence of a right to withdraw. For a consumer credit firm, the SECCI is a mandatory pre-contract document that must be embedded into the customer journey — it cannot be substituted by the firm's own marketing materials or summary documents. Failure to provide the SECCI in the correct format and at the correct time is a common compliance failing that can lead to FCA enforcement action.",

  "CU-0030": "CONC 2.5 requires firms to provide adequate explanations to enable borrowers to assess whether the agreement is suited to their needs and financial situation. The explanations must cover: the features of the agreement that may make it unsuitable for particular types of use, how much the borrower will have to pay, the consequences of failing to make payments on time, and the right to withdraw. The adequacy of the explanation is assessed from the customer's perspective — it must be sufficient for the particular individual, taking into account their characteristics and the complexity of the product. For an online consumer credit firm, adequate explanations must be incorporated into the digital customer journey in a way that promotes genuine understanding rather than mere information provision. This is closely linked to the Consumer Duty's Consumer Understanding outcome and the FCA expects firms to test whether their explanations are actually understood.",

  "CU-0031": "CONC 2.6 addresses requirements for credit brokers, including the obligation to disclose their status as a broker (not a lender), the identity of lenders with whom they have arrangements, and any commission or fee receivable from the lender. Where a broker charges a fee, the fee must be agreed with the customer before any work is done, and the customer must be informed of their right to cancel and receive a refund if no credit agreement results. For a consumer credit firm that uses broker channels or acts as an introducer, CONC 2.6 is directly relevant to the disclosure obligations that apply to broker relationships — the firm must ensure that any intermediaries properly disclose their relationship, and that commission arrangements do not create undisclosed conflicts of interest that could result in unsuitable lending.",

  "CU-0032": "CONC 2.7 imposes additional requirements for distance contracts — credit agreements entered into by means of distance communication (online, phone, mail) without face-to-face contact. Given that most modern consumer credit is originated through digital channels, these requirements apply to virtually all online lending. The firm must provide comprehensive pre-contract information including the total price, the arrangements for payment and performance, the existence of a right to cancel, and the firm's complaints handling procedure. The information must be provided in a clear and comprehensible manner, appropriate to the means of distance communication used. For an app-based or web-based lender, this means the digital customer journey must incorporate all required distance marketing disclosures in a manner that is genuinely accessible and not buried in scrollable terms.",

  "CU-0033": "CONC 2.8 prohibits unfair, misleading and aggressive commercial practices in relation to consumer credit, implementing the Consumer Protection from Unfair Trading Regulations 2008 (CPRs) in the consumer credit context. A firm must not engage in misleading actions (providing false or deceptive information), misleading omissions (hiding or providing unclear material information), or aggressive practices (using harassment, coercion or undue influence to impair the customer's freedom of choice). The prohibition covers the entire customer lifecycle from marketing through to collections. For a consumer credit firm, common unfair practices include: creating a false sense of urgency in marketing, misrepresenting the speed or certainty of approval, omitting material information about charges from promotions, and using aggressive debt collection techniques that exploit vulnerability or fear.",

  "CU-0034": "CONC 2.9 provides supplementary provisions on unfair business practices, extending the protections in CONC 2.8 to address specific practices including pressure selling, exploitation of vulnerability, and inappropriate product bundling. A firm must not pressure customers into taking credit that is not in their interests, must not exploit customers' lack of knowledge or experience, and must not bundle ancillary products with credit in a manner that is not transparent or that creates barriers to the customer's ability to shop around. For a consumer credit firm, CONC 2.9 reinforces the requirement that the customer's interests must be at the centre of every interaction — commercial pressure to meet lending targets or product attachment rates cannot override the obligation to treat customers fairly and not exploit their circumstances.",

  "CU-0035": "CONC 2.10 provides guidance on dealing with customers who may lack the mental capacity to enter into or manage a regulated credit agreement. A firm must have appropriate policies and procedures to identify customers who may lack capacity, and must not enter into a credit agreement with a customer whom it reasonably suspects lacks the capacity to understand and consent to the agreement. Where capacity concerns arise during an existing agreement (for example, during collections), the firm must take appropriate steps to ensure the customer's interests are protected, including considering whether a third party with appropriate legal authority (such as a lasting power of attorney holder) should be involved. This guidance intersects with the Mental Capacity Act 2005, the Equality Act 2010, and the FCA's vulnerability guidance (FG21/1), and is operationally critical for collections and forbearance teams.",

  "CU-0036": "CONC 3 governs all financial promotions and communications by consumer credit firms, requiring that every promotion — whether in print, online, on social media, or verbal — is clear, fair and not misleading. The chapter establishes both general principles (CONC 3.2-3.3) and specific rules for credit agreement promotions (CONC 3.5), high-cost short-term credit (CONC 3.6), P2P lending (CONC 3.7), debt services (CONC 3.8), and real-time communications (CONC 3.10). CONC 3 also implements the Consumer Credit (Advertisements) Regulations 2010, requiring prescribed content and format for credit advertisements including the representative APR calculation. Under the Consumer Duty, financial promotions must not only avoid being misleading but must actively support customer understanding. For a consumer credit firm, CONC 3 governs every piece of external communication — from Google Ads and Instagram posts to comparison site listings and email campaigns.",

  "CU-0037": "CONC 3.1 defines the application and scope of the financial promotions rules, establishing what constitutes a 'financial promotion' for consumer credit purposes. A financial promotion is an invitation or inducement to engage in a credit-related regulated activity, communicated in the course of business. This captures a wide range of communications including advertisements, marketing emails, social media posts, comparison site listings, and even verbal recommendations. CONC 3.1 also sets out exemptions — certain communications are excluded from the financial promotions rules, including one-to-one communications that are not part of a marketing campaign. Understanding the scope of CONC 3.1 is essential for ensuring that all promotional communications are captured by the firm's compliance approval process.",

  "CU-0038": "CONC 3.2 establishes the core rule that every financial promotion must be clear, fair and not misleading. This is the fundamental standard against which all consumer credit communications are assessed. 'Clear' means the communication must be easily understood by the target audience, with information presented in a logical order and without unnecessary complexity. 'Fair' means the communication must present a balanced picture of the product, including both benefits and risks, and must not emphasise benefits to the exclusion of important limitations or costs. 'Not misleading' means the communication must not create a false or deceptive impression, whether by what it includes, what it omits, or how information is presented. Under the Consumer Duty, the bar is raised further — promotions must actively support informed decision-making.",

  "CU-0039": "CONC 3.3 sets out general requirements for financial promotions including rules on prominence (key information must be given at least equal prominence to the most prominent claim), identification (the firm must be clearly identified), risk warnings (appropriate warnings about the risks of credit must be included), and comparisons (any comparison with another product must be meaningful and not misleading). For a consumer credit firm, these requirements mean that headline claims about low rates or easy approval must be accompanied by equally prominent information about the total cost of credit, representative APR, and any conditions. The FCA has taken enforcement action against firms that buried important information in footnotes, used misleading percentage claims, or failed to include adequate risk warnings in social media advertisements.",

  "CU-0040": "CONC 3.5 contains the specific rules for financial promotions relating to credit agreements not secured on land, including the representative example requirements that are central to consumer credit advertising. Where a promotion includes a specific interest rate, amount of credit, or any other cost trigger, it must also include a representative example showing: the borrowing rate, whether fixed or variable; the nature and amount of any charges; the total amount of credit; the representative APR; the duration; the total amount payable; and the amount of each repayment. The representative APR must reflect at least 51% of the business expected from the promotion. For a consumer credit firm, CONC 3.5 compliance is critical to all advertising activity — incorrect or incomplete representative examples are a frequent source of FCA enforcement action and ASA complaints.",

  "CU-0041": "CONC 3.6 contains additional financial promotion rules specific to high-cost short-term credit (HCSTC) products, including mandatory risk warnings and restrictions on targeting. While not directly applicable to a non-HCSTC consumer credit firm, CONC 3.6 is relevant for understanding the regulatory framework's approach to higher-risk credit products and the enhanced protections the FCA imposes where products carry greater risk of customer detriment. The prescribed risk warning for HCSTC products must state: 'Warning: Late repayment can cause you serious money problems. For help, go to moneyhelper.org.uk'. Understanding CONC 3.6 is also valuable for compliance monitoring purposes, to ensure the firm's own products are not inadvertently classified as HCSTC.",

  "CU-0042": "CONC 3.7 sets out promotion rules specific to peer-to-peer (P2P) lending agreements, requiring additional disclosures about the nature of the lending arrangement and the risks specific to P2P platforms. While not directly applicable to a traditional consumer credit lender, CONC 3.7 is relevant where the firm's business model involves any element of peer-to-peer or marketplace lending. The key additional requirements include disclosure that the platform is not a bank and deposits are not protected by the FSCS, clear explanation of the risk of capital loss, and transparency about the platform's role in the lending process.",

  "CU-0043": "CONC 3.8 addresses promotion rules for debt counselling, debt adjusting and debt management services. While primarily relevant to debt advice firms, CONC 3.8 applies to any consumer credit firm that promotes forbearance services, debt management options, or support for customers in financial difficulty. Promotions for debt services must not trivialise the seriousness of debt, must not suggest that debt management is a simple or painless solution, and must clearly disclose any charges. For a consumer credit firm, this is relevant when communicating forbearance options or signposting to debt advice services — such communications must be balanced and not create unrealistic expectations about the ease of resolving financial difficulties.",

  "CU-0044": "CONC 3.9 prescribes the specific risk warning text that must be included in all HCSTC promotions. The warning must be displayed prominently and in a manner that is likely to be read by the target audience. While not applicable to non-HCSTC providers, understanding CONC 3.9 is relevant for compliance teams monitoring the broader regulatory landscape and ensuring the firm's products are correctly classified. The prescribed warning text directs consumers to the MoneyHelper service for free and impartial guidance.",

  "CU-0045": "CONC 3.10 addresses real-time (verbal) financial promotions, including telephone conversations and live chat interactions. Real-time promotions are subject to the same clear, fair and not misleading standard as written promotions, but the rules recognise the different nature of verbal communication. Firms must ensure that call centre scripts and live chat templates include all required information, that staff are trained to provide balanced information without creating pressure, and that verbal promotions are recorded and monitored for compliance. For a consumer credit firm with outbound sales or customer service teams, CONC 3.10 means that every verbal interaction that could constitute a promotion — including follow-up calls, cross-sell offers, and retention discussions — must comply with the same standards as written advertisements.",

  "CU-0046": "CONC 4 establishes the detailed pre-contractual disclosure requirements for consumer credit, specifying the timing, format and content of information that must be provided before a customer enters into a regulated credit agreement. The chapter implements the CCA 1974 requirements and the Consumer Credit (Disclosure of Information) Regulations 2010, requiring firms to provide the Standard European Consumer Credit Information (SECCI) document, adequate explanations, and other prescribed pre-contractual information. CONC 4 is operationally critical because failure to comply with pre-contractual disclosure requirements can render agreements unenforceable under the CCA — this is not merely a regulatory risk but a commercial and legal risk that could affect the enforceability of the firm's entire loan book.",

  "CU-0047": "CONC 4.2 sets out the detailed requirements for providing pre-contract credit information (SECCI) and adequate explanations to borrowers before they become bound by a credit agreement. The SECCI must be provided in good time to allow the customer to compare products and make an informed decision — 'good time' is assessed in context but must be genuinely meaningful, not a formality at the point of signature. The information must be presented using the prescribed SECCI format, which enables standardised comparison across providers. For an online lender, the SECCI must be integrated into the digital journey at a point where the customer can genuinely review and absorb the information — presenting it only at the final click-to-accept stage is unlikely to meet the 'good time' requirement.",

  "CU-0048": "CONC 4.3 specifies the detailed content requirements for adequate explanations, building on the general obligation in CONC 2.5. Adequate explanations must cover: the features of the agreement that may make it unsuitable for particular types of use; how much the borrower will have to pay periodically and in total; the consequences of failing to make payments on time (including late payment charges, default reporting to CRAs, and potential legal action); the effect of exercising the right to withdraw within 14 days; and how to complain. The explanations must be tailored to the customer's circumstances — a one-size-fits-all approach is unlikely to satisfy the requirement for adequacy. For a consumer credit firm's digital journey, this means dynamic content that responds to the specific product, amount, and term the customer has selected, presented in a format that promotes genuine understanding.",

  "CU-0049": "CONC 5 is the FCA's responsible lending chapter and represents the single most important operational compliance obligation for any consumer credit firm. It requires firms to conduct a creditworthiness assessment before making a regulated credit agreement, encompassing both credit risk assessment (the risk the borrower will not repay) and affordability assessment (the impact of repayments on the borrower's financial situation). CONC 5 establishes that responsible lending is not merely a commercial risk management exercise but a consumer protection obligation — lending to a customer who cannot afford the repayments is a regulatory breach regardless of whether the lender is willing to accept the credit risk. The FCA's approach to CONC 5 enforcement has evolved significantly, with increasing focus on the quality and robustness of affordability assessments and the firm's ability to demonstrate that lending decisions were responsible.",

  "CU-0050": "CONC 5.2 establishes the core creditworthiness assessment obligation: before making a regulated credit agreement, the firm must undertake a reasonable and proportionate assessment of the customer's creditworthiness, having regard to both the credit risk and the customer's ability to make repayments without suffering adverse consequences. The assessment must be based on sufficient information obtained from the customer and, where appropriate, from a credit reference agency. 'Reasonable and proportionate' is assessed in context — factors include the type and amount of credit, the risk presented by the customer, and the potential impact of the credit on the customer. For a consumer credit firm offering consolidation loans, the creditworthiness assessment must specifically consider whether the consolidation will genuinely improve the customer's financial position, not merely replace existing debts with a new obligation.",

  "CU-0051": "CONC 5.2A imposes additional creditworthiness requirements including the obligation to take account of the customer's committed expenditure and to obtain and verify income information where appropriate. The firm must consider not just the customer's current financial position but foreseeable future changes in circumstances, and must not rely solely on automated credit scoring without adequate human oversight of the assessment process. For a consumer credit firm, CONC 5.2A means that income must be verified through reliable means (such as Open Banking data, payslips, or bank statements), committed expenditure must be realistically assessed (including existing credit commitments, housing costs, and essential living expenses), and the overall assessment must demonstrate that the customer can afford repayments without undue difficulty. The FCA distinguishes between 'affordability' (can the customer make the payments) and 'sustainability' (can the customer make the payments without adverse consequences to their lifestyle and wellbeing).",

  "CU-0052": "CONC 5.3 addresses creditworthiness requirements for credit brokers, requiring that brokers do not introduce customers to lenders where there are reasonable grounds to suspect the credit would be unaffordable. Brokers must take reasonable steps to assess whether the credit is likely to be affordable before making an introduction. For a consumer credit firm that uses broker channels, CONC 5.3 is relevant because the firm retains ultimate responsibility for the creditworthiness assessment — a broker's assessment does not substitute for the lender's own obligations under CONC 5.2. The firm must ensure that broker-originated applications are subject to the same rigorous affordability standards as direct applications.",

  "CU-0053": "CONC 5.4 requires firms to establish and maintain clear, effective policies and procedures for responsible lending that are consistently applied across the business. The policies must address how creditworthiness assessments are conducted, what information is obtained and verified, how income and expenditure are assessed, and the criteria for approving or declining applications. The policies must be documented, regularly reviewed, and updated to reflect changes in the firm's risk appetite, product range, or regulatory expectations. For a consumer credit firm, the lending policy is the operational expression of CONC 5 compliance — it must be sufficiently detailed to ensure consistent decision-making, sufficiently flexible to accommodate individual circumstances, and supported by adequate management information to monitor adherence and outcomes.",

  "CU-0054": "CONC 5.5 contains the specific affordability requirements, requiring firms to assess whether the customer can afford repayments without suffering adverse consequences. The assessment must consider the customer's income, existing credit commitments, essential living expenses, and any other reasonably foreseeable expenditure. The firm must not assume that the customer will reduce existing commitments to afford new credit, and must not rely on the customer's own assessment of affordability without verification. For a consumer credit firm specialising in debt consolidation, affordability assessment is particularly nuanced — the firm must demonstrate that the consolidation loan will genuinely improve the customer's financial position by reducing total interest costs, simplifying payments, or both, and that the customer can sustainably afford the consolidated repayment over the full term. The FCA expects firms to be able to evidence their affordability assessment for every individual lending decision.",

  "CU-0055": "CONC 6 establishes the post-contractual obligations that apply throughout the life of a regulated credit agreement, from execution through to settlement or write-off. The chapter covers periodic statements of account (CONC 6.4), early settlement rights and calculations (CONC 6.5), the right to withdraw within 14 days (CONC 6.3), arrears and default notification requirements (CONC 6.7), and general post-contract conduct standards (CONC 6.2). For a consumer credit firm, CONC 6 compliance requires robust systems for generating accurate statements at prescribed intervals, calculating settlement figures promptly and correctly, honouring the 14-day withdrawal right, and identifying the early signs of financial difficulty that trigger the enhanced obligations under CONC 7. Post-contract failures are a frequent source of FCA enforcement action and FOS complaints.",

  "CU-0056": "CONC 6.2 sets out the general conduct obligations that apply after a credit agreement has been entered into, requiring fair treatment throughout the life of the agreement and prohibiting the exploitation of vulnerability or financial difficulty. A firm must not take action that is not proportionate to the customer's circumstances, must not add unnecessary charges, and must ensure that all post-contract communications are clear and fair. For a consumer credit firm, CONC 6.2 provides the overarching standard against which all post-contract interactions are assessed — from routine account management through to arrears handling and settlement negotiations.",

  "CU-0057": "CONC 6.3 implements the customer's statutory right to withdraw from a regulated credit agreement within 14 days of execution, without giving any reason. The customer must repay the credit and any interest accrued within 30 days of giving notice of withdrawal. Firms must have clear processes for handling withdrawals, including calculating the precise amount to be repaid and ensuring that any products or services linked to the credit are unwound appropriately. For a consumer credit firm, the withdrawal right must be clearly communicated in the agreement and in post-contract documentation, and the withdrawal process must be simple and accessible — creating barriers to exercise of the withdrawal right is a breach of both CONC and the Consumer Duty's Consumer Support outcome.",

  "CU-0058": "CONC 6.4 requires firms to provide periodic statements of account to borrowers, containing prescribed information about the balance outstanding, payments made, interest charged, and the amount and date of the next payment due. Statements must be provided in a durable medium at prescribed intervals (at least annually for fixed-sum credit). Firms must also respond promptly to reasonable requests for information about the agreement. For a consumer credit firm, this requires robust systems for generating accurate, compliant statements and maintaining comprehensive records of all post-contract communications. Common compliance issues include calculation errors (particularly around interest accrual and partial payments), late issuance of statements, and failure to comply with prescribed content requirements.",

  "CU-0059": "CONC 6.5 governs early settlement, requiring firms to provide a settlement figure upon request, calculate it accurately in accordance with the CCA provisions, and ensure customers are not penalised for exercising their statutory right to repay early. The settlement figure must reflect a proportionate rebate of interest and charges under the Consumer Credit (Early Settlement) Regulations 2004. Firms must provide the settlement figure promptly and ensure it remains valid for a reasonable period. For a consolidation lender where early settlement is particularly frequent, robust systems for calculating accurate settlement figures at volume are essential. Common compliance issues include calculation errors, delays in providing figures, and applying incorrect early settlement fees.",

  "CU-0060": "CONC 6.7 addresses the firm's obligations when a customer falls into arrears or default, providing the bridge between general post-contract requirements (CONC 6) and the comprehensive arrears and collections framework (CONC 7). CONC 6.7 requires firms to take appropriate action where there are signs of actual or possible financial difficulty, including contacting the customer to discuss their position, offering forbearance where appropriate, and signposting to free debt advice services. Firms must not take disproportionate action against a customer, and must ensure their arrears management approach aligns with the detailed requirements of CONC 7. For a consumer credit firm, early identification of financial difficulty and prompt, proportionate response is both a regulatory obligation and a key driver of customer outcomes.",

  "CU-0061": "CONC 7 is the comprehensive chapter governing how firms must treat customers in arrears, default, or subject to debt recovery proceedings. It is one of the most operationally significant chapters for consumer credit firms, as it directly governs day-to-day collections activity and has a material impact on customer outcomes. The overarching requirement is that firms must treat customers with forbearance and due consideration, pay due regard to their interests, and not take disproportionate action. CONC 7 covers policies and procedures (7.2), treatment in arrears/default including forbearance (7.3), default notices (7.4), debt collection communications (7.5), continuous payment authorities (7.6), lenders' responsibilities (7.9), signposting to debt advice (7.10), breathing space (7.11), and customers with mental health difficulties (7.15). The FCA has strengthened protections repeatedly, most recently through PS24/2 on enhanced support for customers in financial difficulty.",

  "CU-0062": "CONC 7.2 requires firms to establish, implement and maintain clear, effective and appropriate policies and procedures for dealing with customers in or approaching arrears or default. The policies must ensure fair and appropriate treatment of all customers, with particular attention to those who the firm understands or suspects to be vulnerable. The firm must ensure that the effectiveness of these policies, and compliance with them, is reviewed at appropriate intervals. Policies must cover identification of customers in financial difficulty, escalation procedures, training requirements for collections staff, and the range of forbearance options available. The most common compliance failing is having policies that look good on paper but are not consistently applied in practice — the FCA expects firms to evidence that policies translate into actual customer outcomes through MI, quality assurance, and case file reviews.",

  "CU-0063": "CONC 7.3 is the core section on treating customers in default or arrears, requiring forbearance and due consideration taking into account individual circumstances. Examples of appropriate forbearance include: suspending, reducing, waiving or cancelling further interest or charges; allowing time to find a repayment solution; agreeing token payments for a reasonable period; considering alternatives to formal recovery; and signposting to free debt advice. Where a firm has entered into a sustainable repayment arrangement, it must ensure debt does not rise during the arrangement — meaning interest and charges must be reduced, waived or cancelled to the extent necessary. Firms must not take disproportionate action, threaten court action to pressurise customers, or claim recovery costs where no contractual right exists. This section is subject to intensive FCA supervisory scrutiny and is central to the Consumer Duty's Consumer Support outcome.",

  "CU-0064": "CONC 7.4 implements the CCA 1974 requirements for default notices and notices of sums in arrears (NOSIA/SNOSIA). Before taking enforcement action (such as commencing litigation or filing a default with CRAs), the firm must serve a default notice in the prescribed form giving the customer at least 14 days to remedy the breach. NOSIAs must be sent when two payments are missed, and subsequent NOSIAs (SNOSIAs) at prescribed intervals thereafter. Failure to comply with these notice requirements can render the agreement unenforceable. For a consumer credit firm, NOSIA/SNOSIA compliance requires automated systems that accurately track arrears status, trigger notices at the correct points, use the prescribed format and content, and maintain an auditable record of every notice issued and delivered.",

  "CU-0065": "CONC 7.5 prohibits unfair, oppressive and improper debt collection practices. A firm must not subject a customer to harassment, undue pressure, or coercion in connection with debt recovery. Specifically, firms must not: contact customers at unreasonable times or with unreasonable frequency; use threatening or intimidating language; misrepresent the consequences of non-payment; falsely imply legal proceedings have been or will be commenced; use confusing legal language or misleading documents; or make undue use of statutory demands. Recovery costs may only be claimed where there is a genuine contractual right. Firms engaging third-party collectors must ensure they comply with the same standards. Common compliance issues include excessive contact frequencies, inadequate record-keeping of customer interactions, and failing to recognise and respond to signs of vulnerability during recovery.",

  "CU-0066": "CONC 7.6 governs the use of continuous payment authorities (CPAs) in collections, imposing strict restrictions introduced to address widespread consumer harm from repeated, unauthorised payment attempts. A firm may only make two attempts to collect a payment by CPA on any given due date, and may not take partial payments. If a CPA payment fails, the firm must not attempt to collect again without first contacting the customer and obtaining express consent. When a customer cancels a CPA, the firm must cease exercising its rights immediately. Firms must maintain detailed records of all CPA payment requests (including refusals) and customer consents. The most common compliance failing is exceeding the permitted number of CPA attempts or continuing to take payments after the customer has withdrawn consent.",

  "CU-0067": "CONC 7.9 imposes specific obligations on lenders (as distinct from debt collectors) regarding the management of customers in arrears. A firm must not refuse to deal with a not-for-profit debt advice body or other person acting on the customer's behalf without objectively justifiable reason. The firm must give due consideration to reasonable repayment proposals and, where it rejects a proposal, must provide clear written explanation of the reasons. Lenders must ensure repayment arrangements are sustainable — an arrangement is unlikely to be sustainable if it means the customer cannot meet priority debts and essential living expenses. The section also addresses the firm's responsibilities when selling or outsourcing debt, requiring reasonable steps to ensure fair treatment continues. Common failings include refusing to engage with debt advice agencies, setting unaffordable minimum repayment thresholds, and inadequate oversight of outsourced collections.",

  "CU-0068": "CONC 7.10 requires firms to signpost customers in financial difficulty to free, independent debt advice services. The signposting must be proactive — firms should direct customers to organisations such as MoneyHelper, StepChange, Citizens Advice, and other approved free debt advice providers, and should not signpost to fee-charging debt management companies. The obligation arises at the point the firm becomes aware or ought reasonably to be aware that the customer may be experiencing financial difficulty. For a consumer credit firm, signposting must be embedded into arrears communications (including letters, emails, SMS and call scripts), and staff must be trained to provide the signposting in a genuine and helpful manner rather than as a compliance formality.",

  "CU-0069": "CONC 7.11 requires firms to comply with the Debt Respite Scheme (Breathing Space), implemented by the Debt Respite Scheme (Breathing Space Moratorium and Mental Health Crisis Moratorium) (England and Wales) Regulations 2020. During a standard breathing space period (60 days), the firm must freeze enforcement action, not apply interest or charges to the breathing space debt, and not contact the customer to request payment of the debt (contact to provide essential information, such as regulatory communications, is permitted). During a mental health crisis breathing space, the protections continue for as long as the individual's mental health crisis treatment plus 30 days. The firm must take positive steps: update systems to reflect the moratorium, ensure no automated debt collection activity is triggered, and communicate with the insolvency service within prescribed timescales. Breach of breathing space is enforceable by the court and can result in penalties.",

  "CU-0070": "CONC 7.12 provides detailed forbearance requirements, specifying the range of forbearance options that firms must actively consider for customers in financial difficulty. These include: reducing payments to an affordable level; accepting token payments for a reasonable period; suspending, reducing, waiving or cancelling interest and charges; accepting that the debt will be repaid over a longer period; not pursuing enforcement action while the customer is genuinely engaged in finding a solution; and considering writing off the debt where the customer has no realistic prospect of repayment. The firm must not adopt a one-size-fits-all approach but must assess each customer's individual circumstances and offer forbearance that is genuinely tailored and sustainable. The FCA expects firms to monitor forbearance outcomes and to use this data to continually improve their approach to supporting customers in difficulty.",

  "CU-0071": "CONC 7.15 addresses the treatment of customers with mental health difficulties or mental capacity limitations during arrears and collections. Firms must have procedures to identify customers who may lack capacity, and must not pursue recovery in a manner that takes advantage of incapacity. Where a customer lacks capacity, the firm should consider whether a responsible third party (such as a lasting power of attorney holder) can act on their behalf. Staff must be trained to recognise indicators of mental health difficulties and capacity limitations and to escalate such cases to specialist teams. The practical challenge is that capacity may fluctuate, requiring ongoing reassessment. This section intersects with the Mental Capacity Act 2005, the Equality Act 2010 (disability as a protected characteristic), and the FCA's vulnerability guidance, creating a multi-layered set of obligations for firms dealing with vulnerable customers in collections.",

  "CU-0072": "CONC 8 sets out the rules applicable to firms providing debt counselling, debt adjusting, and credit information services. While primarily relevant to debt advice providers rather than lenders, CONC 8 is important for consumer credit firms to understand because it governs the entities their customers may engage with when in financial difficulty, and because certain lending activities (such as providing guidance on repayment options) may inadvertently cross into debt counselling territory. Key requirements include conducting reasonable assessments of the customer's financial circumstances before giving advice, presenting advice in a durable medium, and not recommending debt solutions that are unaffordable. Understanding CONC 8 helps a consumer credit firm engage more effectively with debt advice agencies acting on behalf of customers.",

  "CU-0073": "CONC 9 governs credit reference agency responsibilities and the firm's obligations in credit reporting, implementing certain obligations derived from section 159 of the CCA 1974. When a CRA removes or amends an entry, it must notify all recipients of the original information. Consumers have a statutory right to add a notice of correction to their credit file. For a consumer credit firm that reports to and uses CRA data, CONC 9 creates obligations around: accuracy of data reported (ensuring account status, balances and payment histories are correctly recorded), timeliness of reporting (updating CRA records promptly when circumstances change, including when disputes are resolved), and dispute handling (investigating accuracy disputes within prescribed timeframes and correcting errors). CRA data accuracy is a frequent source of FOS complaints and ICO enforcement action, and errors can cause significant customer harm.",

  "CU-0074": "CONC 10 addresses connected obligations arising from consumer credit agreements, including prudential requirements for debt management firms and requirements relating to client money. For debt management firms, CONC 10 requires maintaining prudential resources equal to the higher of £5,000 or 0.25% of total value of relevant debts under management. Client money requirements mandate segregation from the firm's own funds, accurate record-keeping, and regular reconciliation. While the prudential provisions are primarily relevant to debt management firms, the principles of CONC 10 inform the broader expectations around financial resilience and client money handling that apply to all consumer credit firms.",

  "CU-0075": "CONC 11 governs cancellation and withdrawal rights for consumer credit agreements, primarily implementing the Distance Marketing Directive's cancellation provisions alongside the CCA 1974's withdrawal rights. A customer has the right to cancel certain distance contracts within 14 days without penalty or reason. For credit agreements, the withdrawal right under section 66A CCA provides a separate 14-day period beginning the day after agreement execution (or the day after documentation is received, if later). If the customer withdraws, they must repay the credit and accrued interest within 30 days. Firms must clearly communicate the existence and terms of the withdrawal/cancellation right in pre-contract and post-contract documentation. Common compliance issues include failing to start the cancellation clock correctly, not providing adequate information about how to exercise the right, and creating barriers to withdrawal that discourage customers from exercising their statutory entitlement.",

  "CU-0076": "CONC 13 provides non-binding guidance supplementing the responsible lending and affordability assessment obligations in CONC 5. The guidance addresses the firm's obligations under sections 77, 78 and 79 of the CCA 1974 to provide information to customers upon request. Section 77 (fixed-sum credit) and section 78 (running-account credit) require the firm to provide a copy of the executed agreement and a statement of account within 12 working days. Failure to comply renders the agreement unenforceable until the information is provided and constitutes a criminal offence. For a consumer credit firm, CONC 13 provides important interpretive context for the responsible lending obligations, helping firms understand the FCA's expectations around creditworthiness assessment methodology, income verification standards, and the treatment of different types of expenditure.",

  "CU-0077": "CONC 14 sets out requirements for staff involved in consumer credit activities to have appropriate knowledge and competence. The chapter requires firms to ensure that employees who carry out activities within scope of CONC have the necessary knowledge of consumer credit law, consumer protection requirements, and the process of assessing creditworthiness. Firms must assess competence at the outset, provide appropriate training and supervision, and reassess competence regularly. Common failings include inadequate initial competence assessment of new joiners, failure to maintain structured training records, insufficient ongoing competence monitoring when roles change, and supervisors who lack the skills to assess competence effectively. For a consumer credit firm, CONC 14 means that every staff member involved in lending decisions, customer service, collections, or compliance must be demonstrably competent in their role.",

  "CU-0078": "CONC 15 addresses connected lender liability under section 75 of the Consumer Credit Act 1974, which makes the creditor jointly and severally liable with the supplier for breach of contract or misrepresentation in certain debtor-creditor-supplier agreements. While section 75 is most commonly associated with credit card transactions, it can apply to other credit arrangements where there is a 'connection' between the credit and the supply transaction. For a consumer credit firm offering consolidation loans, section 75 liability is generally less directly relevant (as consolidation loans are debtor-creditor agreements, not debtor-creditor-supplier agreements), but the firm should understand the framework in case any of its products or arrangements create the necessary connection. Understanding CONC 15 is also important for handling customer complaints that invoke section 75 claims.",
};
